### ISSUE TITLE
FootprintTest.cleanOldClaims is not stable

### ISSUE THREAD

**Issue by krzyk** [zerocracy/farm#1032]
`FootprintTest.cleanOldClaims` sometimes fails, I once saw it in [travis](https://travis-ci.org/zerocracy/farm/builds/380839701) and now it failed also on my local machine:

```
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.138 sec <<< FAILURE! - in com.zerocracy.pm.FootprintTest
cleanOldClaims(com.zerocracy.pm.FootprintTest)  Time elapsed: 1.127 sec  <<< FAILURE!
java.lang.AssertionError: 

Expected: <1L>
     but: was <0L>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at com.zerocracy.pm.FootprintTest.cleanOldClaims(FootprintTest.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:393)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Running com.zerocracy.radars.github.RbMilestoneTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in com.zerocracy.radars.github.RbMilestoneTest
Running com.zerocracy.tools.SignatureTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 sec - in com.zerocracy.tools.SignatureTest

Results :

Failed tests: 
  FootprintTest.cleanOldClaims:100 
Expected: <1L>
     but: was <0L>

Tests run: 353, Failures: 1, Errors: 0, Skipped: 7
```

Please make it stable.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by g4s8** [comment]
@krzyk yes, it's a known issue: https://github.com/zerocracy/farm/issues/1050

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1032` is not assigned, can't get performer
