### ISSUE TITLE
NPE in Saxon

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#1037]
Very rarely I see this exception when building locally. I believe, there is some concurrency issue inside Saxon. Let's fix somehow (maybe synchronize).

```
Caused by: java.lang.NullPointerException
	at net.sf.saxon.functions.FunctionLibraryList.bind(FunctionLibraryList.java:105)
	at net.sf.saxon.functions.FunctionLibraryList.bind(FunctionLibraryList.java:105)
	at net.sf.saxon.expr.parser.XPathParser.parseFunctionCall(XPathParser.java:3189)
	at net.sf.saxon.expr.parser.XPathParser.parseBasicStep(XPathParser.java:2076)
	at net.sf.saxon.expr.parser.XPathParser.parseStepExpression(XPathParser.java:1957)
	at net.sf.saxon.expr.parser.XPathParser.parseRelativePath(XPathParser.java:1882)
	at net.sf.saxon.expr.parser.XPathParser.parsePathExpression(XPathParser.java:1844)
	at net.sf.saxon.expr.parser.XPathParser.parseSimpleMappingExpression(XPathParser.java:1858)
	at net.sf.saxon.expr.parser.XPathParser.parseUnaryExpression(XPathParser.java:1713)
	at net.sf.saxon.expr.parser.XPathParser.parseExprSingle(XPathParser.java:660)
	at net.sf.saxon.expr.parser.XPathParser.parseExpression(XPathParser.java:595)
	at net.sf.saxon.expr.parser.XPathParser.parsePredicate(XPathParser.java:2029)
	at net.sf.saxon.expr.parser.XPathParser.parseStepExpression(XPathParser.java:1967)
	at net.sf.saxon.expr.parser.XPathParser.parseRemainingPath(XPathParser.java:1919)
	at net.sf.saxon.expr.parser.XPathParser.parsePathExpression(XPathParser.java:1813)
	at net.sf.saxon.expr.parser.XPathParser.parseSimpleMappingExpression(XPathParser.java:1858)
	at net.sf.saxon.expr.parser.XPathParser.parseUnaryExpression(XPathParser.java:1713)
	at net.sf.saxon.expr.parser.XPathParser.parseExprSingle(XPathParser.java:660)
	at net.sf.saxon.expr.parser.XPathParser.parseExpression(XPathParser.java:595)
	at net.sf.saxon.expr.parser.XPathParser.parse(XPathParser.java:466)
	at net.sf.saxon.expr.parser.ExpressionTool.make(ExpressionTool.java:103)
	at net.sf.saxon.xpath.XPathEvaluator.compile(XPathEvaluator.java:194)
	at net.sf.saxon.xpath.XPathEvaluator.evaluate(XPathEvaluator.java:233)
	at org.xembly.XpathDirective.traditional(XpathDirective.java:143)
	at org.xembly.XpathDirective.exec(XpathDirective.java:98)
	at org.xembly.Xembler.apply(Xembler.java:155)
	at org.xembly.Xembler.applyQuietly(Xembler.java:129)
	at com.zerocracy.Xocument.modify(Xocument.java:248)
```

**Comment by 0crat** [comment]
Job [#1037](https://github.com/zerocracy/farm/issues/1037) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#1037](https://github.com/zerocracy/farm/issues/1037) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1701428081); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by krzyk** [comment]
@yegor256 I did 170 builds and haven't seen a single NullPointerException in the logs, maybe it got fixed by accident during the last 29 days?

**Comment by krzyk** [comment]
@yegor256 could you take a look here?

**Comment by yegor256** [comment]
@krzyk I don't think running a build many times will help. We should create a heavy multi-threaded test, which will make those `Xocument.modify()` calls from different threads to the same document. This may reproduce the problem. If not, commit the test and we'll call it a day.

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by krzyk** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/1037#issuecomment-400185569))

@krzyk The user @krzyk[/z](https://www.0crat.com/u/krzyk) resigned from [#1037](https://github.com/zerocracy/farm/issues/1037), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
The job [#1037](https://github.com/zerocracy/farm/issues/1037) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1900042116); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by carlosmiranda** [comment]
@yegor256 see PR #1383. I wasn't able to reproduce the same exception, but confirmed via a unit test that `Xocument` is not thread safe when modifying the same file.

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#1385](https://github.com/zerocracy/farm/issues/1385) is still not solved.

**Comment by carlosmiranda** [comment]
@yegor256 #1383 has been merged, may we close this now?

**Comment by yegor256** [comment]
@carlosmiranda thanks!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1037](https://github.com/zerocracy/farm/issues/1037) is now out of scope

**Comment by 0crat** [comment]
Order was finished, quality is "good": +38 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#unknown]() is still not solved.
