### ISSUE TITLE
IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/staff/elections/elect_perform...

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#1078]
https://sentry.io/zerocracy/farm/issues/530551984/

```
SoftException: Job `gh:yegor256/wring#26` is not estimated yet
    at com.zerocracy.pm.cost.Estimates.get(Estimates.java:171)
...
(77 additional frame(s) were not displayed)

UncheckedIOException: com.zerocracy.SoftException: Job `gh:yegor256/wring#26` is not estimated yet
    at com.zerocracy.pm.staff.ranks.RnkEstimates.lambda$new$0(RnkEstimates.java:51)
    at com.zerocracy.pm.staff.ranks.RnkEstimates.compare(RnkEstimates.java:65)
    at com.zerocracy.pm.staff.ranks.RnkEstimates.compare(RnkEstimates.java:33)
    at com.zerocracy.stk.pm.staff.elections.elect_performer$_exec_closure1.doCall(elect_performer.groovy:79)
    at com.zerocracy.stk.pm.staff.elections.elect_performer.exec(elect_performer.groovy:78)
...
(73 additional frame(s) were not displayed)

InvocationTargetException: None
    at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:115)
...
(40 additional frame(s) were not displayed)

IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/staff/elections/elect_performer.groovy
    at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:125)
    at com.zerocracy.farm.StkSafe.process(StkSafe.java:81)
    at com.zerocracy.farm.reactive.StkSmart.process(StkSmart.java:66)
    at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:82)
    at com.zerocracy.farm.reactive.Brigade.lambda$apply$0(Brigade.java:64)
...
(37 additional frame(s) were not displayed)

java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/staff/elections/elect_performer.groovy
```

full stack:

```
com.zerocracy.SoftException: Job `gh:sunsofterp/portal#65` is not estimated yet
    at com.zerocracy.pm.cost.Estimates.get(Estimates.java:171)
    at org.cactoos.func.SyncBiFunc.apply(SyncBiFunc.java:73)
    at org.cactoos.func.UncheckedBiFunc.lambda$apply$0(UncheckedBiFunc.java:59)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
    at org.cactoos.func.UncheckedBiFunc.apply(UncheckedBiFunc.java:60)
    at com.zerocracy.pm.staff.ranks.RnkEstimates.lambda$new$0(RnkEstimates.java:51)
    at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
    at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
    at com.zerocracy.pm.staff.ranks.RnkEstimates.compare(RnkEstimates.java:65)
    at com.zerocracy.pm.staff.ranks.RnkEstimates.compare(RnkEstimates.java:33)
    at java.util.TimSort.countRunAndMakeAscending(TimSort.java:356)
    at java.util.TimSort.sort(TimSort.java:220)
    at java.util.Arrays.sort(Arrays.java:1512)
    at java.util.ArrayList.sort(ArrayList.java:1462)
    at java_util_List$sort$0.call
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at java_util_List$sort$0.call
    at com.zerocracy.stk.pm.staff.elections.elect_performer$_exec_closure1.doCall(elect_performer.groovy:79)
    at sun.reflect.GeneratedMethodAccessor16.invoke
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:272)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
    at groovy.lang.Closure.call(Closure.java:423)
    at groovy.lang.Closure.call(Closure.java:439)
    at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1373)
    at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1366)
    at org.codehaus.groovy.runtime.dgm$149.invoke
    at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
    at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
    at com.zerocracy.stk.pm.staff.elections.elect_performer.exec(elect_performer.groovy:78)
    at sun.reflect.GeneratedMethodAccessor154.invoke
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:115)
    at com.zerocracy.farm.StkSafe.process(StkSafe.java:81)
    at com.zerocracy.farm.reactive.StkSmart.process(StkSmart.java:66)
    at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:82)
    at com.zerocracy.farm.reactive.Brigade.lambda$apply$0(Brigade.java:64)
    at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
    at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
    at org.cactoos.iterator.Filtered.hasNext(Filtered.java:90)
    at org.cactoos.iterator.LengthOf.lambda$new$0(LengthOf.java:52)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
    at org.cactoos.scalar.NumberEnvelope.doubleValue(NumberEnvelope.java:113)
    at org.cactoos.iterable.LengthOf.lambda$new$0(LengthOf.java:51)
    at org.cactoos.scalar.NumberEnvelope.lambda$new$1(NumberEnvelope.java:73)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
    at org.cactoos.scalar.NumberEnvelope.intValue(NumberEnvelope.java:98)
    at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:67)
    at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:37)
    at org.cactoos.func.IoCheckedBiFunc.lambda$apply$0(IoCheckedBiFunc.java:60)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:61)
    at com.zerocracy.farm.reactive.DefaultFlush.process(DefaultFlush.java:98)
    at com.zerocracy.farm.reactive.DefaultFlush.lambda$exec$0(DefaultFlush.java:67)
    at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
    at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
    at org.cactoos.func.IoCheckedFunc.lambda$apply$0(IoCheckedFunc.java:59)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:59)
    at org.cactoos.func.IoCheckedProc.exec(IoCheckedProc.java:57)
    at com.zerocracy.pm.Claims.take(Claims.java:150)
    at com.zerocracy.farm.reactive.DefaultFlush.exec(DefaultFlush.java:66)
    at com.zerocracy.farm.reactive.DefaultFlush.exec(DefaultFlush.java:44)
    at com.zerocracy.farm.reactive.AsyncFlush.lambda$exec$2(AsyncFlush.java:118)
    at com.jcabi.log.VerboseCallable.call(VerboseCallable.java:173)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:221)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 I believe it's critical, we are getting many of them now in production logs.

**Comment by g4s8** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zerocracy/farm/issues/1078#issuecomment-394115549))

@g4s8 The job [#1078](https://github.com/zerocracy/farm/issues/1078) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1532043753); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @g4s8[/z](https://www.0crat.com/u/g4s8) is on vacation; this ticket may be delayed; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@yegor256 looks like task https://github.com/zerocracy/farm/issues/875 was not valid because we don't know estimate of the job before assign it to performer but we are trying to get estimate during election (before assign to performer)

**Comment by yegor256** [comment]
@g4s8 we still have to fix this somehow and ASAP, since the entire election process is blocked now. Please, do something ASAP and then we'll discuss how to do it right.

**Comment by g4s8** [comment]
@yegor256 disabled `RnkEstimates` to fix election: #1081

**Comment by yegor256** [comment]
@g4s8 will you release?

**Comment by g4s8** [comment]
@yegor256 [done](https://github.com/zerocracy/farm/pull/1081#issuecomment-394278024), election seems to be working now

**Comment by yegor256** [comment]
@g4s8 thanks!

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
