### ISSUE TITLE
IllegalStateException: [GET https://www.0crat.com/board] failed in 4s: ValidationException: Cannot convert string "$4419...

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#1084]
https://sentry.io/zerocracy/farm/issues/570626312/

```
ValidationException: Cannot convert string "$4419.93" to double
    at net.sf.saxon.type.ValidationFailure.makeException(ValidationFailure.java:393)
    at net.sf.saxon.type.ValidationFailure.asAtomic(ValidationFailure.java:419)
    at net.sf.saxon.expr.sort.UntypedNumericComparer.quickComparison(UntypedNumericComparer.java:159)
    at net.sf.saxon.expr.sort.UntypedNumericComparer.quickCompare(UntypedNumericComparer.java:59)
    at net.sf.saxon.expr.GeneralComparison.compare(GeneralComparison.java:833)
...
(96 additional frame(s) were not displayed)

IOException: ValidationException: Cannot convert string "$4419.93" to double
    at com.zerocracy.tk.TkSoftForward$RsSoft$1.body(TkSoftForward.java:95)
...
(32 additional frame(s) were not displayed)

IllegalStateException: [GET https://www.0crat.com/board] failed in 4s: ValidationException: Cannot convert string "$4419.93" to double
    at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)
    at org.takes.facets.fallback.TkFallback.access$100(TkFallback.java:54)
    at org.takes.facets.fallback.TkFallback$2.body(TkFallback.java:202)
    at org.takes.rs.RsWrap.body(RsWrap.java:65)
    at org.takes.rs.RsPrint.printBody(RsPrint.java:161)
...
(10 additional frame(s) were not displayed)

[GET https://www.0crat.com/board] failed in 4s: ValidationException: Cannot convert string "$4419.93" to double
```

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by skapral** [comment]
Upvoted. Also saw this exception when opening a "board" page.

**Comment by g4s8** [comment]
@0crat assign @krzyk

**Comment by 0crat** [comment]
> @0crat assign @krzyk  ([here](https://github.com/zerocracy/farm/issues/1084#issuecomment-397588401))

@g4s8 The job [#1084](https://github.com/zerocracy/farm/issues/1084) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1661107041); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by krzyk** [comment]
@yegor256 please close this issue, changes have been merged to master in #1158

**Comment by krzyk** [comment]
@yegor256 BTW. After release the board works in firefox - https://www.0crat.com/board

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this job was assigned to you 7days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1084](https://github.com/zerocracy/farm/issues/1084) is now out of scope

**Comment by ypshenychka** [comment]
@skapral According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Messages in a job [always](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#4-avoid-noiseaddress-your-comments) start with a name of a user they are addressed to.

Please correct your [message](https://github.com/zerocracy/farm/issues/1084#issuecomment-397560671) by indicating an addressee in the beginning.

**Comment by skapral** [comment]
@ypshenychka fixed.

**Comment by ypshenychka** [comment]
@skapral thanks

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
