### ISSUE TITLE
IllegalStateException: [GET https://www.0crat.com/u/krzyk] failed in 727ms: net.sf.saxon.trans.XPathException: Cannot co...

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#1085]
https://sentry.io/zerocracy/farm/issues/570581292/

```
XPathException: Cannot compare xs:untypedAtomic to xs:integer
    at net.sf.saxon.expr.ValueComparison.compare(ValueComparison.java:749)
    at net.sf.saxon.expr.ValueComparison.effectiveBooleanValue(ValueComparison.java:695)
    at net.sf.saxon.expr.instruct.Choose.choose(Choose.java:902)
    at net.sf.saxon.expr.instruct.Choose.processLeavingTail(Choose.java:877)
    at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687)
...
(82 additional frame(s) were not displayed)

IOException: net.sf.saxon.trans.XPathException: Cannot compare xs:untypedAtomic to xs:integer
    at com.zerocracy.tk.TkSoftForward$RsSoft$1.body(TkSoftForward.java:95)
...
(38 additional frame(s) were not displayed)

IllegalStateException: [GET https://www.0crat.com/u/krzyk] failed in 727ms: net.sf.saxon.trans.XPathException: Cannot compare xs:untypedAtomic to xs:integer
    at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)
    at org.takes.facets.fallback.TkFallback.access$100(TkFallback.java:54)
    at org.takes.facets.fallback.TkFallback$2.head(TkFallback.java:173)
    at org.takes.rs.RsWrap.head(RsWrap.java:60)
    at org.takes.rs.RsPrint.printHead(RsPrint.java:128)
...
(10 additional frame(s) were not displayed)

[GET https://www.0crat.com/u/krzyk] failed in 727ms: net.sf.saxon.trans.XPathException: Cannot compare xs:untypedAtomic to xs:integer
```

```
net.sf.saxon.trans.XPathException: Cannot compare xs:untypedAtomic to xs:integer
    at net.sf.saxon.expr.ValueComparison.compare(ValueComparison.java:749)
    at net.sf.saxon.expr.ValueComparison.effectiveBooleanValue(ValueComparison.java:695)
    at net.sf.saxon.expr.instruct.Choose.choose(Choose.java:902)
    at net.sf.saxon.expr.instruct.Choose.processLeavingTail(Choose.java:877)
    at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687)
    at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151)
    at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337)
    at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284)
    at net.sf.saxon.expr.instruct.TemplateRule.applyLeavingTail(TemplateRule.java:347)
    at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:502)
    at net.sf.saxon.expr.instruct.ApplyTemplates.apply(ApplyTemplates.java:295)
    at net.sf.saxon.expr.instruct.ApplyTemplates.processLeavingTail(ApplyTemplates.java:252)
    at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687)
    at net.sf.saxon.expr.instruct.TemplateRule.applyLeavingTail(TemplateRule.java:347)
    at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:502)
    at net.sf.saxon.expr.instruct.ApplyTemplates.apply(ApplyTemplates.java:295)
    at net.sf.saxon.expr.instruct.ApplyTemplates.process(ApplyTemplates.java:248)
    at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337)
    at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284)
    at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687)
    at net.sf.saxon.expr.instruct.TemplateRule.applyLeavingTail(TemplateRule.java:347)
    at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:502)
    at net.sf.saxon.expr.instruct.ApplyTemplates.apply(ApplyTemplates.java:295)
    at net.sf.saxon.expr.instruct.ApplyTemplates.processLeavingTail(ApplyTemplates.java:252)
    at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687)
    at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151)
    at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337)
    at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284)
    at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151)
    at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337)
    at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284)
    at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687)
    at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151)
    at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337)
    at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284)
    at net.sf.saxon.expr.instruct.TemplateRule.applyLeavingTail(TemplateRule.java:347)
    at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:502)
    at net.sf.saxon.trans.TextOnlyCopyRuleSet.process(TextOnlyCopyRuleSet.java:66)
    at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:478)
    at net.sf.saxon.Controller.transformDocument(Controller.java:2402)
    at net.sf.saxon.Controller.transform(Controller.java:1970)
    at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:596)
    at net.sf.saxon.jaxp.TransformerImpl.transform(TransformerImpl.java:73)
    at org.takes.rs.RsXslt.transform(RsXslt.java:160)
    at org.takes.rs.RsXslt.transform(RsXslt.java:131)
    at org.takes.rs.RsXslt.access$100(RsXslt.java:89)
    at org.takes.rs.RsXslt$1.body(RsXslt.java:113)
    at org.takes.rs.RsWrap.body(RsWrap.java:65)
    at org.takes.facets.fork.RsFork$1.body(RsFork.java:74)
    at org.takes.rs.RsWrap.body(RsWrap.java:65)
    at org.takes.rs.RsWrap.body(RsWrap.java:65)
    at com.zerocracy.tk.TkSoftForward$RsSoft$1.body(TkSoftForward.java:95)
    at org.takes.rs.RsWrap.body(RsWrap.java:65)
    at org.takes.facets.forward.TkForward$Safe.load(TkForward.java:116)
    at org.takes.facets.forward.TkForward$Safe.body(TkForward.java:102)
    at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
    at org.takes.rs.RsWrap.body(RsWrap.java:65)
    at org.takes.rs.RsWrap.body(RsWrap.java:65)
    at org.takes.rs.RsGzip.make(RsGzip.java:91)
    at org.takes.rs.RsGzip.head(RsGzip.java:71)
    at org.takes.facets.fork.RsFork$1.head(RsFork.java:70)
    at org.takes.rs.RsWrap.head(RsWrap.java:60)
    at org.takes.rs.RsWithHeader$1.head(RsWithHeader.java:110)
    at org.takes.rs.RsWrap.head(RsWrap.java:60)
    at org.takes.rs.RsWithHeader$1.head(RsWithHeader.java:110)
    at org.takes.rs.RsWrap.head(RsWrap.java:60)
    at org.takes.rs.RsWithHeader$1.head(RsWithHeader.java:110)
    at org.takes.rs.RsWrap.head(RsWrap.java:60)
    at org.takes.rs.RsWithHeader$1.head(RsWithHeader.java:110)
    at org.takes.rs.RsWrap.head(RsWrap.java:60)
    at org.takes.rs.RsWithHeaders.extend(RsWithHeaders.java:98)
    at org.takes.rs.RsWithHeaders.access$000(RsWithHeaders.java:44)
    at org.takes.rs.RsWithHeaders$1.head(RsWithHeaders.java:74)
    at org.takes.rs.RsWrap.head(RsWrap.java:60)
    at org.takes.facets.fallback.TkFallback$2.head(TkFallback.java:158)
    at org.takes.rs.RsWrap.head(RsWrap.java:60)
    at org.takes.rs.RsPrint.printHead(RsPrint.java:128)
    at org.takes.rs.RsPrint.print(RsPrint.java:113)
    at org.takes.http.BkBasic.print(BkBasic.java:108)
    at org.takes.http.BkBasic.accept(BkBasic.java:84)
    at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
    at org.takes.http.BkWrap.accept(BkWrap.java:52)
    at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
    at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
java.io.IOException: net.sf.saxon.trans.XPathException: Cannot compare xs:untypedAtomic to xs:integer
    at org.takes.rs.RsXslt.transform(RsXslt.java:133)
    at org.takes.rs.RsXslt.access$100(RsXslt.java:89)
    at org.takes.rs.RsXslt$1.body(RsXslt.java:113)
    at org.takes.rs.RsWrap.body(RsWrap.java:65)
    at org.takes.facets.fork.RsFork$1.body(RsFork.java:74)
    at org.takes.rs.RsWrap.body(RsWrap.java:65)
    at org.takes.rs.RsWrap.body(RsWrap.java:65)
    at com.zerocracy.tk.TkSoftForward$RsSoft$1.body(TkSoftForward.java:95)
    at org.takes.rs.RsWrap.body(RsWrap.java:65)
    at org.takes.facets.forward.TkForward$Safe.load(TkForward.java:116)
    at org.takes.facets.forward.TkForward$Safe.body(TkForward.java:102)
    at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
    at org.takes.rs.RsWrap.body(RsWrap.java:65)
    at org.takes.rs.RsWrap.body(RsWrap.java:65)
    at org.takes.rs.RsGzip.make(RsGzip.java:91)
    at org.takes.rs.RsGzip.head(RsGzip.java:71)
    at org.takes.facets.fork.RsFork$1.head(RsFork.java:70)
    at org.takes.rs.RsWrap.head(RsWrap.java:60)
    at org.takes.rs.RsWithHeader$1.head(RsWithHeader.java:110)
    at org.takes.rs.RsWrap.head(RsWrap.java:60)
    at org.takes.rs.RsWithHeader$1.head(RsWithHeader.java:110)
    at org.takes.rs.RsWrap.head(RsWrap.java:60)
    at org.takes.rs.RsWithHeader$1.head(RsWithHeader.java:110)
    at org.takes.rs.RsWrap.head(RsWrap.java:60)
    at org.takes.rs.RsWithHeader$1.head(RsWithHeader.java:110)
    at org.takes.rs.RsWrap.head(RsWrap.java:60)
    at org.takes.rs.RsWithHeaders.extend(RsWithHeaders.java:98)
    at org.takes.rs.RsWithHeaders.access$000(RsWithHeaders.java:44)
    at org.takes.rs.RsWithHeaders$1.head(RsWithHeaders.java:74)
    at org.takes.rs.RsWrap.head(RsWrap.java:60)
    at org.takes.facets.fallback.TkFallback$2.head(TkFallback.java:158)
    at org.takes.rs.RsWrap.head(RsWrap.java:60)
    at org.takes.rs.RsPrint.printHead(RsPrint.java:128)
    at org.takes.rs.RsPrint.print(RsPrint.java:113)
    at org.takes.http.BkBasic.print(BkBasic.java:108)
    at org.takes.http.BkBasic.accept(BkBasic.java:84)
    at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
    at org.takes.http.BkWrap.accept(BkWrap.java:52)
    at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
    at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
java.lang.IllegalStateException: [GET https://www.0crat.com/u/krzyk] failed in 727ms: net.sf.saxon.trans.XPathException: Cannot compare xs:untypedAtomic to xs:integer
    at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)
    at org.takes.facets.fallback.TkFallback.access$100(TkFallback.java:54)
    at org.takes.facets.fallback.TkFallback$2.head(TkFallback.java:173)
    at org.takes.rs.RsWrap.head(RsWrap.java:60)
    at org.takes.rs.RsPrint.printHead(RsPrint.java:128)
    at org.takes.rs.RsPrint.print(RsPrint.java:113)
    at org.takes.http.BkBasic.print(BkBasic.java:108)
    at org.takes.http.BkBasic.accept(BkBasic.java:84)
    at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
    at org.takes.http.BkWrap.accept(BkWrap.java:52)
    at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
    at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@yegor256 looks like a duplicate of #1080

**Comment by yegor256** [comment]
@g4s8 right, sorry

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
