### ISSUE TITLE
IllegalStateException: [GET https://www.0crat.com/u/g4s8] failed in 3ms: Task java.util.concurrent.FutureTask@131e1fb2 r...

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#1086]
https://sentry.io/zerocracy/farm/issues/571429188/

```
RejectedExecutionException: Task java.util.concurrent.FutureTask@131e1fb2 rejected from java.util.concurrent.ThreadPoolExecutor@21384fc5[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1326579]
    at com.zerocracy.farm.sync.Terminator.submit(Terminator.java:106)
    at com.zerocracy.farm.sync.SyncProject.acq(SyncProject.java:97)
    at com.zerocracy.farm.strict.StrictProject.acq(StrictProject.java:127)
    at com.zerocracy.farm.props.PropsProject.acq(PropsProject.java:81)
    at com.zerocracy.farm.footprint.FtProject.acq(FtProject.java:67)
...
(80 additional frame(s) were not displayed)

IllegalStateException: [GET https://www.0crat.com/u/g4s8] failed in 3ms: Task java.util.concurrent.FutureTask@131e1fb2 rejected from java.util.concurrent.ThreadPoolExecutor@21384fc5[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1326579]
    at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)
    at org.takes.facets.fallback.TkFallback.access$100(TkFallback.java:54)
    at org.takes.facets.fallback.TkFallback$2.head(TkFallback.java:173)
    at org.takes.rs.RsWrap.head(RsWrap.java:60)
    at org.takes.rs.RsPrint.printHead(RsPrint.java:128)
...
(10 additional frame(s) were not displayed)

[GET https://www.0crat.com/u/g4s8] failed in 3ms: Task java.util.concurrent.FutureTask@131e1fb2 rejected from java.util.concurrent.ThreadPoolExecutor@21384fc5[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1326579]
```

```
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@131e1fb2 rejected from java.util.concurrent.ThreadPoolExecutor@21384fc5[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1326579]
    at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
    at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
    at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
    at com.zerocracy.farm.sync.Terminator.submit(Terminator.java:106)
    at com.zerocracy.farm.sync.SyncProject.acq(SyncProject.java:97)
    at com.zerocracy.farm.strict.StrictProject.acq(StrictProject.java:127)
    at com.zerocracy.farm.props.PropsProject.acq(PropsProject.java:81)
    at com.zerocracy.farm.footprint.FtProject.acq(FtProject.java:67)
    at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
    at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:62)
    at com.zerocracy.pmo.Pmo.acq(Pmo.java:58)
    at com.zerocracy.pmo.People.item(People.java:789)
    at com.zerocracy.pmo.People.bootstrap(People.java:88)
    at com.zerocracy.tk.RqUser.lambda$new$0(RqUser.java:109)
    at org.cactoos.scalar.SolidScalar.lambda$new$0(SolidScalar.java:55)
    at org.cactoos.func.StickyFunc.lambda$new$0(StickyFunc.java:72)
    at org.cactoos.func.StickyBiFunc.apply(StickyBiFunc.java:95)
    at org.cactoos.func.StickyFunc.apply(StickyFunc.java:79)
    at org.cactoos.func.SyncFunc.apply(SyncFunc.java:101)
    at org.cactoos.func.SolidFunc.apply(SolidFunc.java:66)
    at org.cactoos.scalar.SolidScalar.value(SolidScalar.java:61)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at com.zerocracy.tk.RqUser.value(RqUser.java:127)
    at com.zerocracy.tk.profile.TkProfile.lambda$act$3(TkProfile.java:72)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at com.zerocracy.tk.RsPage.lambda$make$0(RsPage.java:132)
    at org.takes.rs.xe.XeChain$2.toXembly(XeChain.java:79)
    at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
    at org.takes.rs.xe.XeChain$2.toXembly(XeChain.java:80)
    at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
    at org.takes.rs.xe.XeAppend$1.toXembly(XeAppend.java:75)
    at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
    at org.takes.rs.xe.XeChain$2.toXembly(XeChain.java:80)
    at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
    at org.takes.rs.xe.RsXembly.render(RsXembly.java:147)
    at org.takes.rs.xe.RsXembly.access$000(RsXembly.java:65)
    at org.takes.rs.xe.RsXembly$1.body(RsXembly.java:129)
    at org.takes.rs.RsWrap.body(RsWrap.java:65)
    at org.takes.rs.RsWithoutHeader$1.body(RsWithoutHeader.java:75)
    at org.takes.rs.RsWrap.body(RsWrap.java:65)
    at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
    at org.takes.rs.RsWrap.body(RsWrap.java:65)
    at org.takes.rs.RsWrap.body(RsWrap.java:65)
    at org.takes.rs.RsPrettyXml.make(RsPrettyXml.java:113)
    at org.takes.rs.RsPrettyXml.head(RsPrettyXml.java:94)
    at org.takes.facets.fork.RsFork$1.head(RsFork.java:70)
    at org.takes.rs.RsWrap.head(RsWrap.java:60)
    at org.takes.rs.RsWrap.head(RsWrap.java:60)
    at com.zerocracy.tk.TkSoftForward$RsSoft$1.head(TkSoftForward.java:87)
    at org.takes.rs.RsWrap.head(RsWrap.java:60)
    at org.takes.facets.forward.TkForward$Safe.load(TkForward.java:115)
    at org.takes.facets.forward.TkForward$Safe.body(TkForward.java:102)
    at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
    at org.takes.rs.RsWrap.body(RsWrap.java:65)
    at org.takes.rs.RsWrap.body(RsWrap.java:65)
    at org.takes.rs.RsGzip.make(RsGzip.java:91)
    at org.takes.rs.RsGzip.head(RsGzip.java:71)
    at org.takes.facets.fork.RsFork$1.head(RsFork.java:70)
    at org.takes.rs.RsWrap.head(RsWrap.java:60)
    at org.takes.rs.RsWithHeader$1.head(RsWithHeader.java:110)
    at org.takes.rs.RsWrap.head(RsWrap.java:60)
    at org.takes.rs.RsWithHeader$1.head(RsWithHeader.java:110)
    at org.takes.rs.RsWrap.head(RsWrap.java:60)
    at org.takes.rs.RsWithHeader$1.head(RsWithHeader.java:110)
    at org.takes.rs.RsWrap.head(RsWrap.java:60)
    at org.takes.rs.RsWithHeader$1.head(RsWithHeader.java:110)
    at org.takes.rs.RsWrap.head(RsWrap.java:60)
    at org.takes.rs.RsWithHeaders.extend(RsWithHeaders.java:98)
    at org.takes.rs.RsWithHeaders.access$000(RsWithHeaders.java:44)
    at org.takes.rs.RsWithHeaders$1.head(RsWithHeaders.java:74)
    at org.takes.rs.RsWrap.head(RsWrap.java:60)
    at org.takes.facets.fallback.TkFallback$2.head(TkFallback.java:158)
    at org.takes.rs.RsWrap.head(RsWrap.java:60)
    at org.takes.rs.RsPrint.printHead(RsPrint.java:128)
    at org.takes.rs.RsPrint.print(RsPrint.java:113)
    at org.takes.http.BkBasic.print(BkBasic.java:108)
    at org.takes.http.BkBasic.accept(BkBasic.java:84)
    at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
    at org.takes.http.BkWrap.accept(BkWrap.java:52)
    at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
    at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
java.lang.IllegalStateException: [GET https://www.0crat.com/u/g4s8] failed in 3ms: Task java.util.concurrent.FutureTask@131e1fb2 rejected from java.util.concurrent.ThreadPoolExecutor@21384fc5[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1326579]
    at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)
    at org.takes.facets.fallback.TkFallback.access$100(TkFallback.java:54)
    at org.takes.facets.fallback.TkFallback$2.head(TkFallback.java:173)
    at org.takes.rs.RsWrap.head(RsWrap.java:60)
    at org.takes.rs.RsPrint.printHead(RsPrint.java:128)
    at org.takes.rs.RsPrint.print(RsPrint.java:113)
    at org.takes.http.BkBasic.print(BkBasic.java:108)
    at org.takes.http.BkBasic.accept(BkBasic.java:84)
    at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
    at org.takes.http.BkWrap.accept(BkWrap.java:52)
    at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
    at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue
