### ISSUE TITLE
error on board page in firefox

### ISSUE THREAD

**Issue by krzyk** [zerocracy/farm#1087]
When I go to https://www.0crat.com/board I see:
```
java.lang.IllegalStateException: [GET https://www.0crat.com/board] failed in 4s: ValidationException: Cannot convert string "$4419.93" to double at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234) at org.takes.facets.fallback.TkFallback.access$100(TkFallback.java:54) at org.takes.facets.fallback.TkFallback$2.body(TkFallback.java:202) at org.takes.rs.RsWrap.body(RsWrap.java:65) at org.takes.rs.RsPrint.printBody(RsPrint.java:161) at org.takes.rs.RsPrint.print(RsPrint.java:114) at org.takes.http.BkBasic.print(BkBasic.java:108) at org.takes.http.BkBasic.accept(BkBasic.java:84) at org.takes.http.BkSafe$1.accept(BkSafe.java:51) at org.takes.http.BkWrap.accept(BkWrap.java:52) at org.takes.http.BkTimeable.accept(BkTimeable.java:89) at org.takes.http.BkParallel$1$1.run(BkParallel.java:89) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) Caused by: java.io.IOException: ValidationException: Cannot convert string "$4419.93" to double at org.takes.rs.RsXslt.transform(RsXslt.java:133) at org.takes.rs.RsXslt.access$100(RsXslt.java:89) at org.takes.rs.RsXslt$1.body(RsXslt.java:113) at org.takes.rs.RsWrap.body(RsWrap.java:65) at org.takes.facets.fork.RsFork$1.body(RsFork.java:74) at org.takes.rs.RsWrap.body(RsWrap.java:65) at org.takes.rs.RsWrap.body(RsWrap.java:65) at com.zerocracy.tk.TkSoftForward$RsSoft$1.body(TkSoftForward.java:95) at org.takes.rs.RsWrap.body(RsWrap.java:65) at org.takes.facets.forward.TkForward$Safe.load(TkForward.java:116) at org.takes.facets.forward.TkForward$Safe.body(TkForward.java:102) at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114) at org.takes.rs.RsWrap.body(RsWrap.java:65) at org.takes.rs.RsWrap.body(RsWrap.java:65) at org.takes.rs.RsGzip.make(RsGzip.java:91) at org.takes.rs.RsGzip.body(RsGzip.java:76) at org.takes.facets.fork.RsFork$1.body(RsFork.java:74) at org.takes.rs.RsWrap.body(RsWrap.java:65) at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114) at org.takes.rs.RsWrap.body(RsWrap.java:65) at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114) at org.takes.rs.RsWrap.body(RsWrap.java:65) at org.takes.rs.RsWithHeaders$1.body(RsWithHeaders.java:78) at org.takes.rs.RsWrap.body(RsWrap.java:65) at org.takes.facets.fallback.TkFallback$2.body(TkFallback.java:187) ... 12 more Caused by: ValidationException: Cannot convert string "$4419.93" to double at net.sf.saxon.type.ValidationFailure.makeException(ValidationFailure.java:393) at net.sf.saxon.type.ValidationFailure.asAtomic(ValidationFailure.java:419) at net.sf.saxon.expr.sort.UntypedNumericComparer.quickComparison(UntypedNumericComparer.java:159) at net.sf.saxon.expr.sort.UntypedNumericComparer.quickCompare(UntypedNumericComparer.java:59) at net.sf.saxon.expr.GeneralComparison.compare(GeneralComparison.java:833) at net.sf.saxon.expr.GeneralComparison.evaluateManyToOne(GeneralComparison.java:711) at net.sf.saxon.expr.GeneralComparison.effectiveBooleanValue(GeneralComparison.java:660) at net.sf.saxon.expr.instruct.Choose.choose(Choose.java:902) at net.sf.saxon.expr.instruct.Choose.processLeavingTail(Choose.java:877) at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687) at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151) at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337) at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284) at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687) at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151) at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337) at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284) at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687) at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151) at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337) at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284) at net.sf.saxon.expr.instruct.TemplateRule.applyLeavingTail(TemplateRule.java:347) at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:502) at net.sf.saxon.expr.instruct.ApplyTemplates.apply(ApplyTemplates.java:295) at net.sf.saxon.expr.instruct.ApplyTemplates.process(ApplyTemplates.java:248) at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337) at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284) at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687) at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151) at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337) at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284) at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687) at net.sf.saxon.expr.instruct.TemplateRule.applyLeavingTail(TemplateRule.java:347) at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:502) at net.sf.saxon.expr.instruct.ApplyTemplates$ApplyTemplatesPackage.processLeavingTail(ApplyTemplates.java:553) at net.sf.saxon.expr.instruct.ApplyTemplates.apply(ApplyTemplates.java:297) at net.sf.saxon.expr.instruct.ApplyTemplates.process(ApplyTemplates.java:248) at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337) at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284) at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687) at net.sf.saxon.expr.instruct.TemplateRule.applyLeavingTail(TemplateRule.java:347) at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:502) at net.sf.saxon.expr.instruct.ApplyTemplates.apply(ApplyTemplates.java:295) at net.sf.saxon.expr.instruct.ApplyTemplates.processLeavingTail(ApplyTemplates.java:252) at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687) at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151) at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337) at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284) at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151) at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337) at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284) at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687) at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151) at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337) at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:284) at net.sf.saxon.expr.instruct.TemplateRule.applyLeavingTail(TemplateRule.java:347) at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:502) at net.sf.saxon.trans.TextOnlyCopyRuleSet.process(TextOnlyCopyRuleSet.java:66) at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:478) at net.sf.saxon.Controller.transformDocument(Controller.java:2402) at net.sf.saxon.Controller.transform(Controller.java:1970) at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:596) at net.sf.saxon.jaxp.TransformerImpl.transform(TransformerImpl.java:73) at org.takes.rs.RsXslt.transform(RsXslt.java:160) at org.takes.rs.RsXslt.transform(RsXslt.java:131) ... 36 more 
```

Please make it work in firefox.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue
