### ISSUE TITLE
Error while submitting the Join form

### ISSUE THREAD

**Issue by vizotov** [zerocracy/farm#1149]
I am logged into 0crat.com and see the Policy and the Board.
When i am trying to submit the Join form, then receive error:
```
Internal application error
0.22.3, ${buildNumber}

Please, report it here. We will do our best to fix it as soon as possible. We're very sorry.

java.lang.IllegalStateException: [POST https://www.0crat.com/join-post] failed in 595ms: Person @vizotov[/z](https://www.0crat.com/u/vizotov) doesn't exist
	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:115)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkSslOnly.act(TkSslOnly.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.http.BkBasic.print(BkBasic.java:108)
	at org.takes.http.BkBasic.accept(BkBasic.java:84)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Person @vizotov[/z](https://www.0crat.com/u/vizotov) doesn't exist
	at com.zerocracy.pmo.People.appliedTime(People.java:762)
	at com.zerocracy.tk.TkJoin.act(TkJoin.java:89)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:210)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at com.zerocracy.tk.TkSoftForward.lambda$new$0(TkSoftForward.java:50)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.forward.TkForward.act(TkForward.java:68)
	at org.takes.facets.fork.FkFixed$1.route(FkFixed.java:56)
	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:109)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:89)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:108)
	at org.takes.tk.TkGzip$1.act(TkGzip.java:58)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:73)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:86)
	... 14 more
HTTP/1.1 500 Internal Error Content-Length: 1060 Content-Type: text/plain java.io.IOException: Invalid HTTP method: X-Takes-LocalAddress: at org.takes.rq.RqMethod$Base.method(RqMethod.java:128) at org.takes.facets.fallback.TkFallback.error(TkFallback.java:236) at org.takes.facets.fallback.TkFallback.route(TkFallback.java:92) at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54) at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66) at org.takes.tk.TkWrap.act(TkWrap.java:61) at org.takes.tk.TkSslOnly.act(TkSslOnly.java:71) at org.takes.tk.TkWrap.act(TkWrap.java:61) at org.takes.http.BkBasic.print(BkBasic.java:108) at org.takes.http.BkBasic.accept(BkBasic.java:84) at org.takes.http.BkSafe$1.accept(BkSafe.java:51) at org.takes.http.BkWrap.accept(BkWrap.java:52) at org.takes.http.BkTimeable.accept(BkTimeable.java:89) at org.takes.http.BkParallel$1$1.run(BkParallel.java:89) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)
```

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@vizotov[/z](https://www.0crat.com/u/vizotov) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by summittjack** [comment]
Ah I seen what your doing.Thats clever. Well played.

**Comment by g4s8** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/zerocracy/farm/issues/1149#issuecomment-397216091))

@g4s8 Job [#1149](https://github.com/zerocracy/farm/issues/1149) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/zerocracy/farm/issues/1149#issuecomment-397216091))

@g4s8 Thanks for your contribution, @vizotov[/z](https://www.0crat.com/u/vizotov)! If you would be a member of [the project](https://www.0crat.com/p/C3NDPUA8L), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by g4s8** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zerocracy/farm/issues/1149#issuecomment-397414679))

@g4s8 The job [#1149](https://github.com/zerocracy/farm/issues/1149) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1651966071); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.22.4`

**Comment by g4s8** [comment]
@vizotov should be fixed, please try now

**Comment by g4s8** [comment]
@rultor release, tag=`0.22.5`

**Comment by g4s8** [comment]
@vizotov fixed this error in 602d06d6be53bc3fd523f1d4d09a238d2eb31a8d, please try again

**Comment by vizotov** [comment]
@g4s8 now it works (from interface side): "The request will be sent to all high-ranked users".
Thanks.

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1149](https://github.com/zerocracy/farm/issues/1149) is now out of scope

**Comment by fatahn** [comment]
I got this same error after signing in with github and being redirected to 
```
Internal application error
0.34.4, ${buildNumber}

Please, report it here. We will do our best to fix it as soon as possible. We're very sorry.

java.lang.IllegalStateException: [GET https://www.0crat.com/join-post] failed in 793ms: [400] form param "telegram" is mandatory
	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:92)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkSslOnly.act(TkSslOnly.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.http.BkBasic.print(BkBasic.java:108)
	at org.takes.http.BkBasic.accept(BkBasic.java:84)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.takes.HttpException: [400] form param "telegram" is mandatory
	at org.takes.rq.form.RqFormSmart.single(RqFormSmart.java:101)
	at com.zerocracy.tk.TkJoinPost.act(TkJoinPost.java:104)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:210)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at com.zerocracy.tk.TkSoftForward.lambda$new$0(TkSoftForward.java:48)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.forward.TkForward.act(TkForward.java:68)
	at org.takes.facets.fork.FkFixed$1.route(FkFixed.java:56)
	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:109)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:89)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:108)
	at org.takes.tk.TkGzip$1.act(TkGzip.java:58)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:73)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:86)
	... 14 more
```
