### ISSUE TITLE
When doing invite exception is thrown

### ISSUE THREAD

**Issue by krzyk** [zerocracy/farm#1166]
Right now I tried to do an invite in telegram and got following exception:
```
There is an unrecoverable failure on my side. Please, submit it here (https://github.com/zerocracy/farm/issues):

PID: 4@fdc50a07-ed94-43df-8504-9aa2af4425b2, thread: AsyncFlush-8
org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl[252] java.lang.ClassCastException: javax.json.JsonValueImpl cannot be cast to javax.json.JsonString


0.22.5 (https://github.com/zerocracy/farm): CID: 1690785068 (https://www.0crat.com/PMO/1690785068), Type: "Invite a friend", Author: "krzyk"
```
Please investigate and make sure it doesn't happen again.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@krzyk more details in [Sentry](https://sentry.io/zerocracy/farm/issues/583496199/):
```
java.lang.ClassCastException: javax.json.JsonValueImpl cannot be cast to javax.json.JsonString
    at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(JsonObjectBuilderImpl.java:252)
    at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:257)
    at javax.json.JsonObject$getString.call
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
    at com.zerocracy.stk.pmo.profile.invite_friend.exec(invite_friend.groovy:68)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:822)
    at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:46)
    at groovy.lang.Script.invokeMethod(Script.java:80)
    at com.zerocracy.farm.reactive.StkRuntime.process(StkRuntime.java:65)
    at com.zerocracy.farm.StkSafe.process(StkSafe.java:81)
    at com.zerocracy.farm.reactive.StkSmart.process(StkSmart.java:66)
    at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:82)
    at com.zerocracy.farm.reactive.Brigade.lambda$apply$0(Brigade.java:64)
    at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
    at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
    at org.cactoos.iterator.Filtered.hasNext(Filtered.java:90)
    at org.cactoos.iterator.LengthOf.lambda$new$0(LengthOf.java:52)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
    at org.cactoos.scalar.NumberEnvelope.doubleValue(NumberEnvelope.java:113)
    at org.cactoos.iterable.LengthOf.lambda$new$0(LengthOf.java:51)
    at org.cactoos.scalar.NumberEnvelope.lambda$new$1(NumberEnvelope.java:73)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
    at org.cactoos.scalar.NumberEnvelope.intValue(NumberEnvelope.java:98)
    at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:67)
    at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:37)
    at org.cactoos.func.IoCheckedBiFunc.lambda$apply$0(IoCheckedBiFunc.java:60)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:61)
    at com.zerocracy.farm.reactive.DefaultFlush.process(DefaultFlush.java:98)
    at com.zerocracy.farm.reactive.DefaultFlush.lambda$exec$0(DefaultFlush.java:67)
    at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
    at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
    at org.cactoos.func.IoCheckedFunc.lambda$apply$0(IoCheckedFunc.java:59)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:59)
    at org.cactoos.func.IoCheckedProc.exec(IoCheckedProc.java:57)
    at com.zerocracy.pm.Claims.take(Claims.java:150)
    at com.zerocracy.farm.reactive.DefaultFlush.exec(DefaultFlush.java:66)
    at com.zerocracy.farm.reactive.DefaultFlush.exec(DefaultFlush.java:44)
    at com.zerocracy.farm.reactive.AsyncFlush.lambda$exec$2(AsyncFlush.java:118)
    at com.jcabi.log.VerboseCallable.call(VerboseCallable.java:173)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:221)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by 0crat** [comment]
Job [#1166](https://github.com/zerocracy/farm/issues/1166) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by g4s8** [comment]
@0crat assign @carlosmiranda

**Comment by 0crat** [comment]
> @0crat assign @carlosmiranda  ([here](https://github.com/zerocracy/farm/issues/1166#issuecomment-402130403))

@g4s8 The job [#1166](https://github.com/zerocracy/farm/issues/1166) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1841205343); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by carlosmiranda** [comment]
@krzyk see PR #1343.

**Comment by carlosmiranda** [comment]
@0crat wait for merge of #1343.

**Comment by 0crat** [comment]
> @0crat wait for merge of #1343. ([here](https://github.com/zerocracy/farm/issues/1166#issuecomment-402627370))

@carlosmiranda The impediment for [#1166](https://github.com/zerocracy/farm/issues/1166) was registered successfully by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by carlosmiranda** [comment]
@krzyk #1343 merged, may we close this now?

**Comment by krzyk** [comment]
@carlosmiranda thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1166](https://github.com/zerocracy/farm/issues/1166) is now out of scope

**Comment by carlosmiranda** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/1166#issuecomment-403708992))

@carlosmiranda This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1166](https://github.com/zerocracy/farm/issues/1166) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 8hr
  * @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%231166%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +38 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
