### ISSUE TITLE
FootprintTest.java:73-77: This test is not stable...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1167]
The puzzle `1050-8012ef0f` from #1050 has to be resolved:

https://github.com/zerocracy/farm/blob/88bb4c8fc41b7c6c57228c9e1ece68395df8613d/src/test/java/com/zerocracy/pm/FootprintTest.java#L73-L77

The puzzle was created by rultor on 18-Jun-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1167](https://github.com/zerocracy/farm/issues/1167) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1167](https://github.com/zerocracy/farm/issues/1167) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1851118604); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by krzyk** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/1167#issuecomment-403507032))

@krzyk The user @krzyk[/z](https://www.0crat.com/u/krzyk) resigned from [#1167](https://github.com/zerocracy/farm/issues/1167), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
The job [#1167](https://github.com/zerocracy/farm/issues/1167) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2010935794); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by carlosmiranda** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/1167#issuecomment-407723933))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#1167](https://github.com/zerocracy/farm/issues/1167), please stop working. Reason for job resignation: Order was cancelled

**Comment by rgevaerd** [comment]
@krzyk do you have a stack trace or a travis build link of the fail of this test?

**Comment by krzyk** [comment]
@rgevaerd sorry I don't have it, it was quite some time ago

**Comment by rgevaerd** [comment]
@g4s8 Since the there has passed quite some time since the error occurred, there is no log or detail of it available, and I cannot reproduce it, I was thinking about resolving this issue by just reactivating the test (removing ignore) and deleting the puzzle. In worst scenario, if it happens again, at least a new issue with more information can be opened. Do you think this resolution is valid? Or is it better that I just refuse it and let the next assignee to try to reproduce it?

**Comment by 0crat** [comment]
@rgevaerd[/z](https://www.0crat.com/u/rgevaerd) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by rgevaerd** [comment]
@0crat waiting for answer of https://github.com/zerocracy/farm/issues/1167#issuecomment-409787582

**Comment by 0crat** [comment]
> @0crat waiting for answer of https://github.com/zerocracy/farm/issues/1167#issuecomment-409787582 ([here](https://github.com/zerocracy/farm/issues/1167#issuecomment-410119579))

@rgevaerd The impediment for [#1167](https://github.com/zerocracy/farm/issues/1167) was registered successfully by @rgevaerd[/z](https://www.0crat.com/u/rgevaerd)

**Comment by g4s8** [comment]
@rgevaerd you can try to unignore this test and to run few times until it failed:
```sh
for i in `seq 100`; do mvn -Dtest="com.zerocracy.pm.FootprintTest#addsInThreads" test; done
```

**Comment by rgevaerd** [comment]
@g4s8 I unignored the test and executed the following (changed mvn target so it will not fail on code coverage check):

```
mvn clean test-compile
for i in `seq 100`; do mvn -Dtest="com.zerocracy.pm.FootprintTest#addsInThreads" surefire:test; done > out.txt 2> err.txt
```

All 100 tests executions passed successfully.
Should I assume the test passes and delete the puzzle?

**Comment by krzyk** [comment]
@rgevaerd I would do a `200` just to be more sure (it all depends on the hardware and then there is rultor :)

**Comment by rgevaerd** [comment]
@krzyk I executed 500 times, it only failed once. Here is the output of the failed execution:
```
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------------< com.zerocracy:farm >-------------------------
[INFO] Building farm 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The artifact org.hibernate:hibernate-validator:jar:6.0.2.Final has been relocated to org.hibernate.validator:hibernate-validator:jar:6.0.2.Final
[INFO] 
[INFO] --- maven-surefire-plugin:2.19.1:test (default-cli) @ farm ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.zerocracy.pm.FootprintTest
swallowed runtime exception: java.lang.ArrayIndexOutOfBoundsException: 8
	at java.util.ArrayList.add(ArrayList.java:459)
	at net.sf.saxon.functions.FunctionLibraryList.addFunctionLibrary(FunctionLibraryList.java:44)
	at net.sf.saxon.Configuration.getBuiltInExtensionLibraryList(Configuration.java:1388)
	at net.sf.saxon.sxpath.AbstractStaticContext.setDefaultFunctionLibrary(AbstractStaticContext.java:127)
	at net.sf.saxon.xpath.JAXPXPathStaticContext.<init>(JAXPXPathStaticContext.java:56)
	at net.sf.saxon.xpath.XPathEvaluator.<init>(XPathEvaluator.java:71)
	at net.sf.saxon.xpath.XPathFactoryImpl.newXPath(XPathFactoryImpl.java:203)
	at org.xembly.XpathDirective.traditional(XpathDirective.java:138)
	at org.xembly.XpathDirective.exec(XpathDirective.java:98)
	at org.xembly.Xembler.apply(Xembler.java:155)
	at org.xembly.Xembler.dom(Xembler.java:210)
	at org.xembly.Xembler.xml(Xembler.java:256)
	at org.xembly.Xembler.xmlQuietly(Xembler.java:221)
	at com.zerocracy.claims.ClaimOut.postTo(ClaimOut.java:127)
	at com.zerocracy.pm.FootprintTest.lambda$addsInThreads$0(FootprintTest.java:88)
	at com.zerocracy.RunsInThreads.lambda$matchesSafely$0(RunsInThreads.java:90)
	at com.jcabi.log.VerboseCallable.call(VerboseCallable.java:173)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:221)
	at java.lang.Thread.run(Thread.java:745)

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.785 sec <<< FAILURE! - in com.zerocracy.pm.FootprintTest
addsInThreads(com.zerocracy.pm.FootprintTest)  Time elapsed: 0.785 sec  <<< ERROR!
java.lang.NullPointerException
	at org.cactoos.scalar.And.value(And.java:167)
	at org.cactoos.scalar.And.value(And.java:60)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at com.zerocracy.RunsInThreads.matchesSafely(RunsInThreads.java:107)
	at com.zerocracy.RunsInThreads.matchesSafely(RunsInThreads.java:43)
	at org.hamcrest.TypeSafeMatcher.matches(TypeSafeMatcher.java:65)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:12)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at com.zerocracy.pm.FootprintTest.addsInThreads(FootprintTest.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:393)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


Results :

Tests in error: 
  FootprintTest.addsInThreads:82 » NullPointer

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.325 s
[INFO] Finished at: 2018-08-04T20:05:58-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-cli) on project farm: There are test failures.
```
I will take a look into it.

**Comment by rgevaerd** [comment]
@krzyk @g4s8  I believe it is a bug in Xembly. I reported https://github.com/yegor256/xembly/issues/82.
Should I try to hack Xembly in farm to workaround the bug (if no SecurityManager is used I may be able to do it through reflection, but is there some bootstrap always executed to place this hack?) or should we just wait for Xembly fix?

**Comment by krzyk** [comment]
@rgevaerd I don't think we should hack it, but I also don't what to do else here except `waiting for` the xemlby bug fix

**Comment by rgevaerd** [comment]
@krzyk yeah, Ideally we shouldn't hack it... But this seems a very serious bug... That although rare, it may cause error on most xembly operations, so it may cause problems at a lot of farm project functionalities. So I don't know if it ok to just wait.
I will wait until it is fixed or someone says otherwise.

**Comment by rgevaerd** [comment]
@0crat waiting for xembly fix at https://github.com/yegor256/xembly/issues/82 that causes this bug on farm.

**Comment by 0crat** [comment]
> @0crat waiting for xembly fix at https://github.com/yegor256/xembly/issues/82 that causes this bu... ([here](https://github.com/zerocracy/farm/issues/1167#issuecomment-410526458))

@rgevaerd Job [#1167](https://github.com/zerocracy/farm/issues/1167) is already on hold

**Comment by 0pdd** [comment]
The puzzle `1050-8012ef0f` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @rgevaerd[/z](https://www.0crat.com/u/rgevaerd), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1167](https://github.com/zerocracy/farm/issues/1167) is now out of scope

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
