### ISSUE TITLE
Can't acquire any file in project

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1168]
I can't open project (`CAWJH9K0X`) page in Zerocracy because of 500 error, also `@0crat` respond with exception to any GitHub comment,
Sentry is full of messages like this one:
```
EXCEPTION(most recent call first)
java.lang.IllegalStateException: Failed to acquire "roles.xml" in "CAWJH9K0X" in 1min: b2c6548869f9/12hr/0/2/true/false by BkParallel-5
    at com.zerocracy.farm.sync.SyncProject.acq(SyncProject.java:77)
    at com.zerocracy.farm.strict.StrictProject.acq(StrictProject.java:129)
    at com.zerocracy.farm.props.PropsProject.acq(PropsProject.java:81)
    at com.zerocracy.farm.footprint.FtProject.acq(FtProject.java:67)
    at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
    at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:62)
    at com.zerocracy.tk.project.RqAnonProject.acq(RqAnonProject.java:80)
    at com.zerocracy.pm.staff.Roles.item(Roles.java:323)
    at com.zerocracy.pm.staff.Roles.bootstrap(Roles.java:69)
    at com.zerocracy.tk.project.RqProject.lambda$new$0(RqProject.java:66)
    at org.cactoos.scalar.SolidScalar.lambda$new$0(SolidScalar.java:55)
    at org.cactoos.func.StickyFunc.lambda$new$0(StickyFunc.java:72)
    at org.cactoos.func.StickyBiFunc.apply(StickyBiFunc.java:95)
    at org.cactoos.func.StickyFunc.apply(StickyFunc.java:79)
    at org.cactoos.func.SyncFunc.apply(SyncFunc.java:101)
    at org.cactoos.func.SolidFunc.apply(SolidFunc.java:66)
    at org.cactoos.scalar.SolidScalar.value(SolidScalar.java:61)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at com.zerocracy.tk.project.RqProject.acq(RqProject.java:118)
    at com.zerocracy.tk.project.TkXml.act(TkXml.java:60)
    at org.takes.facets.fork.FkRegex.route(FkRegex.java:210)
    at org.takes.facets.fork.FkChain.route(FkChain.java:75)
    at org.takes.facets.fork.TkFork.act(TkFork.java:100)
    at com.zerocracy.tk.TkSoftForward.lambda$new$0(TkSoftForward.java:50)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.facets.forward.TkForward.act(TkForward.java:68)
    at org.takes.facets.fork.FkFixed$1.route(FkFixed.java:56)
    at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
    at org.takes.facets.fork.FkChain.route(FkChain.java:75)
    at org.takes.facets.fork.TkFork.act(TkFork.java:100)
    at org.takes.facets.auth.TkAuth.act(TkAuth.java:109)
    at org.takes.facets.auth.TkAuth.act(TkAuth.java:89)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.facets.flash.TkFlash.act(TkFlash.java:108)
    at org.takes.tk.TkGzip$1.act(TkGzip.java:58)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkVersioned$1.act(TkVersioned.java:73)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.facets.fallback.TkFallback.route(TkFallback.java:86)
    at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
    at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkSslOnly.act(TkSslOnly.java:71)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.http.BkBasic.print(BkBasic.java:108)
    at org.takes.http.BkBasic.accept(BkBasic.java:84)
    at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
    at org.takes.http.BkWrap.accept(BkWrap.java:52)
    at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
    at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```
It seems that `lock` in `SyncProject` was not unlocked one time, and now any request to `SyncProject.acuire` throws an exception.

**Comment by 0crat** [comment]
Job [#1168](https://github.com/zerocracy/farm/issues/1168) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
Same here: #1194 `PMO` was inaccessible about 1 hour

**Comment by g4s8** [comment]
@0crat assign @krzyk

**Comment by g4s8** [comment]
@0crat boost 6x

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@0418894d-407e-416a-a17d-15ba3ae5dacd, thread: pool-7-thread-1
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 1min: 199db121b900/1min/0/4/true/false by QuartzScheduler_Worker-6
```

[0.22.9](https://github.com/zerocracy/farm): Issue: zerocracy/farm#1168, Comment: 398738020

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@0418894d-407e-416a-a17d-15ba3ae5dacd, thread: pool-7-thread-1
com.zerocracy.radars.github.ReSafe[82] java.io.IOException: java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 1min: 199db121b900/1min/0/4/true/false by QuartzScheduler_Worker-6
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 1min: 199db121b900/1min/0/4/true/false by QuartzScheduler_Worker-6
```

[0.22.9](https://github.com/zerocracy/farm): Issue: zerocracy/farm#1168, Action: `created`

**Comment by g4s8** [comment]
@krzyk please, try to fix this bug first, it's very critical. Looks like `SyncFarm` may not unlock item on high-load and all next attempts to acquire same item can fail with error: `java.lang.IllegalStateException: Failed to acquire`

**Comment by g4s8** [comment]
@0crat assign @krzyk

**Comment by g4s8** [comment]
@0crat boost 6x

**Comment by 0crat** [comment]
> @0crat assign @krzyk  ([here](https://github.com/zerocracy/farm/issues/1168#issuecomment-398744827))

@g4s8 The job [#1168](https://github.com/zerocracy/farm/issues/1168) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1711320028); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#1196](https://github.com/zerocracy/farm/issues/1196) is still not solved.

**Comment by g4s8** [comment]
@rultor release, tag=`0.22.11`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@6b5bb75a-1f3d-4df6-874b-c80cf409a2f7, thread: pool-34-thread-1
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 1min: 99f8085adfb7/9min/0/1/true/false by QuartzScheduler_Worker-9
```

[0.22.10](https://github.com/zerocracy/farm): Issue: zerocracy/farm#1168, Comment: 398745032

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@6b5bb75a-1f3d-4df6-874b-c80cf409a2f7, thread: pool-34-thread-1
com.zerocracy.radars.github.ReSafe[82] java.io.IOException: java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 1min: 99f8085adfb7/9min/0/1/true/false by QuartzScheduler_Worker-9
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 1min: 99f8085adfb7/9min/0/1/true/false by QuartzScheduler_Worker-9
```

[0.22.10](https://github.com/zerocracy/farm): Issue: zerocracy/farm#1168, Action: `created`

**Comment by g4s8** [comment]
@rultor release, tag=`0.22.13`

**Comment by g4s8** [comment]
@rultor release, tag=`0.22.14`

**Comment by g4s8** [comment]
@krzyk this exception is going front "Can't acquire ..." errors:
```
java.lang.IllegalMonitorStateException: null
    at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:151)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1261)
    at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:457)
    at com.zerocracy.farm.SmartLock.unlock(SmartLock.java:131)
    at com.zerocracy.farm.sync.Terminator.lambda$killer$1(Terminator.java:155)
    at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
    at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
    at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
    at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
    at org.cactoos.func.RunnableOf.run(RunnableOf.java:89)
    at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:190)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:221)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by g4s8** [comment]
@rultor release, tag=`0.22.15`

**Comment by g4s8** [comment]
@rultor release, tag=`0.22.15`

**Comment by g4s8** [comment]
@rultor release, tag=`0.22.16`

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@699dad38-11e0-4927-b0e8-65c95cb08d43, thread: pool-12-thread-1
com.zerocracy.farm.sync.SyncProject[70] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 2min: 266bf5224b6f/24s/0/5/true/false by AsyncFlush-2
```

[0.22.16](https://github.com/zerocracy/farm): Issue: zerocracy/farm#1168, Comment: 398843286

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@699dad38-11e0-4927-b0e8-65c95cb08d43, thread: pool-12-thread-1
com.zerocracy.radars.github.ReSafe[82] java.io.IOException: java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 2min: 266bf5224b6f/24s/0/5/true/false by AsyncFlush-2
com.zerocracy.farm.sync.SyncProject[70] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 2min: 266bf5224b6f/24s/0/5/true/false by AsyncFlush-2
```

[0.22.16](https://github.com/zerocracy/farm): Issue: zerocracy/farm#1168, Action: `created`

**Comment by g4s8** [comment]
@rultor release, tag=`0.22.17`

**Comment by g4s8** [comment]
@rultor release, tag=`0.22.18`

**Comment by 0pdd** [comment]
@g4s8 the only puzzle [#1196](https://github.com/zerocracy/farm/issues/1196) is solved here.

**Comment by g4s8** [comment]
@rultor release, tag=`0.22.19`

**Comment by g4s8** [comment]
@rultor release, tag=0.22.20

**Comment by g4s8** [comment]
@rultor release, tag=`0.22.20`

**Comment by g4s8** [comment]
@carlosmiranda there is some bug in `SyncFarm` I tried to fix it but without success. Can you have a look here? I can boost this bug 6x and assign to you when 0crat starts to work.

**Comment by g4s8** [comment]
@rultor release, tag=`0.22.21`

**Comment by g4s8** [comment]
@rultor release, tag=`0.22.21`

**Comment by g4s8** [comment]
@rultor release, tag=`0.22.21`

**Comment by g4s8** [comment]
@rultor release, tag=`0.22.21`

**Comment by g4s8** [comment]
Anyway if somebody started to work on this issue please add a comment first

**Comment by krzyk** [comment]
@g4s8 I started to look at it, sorry I wasn't available yesterday afternoon.
Do you have some clues besides the two stack traces above (`java.lang.IllegalMonitorStateException: null` from terminator and the `java.lang.IllegalStateException: Failed to acquire "roles.xml" ...`)?

**Comment by g4s8** [comment]
@krzyk thanks! Usually there are 3 exception types in logs, one by one: first `OutOfMemoryError` with random stacktrace, then `IllegalMonitorStateException` in terminator and then a lot of `IllegalStateException Failed to acquire some file`. The biggest part of `IllegalStateException` came from `/badge` and `/contrib-badge` urls, this is why I've diabled them.

What about fixing in production, I can merge your requests for this issue without CR and deploy releases this rultor.

**Comment by g4s8** [comment]
@rultor release, tag=0.22.22

**Comment by g4s8** [comment]
@rultor release, tag=`0.22.22`

**Comment by krzyk** [comment]
@g4s8 OK, so OOM + the recent changes might suggest that it has something to do with my firefox fixes + few new people joining.

I would first try to disable firefox specific handling and will see.

**Comment by g4s8** [comment]
@rultor release, tag=`0.22.22`

**Comment by g4s8** [comment]
@krzyk yes, usually it's working for few minutes

**Comment by g4s8** [comment]
@rultor release, tag=`0.22.23`

**Comment by g4s8** [comment]
@krzyk I added some logs in `0.22.22` and now I can see that this exception was first in application:
```
java.lang.IllegalStateException: Here!
    at com.zerocracy.farm.sync.Terminator.killer(Terminator.java:127)
    at com.zerocracy.farm.sync.Terminator.submit(Terminator.java:109)
    at com.zerocracy.farm.sync.SyncProject.acq(SyncProject.java:97)
    at com.zerocracy.farm.strict.StrictProject.acq(StrictProject.java:129)
    at com.zerocracy.farm.props.PropsProject.acq(PropsProject.java:81)
    at com.zerocracy.farm.footprint.FtProject.acq(FtProject.java:67)
    at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
    at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:62)
    at com.zerocracy.pm.Claims.item(Claims.java:211)
    at com.zerocracy.pm.Claims.bootstrap(Claims.java:70)
    at com.zerocracy.entry.Ping.post(Ping.java:80)
    at com.zerocracy.entry.Ping.post(Ping.java:66)
    at com.zerocracy.entry.Ping.execute(Ping.java:53)
    at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
java.lang.Exception: Thread 27/QuartzScheduler_Worker-3 interrupted because of too long hold of "claims.xml" in PMO (over 240000 msec), a3e35cd2a8c4/4min/0/5/true/false by QuartzScheduler_Worker-3
    at com.zerocracy.farm.sync.Terminator.lambda$killer$1(Terminator.java:140)
    at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
    at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
    at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
    at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
    at org.cactoos.func.RunnableOf.run(RunnableOf.java:89)
    at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:190)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:221)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by krzyk** [comment]
@g4s8 Hmm, so the app starts, receives almost no traffic (rehttp lists just few requests) and it dies after 5 mins.

So what triggers it? Either github, slack, web traffic (all of them are basically web traffic) or some scheduler (that works on our current data)?

Do you know the amount of http traffic to it?



BTW. Strange that there are 100 Grizzly threads, 68 out of those in WAITING. I wonder how it looked when it was working.

**Comment by krzyk** [comment]
@g4s8Do you have some GC logs from the whole start->live->dead process?

**Comment by g4s8** [comment]
@krzyk no, I can't see http traffic and GC logs. But looks like about 35 projects are trying to send something in first 5 minutes:
```
RvFarm:

Alive (75): ABCRDFG11:2, C3FFK3YAY:0, C3NDPUA8L:3, C3RFVLU72:1, C3RP1J1CH:1, C3RUBL5H9:2, C3SAYRPH9:2, C3T46CUJJ:2, C63314D6Z:2, C6LALQH1B:2, C6MATTB7E:3, C7BNDNSNR:3, C7ECPCSMC:2, C7FCB1EQN:0, C7JGJ00DP:2, C7NJ258GL:2, C8MD9MCEP:2, C8MKQ1R37:3, C8Z3EAH18:2, C9LFHR8NM:3, C9QEPABRP:3, C9R53K5JA:2, C9V3GAG9H:3, C9V6HBZQS:0, CA2075Q49:3, CAWJH9K0X:2, CAZPZR9FS:2, CAZUFVA8H:2, CAZUREFND:3, CB08FTCNQ:3, CB28FH2NR:3, G6LPQQV2P:3, G8QQED6QN:3, G930TRU1E:3, PMO:1.

Locks: ABCRDFG11:free, C3FFK3YAY:free, C3RFVLU72:free, C3RP1J1CH:free, C63314D6Z:free, C6LALQH1B:free, C6MATTB7E:free, C7FCB1EQN:free, C8MKQ1R37:91bd4e6aba69/24s/0/1/true/false by AsyncFlush-2, C9QEPABRP:788ac5b961c8/53s/0/1/true/false by AsyncFlush-6, C9R53K5JA:free, C9V6HBZQS:free, CA2075Q49:d48eaff43d18/20s/0/1/true/false by AsyncFlush-8, CAZUFVA8H:free, G930TRU1E:dcd79b935b0c/49s/0/1/true/false by AsyncFlush-7.
```

**Comment by g4s8** [comment]
@rultor release, tag=`0.22.24`

**Comment by g4s8** [comment]
@0crat hello

**Comment by 0crat** [comment]
> @0crat hello ([here](https://github.com/zerocracy/farm/issues/1168#issuecomment-399032651))

@g4s8 Hey, what's up, how is it going?

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/1168#issuecomment-399032776))

@g4s8 This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1168](https://github.com/zerocracy/farm/issues/1168) is [in scope](http://www.zerocracy.com/policy.html#14) for 3days
  * The role is `DEV`
  * The job is assigned to @krzyk[/z](https://www.0crat.com/u/krzyk) for [20hr](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @krzyk[/z](https://www.0crat.com/u/krzyk) will get 50% of their hourly rate for this job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @g4s8[/z](https://www.0crat.com/u/g4s8): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%231168%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by g4s8** [comment]
@krzyk I've just disabled all pings, looks like it's much faster now

**Comment by g4s8** [comment]
@krzyk application is running without errors more than one hour. I think we can submit todo and close this one. It seems that `SyncFarm` can't handle too much pings at the same time (75 pings every minute). Can you take new pings task and fix it ASAP if I boost it?

**Comment by krzyk** [comment]
@g4s8 I'll revert the changes for disabling firefox - https://github.com/zerocracy/farm/pull/1199

**Comment by g4s8** [comment]
@krzyk pings disabling just deferred the problem, without it application can work about 1.5 hour, when with bings 5-10 minutes

**Comment by g4s8** [comment]
@rultor release, tag=`0.22.25`

**Comment by g4s8** [comment]
@0crat hello

**Comment by 0crat** [comment]
> @0crat hello ([here](https://github.com/zerocracy/farm/issues/1168#issuecomment-399072310))

@g4s8 Hey, what's up, how is it going?

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#1201](https://github.com/zerocracy/farm/issues/1201) is still not solved; solved: [#1196](https://github.com/zerocracy/farm/issues/1196).

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/1168#issuecomment-399099206))

@g4s8 This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1168](https://github.com/zerocracy/farm/issues/1168) is [in scope](http://www.zerocracy.com/policy.html#14) for 3days
  * The role is `DEV`
  * The job is assigned to @krzyk[/z](https://www.0crat.com/u/krzyk) for [24hr](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @krzyk[/z](https://www.0crat.com/u/krzyk) will get 50% of their hourly rate for this job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @g4s8[/z](https://www.0crat.com/u/g4s8): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%231168%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by g4s8** [comment]
It will be fixed in #1200 #1203 #1202 #360

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1168](https://github.com/zerocracy/farm/issues/1168) is now out of scope

**Comment by ypshenychka** [comment]
@g4s8 According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Messages in a job [always](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#4-avoid-noiseaddress-your-comments) start with a name of a user they are addressed to.

Please correct your [message](https://github.com/zerocracy/farm/issues/1168#issuecomment-398932845) by indicating an addressee in the beginning.

**Comment by g4s8** [comment]
@ypshenychka done

**Comment by ypshenychka** [comment]
@g4s8 Did you correct this [message](https://github.com/zerocracy/farm/issues/1168#issuecomment-398932845)? Looks like there's still no addressee.

**Comment by g4s8** [comment]
@rultor release, tag=`0.22.29`

**Comment by g4s8** [comment]
@ypshenychka sorry, missed this one, updated now

**Comment by g4s8** [comment]
@rultor release, tag=0.22.29

**Comment by g4s8** [comment]
@rultor release, tag=`0.22.29`

**Comment by 0pdd** [comment]
@g4s8 all 2 puzzles are solved here: [#1196](https://github.com/zerocracy/farm/issues/1196), [#1201](https://github.com/zerocracy/farm/issues/1201).

**Comment by ypshenychka** [comment]
@g4s8 Thanks!

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
