### ISSUE TITLE
Recharge should not fail payment to performer

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1188]
If order closed and `recharge_on_deficit` script fails ("Make payment" claim), the performer won't receive a payment. It's not correct because project has some "locked" funds in `estimates.xml` to be able to pay for each job in scope. E.g. project may have $80 locked funds, but fails to pay $10 for a job.

**Comment by 0crat** [comment]
Job [#1188](https://github.com/zerocracy/farm/issues/1188) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1188](https://github.com/zerocracy/farm/issues/1188) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2030653797); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by krzyk** [comment]
@g4s8 hmm, one stakeholder throwing exception can block execution of another stakeholder?
I tried to recreate it in test, but make_payment.groovy is executed always before the recharge one so it always works.

**Comment by g4s8** [comment]
@krzyk please see the footprint, performer didn't receive a payment in this job (harvest-foundation/telegram#55) automatically:
```
1700905861 1mon "Job removed from WBS" (0.22.6)
  reason: Job was closed, order is finished
  login: olenagerasimova
  token: github;Harvest-foundation/telegram;55
  job: gh:harvest-foundation/telegram#55
  age: 12244
  flow: Close job; Finish order; Order was finished; Remove job from WBS

1700904829 1mon "Remove job from WBS" (0.22.6)
  reason: Job was closed, order is finished
  login: olenagerasimova
  token: github;Harvest-foundation/telegram;55
  job: gh:harvest-foundation/telegram#55
  age: 12244
  flow: Close job; Finish order; Order was finished

1700904828 1mon "Agenda was updated" (0.22.6)
  reason: Job was closed, order is finished
  login: olenagerasimova
  token: github;Harvest-foundation/telegram;55
  job: gh:harvest-foundation/telegram#55
  age: 12244
  flow: Close job; Finish order; Order was finished

1700904825 1mon "Speed was updated" (0.22.6)
  reason: Job was closed, order is finished
  login: olenagerasimova
  token: github;Harvest-foundation/telegram;55
  job: gh:harvest-foundation/telegram#55
  age: 12244
  flow: Close job; Finish order; Order was finished

1700903778 1mon "Error" (0.22.6)
  reason: Order was finished
  minutes: 30
  origin_id: 1700903772
  login: olenagerasimova
  message: Claim #1700903772 in CAWJH9K0X: type="Make payment", stakeholder="recharge_on_deficit", token="github;Harvest-foundation/telegram;55"
  origin_type: Make payment
  token: github;Harvest-foundation/telegram;55
  stacktrace: java.lang.IllegalStateException: org.codehaus.groovy.runtime.InvokerInvocationException in com.zerocracy.stk.pm.cost.funding.recharge_on_deficit
	at com.zerocracy.farm.reactive.StkRuntime.process(StkRuntime.java:78)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:81)
	at com.zerocracy.farm.reactive.StkSmart.process(StkSmart.java:66)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:82)
	at com.zerocracy.farm.reactive.Brigade.lambda$apply$0(Brigade.java:64)
	at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.iterator.Filtered.hasNext(Filtered.java:90)
	at org.cactoos.iterator.LengthOf.lambda$new$0(LengthOf.java:52)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.scalar.NumberEnvelope.doubleValue(NumberEnvelope.java:113)
	at org.cactoos.iterable.LengthOf.lambda$new$0(LengthOf.java:51)
	at org.cactoos.scalar.NumberEnvelope.lambda$new$1(NumberEnvelope.java:73)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.scalar.NumberEnvelope.intValue(NumberEnvelope.java:98)
	at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:67)
	at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:37)
	at org.cactoos.func.IoCheckedBiFunc.lambda$apply$0(IoCheckedBiFunc.java:60)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:61)
	at com.zerocracy.farm.reactive.DefaultFlush.process(DefaultFlush.java:98)
	at com.zerocracy.farm.reactive.DefaultFlush.lambda$exec$0(DefaultFlush.java:67)
	at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
	at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
	at org.cactoos.func.IoCheckedFunc.lambda$apply$0(IoCheckedFunc.java:59)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:59)
	at org.cactoos.func.IoCheckedProc.exec(IoCheckedProc.java:57)
	at com.zerocracy.pm.Claims.take(Claims.java:150)
	at com.zerocracy.farm.reactive.DefaultFlush.exec(DefaultFlush.java:66)
	at com.zerocracy.farm.reactive.DefaultFlush.exec(DefaultFlush.java:44)
	at com.zerocracy.farm.reactive.AsyncFlush.lambda$exec$2(AsyncFlush.java:118)
	at com.jcabi.log.VerboseCallable.call(VerboseCallable.java:173)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:221)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.codehaus.groovy.runtime.InvokerInvocationException: com.zerocracy.pmo.recharge.Stripe$PaymentException: com.stripe.exception.CardException: Your card has insufficient funds.; request-id: req_sFD0KQb0L67CkF
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:105)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:822)
	at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:46)
	at groovy.lang.Script.invokeMethod(Script.java:80)
	at com.zerocracy.farm.reactive.StkRuntime.process(StkRuntime.java:65)
	... 41 more
Caused by: com.zerocracy.pmo.recharge.Stripe$PaymentException: com.stripe.exception.CardException: Your card has insufficient funds.; request-id: req_sFD0KQb0L67CkF
	at com.zerocracy.pmo.recharge.Stripe.charge(Stripe.java:136)
	at com.zerocracy.pmo.recharge.Recharge.pay(Recharge.java:109)
	at com.zerocracy.pmo.recharge.Recharge$pay$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
	at com.zerocracy.stk.pm.cost.funding.recharge_on_deficit.exec(recharge_on_deficit.groovy:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	... 48 more
Caused by: com.stripe.exception.CardException: Your card has insufficient funds.; request-id: req_sFD0KQb0L67CkF
	at com.stripe.net.LiveStripeResponseGetter.handleAPIError(LiveStripeResponseGetter.java:654)
	at com.stripe.net.LiveStripeResponseGetter._request(LiveStripeResponseGetter.java:489)
	at com.stripe.net.LiveStripeResponseGetter.request(LiveStripeResponseGetter.java:72)
	at com.stripe.net.APIResource.request(APIResource.java:167)
	at com.stripe.model.Charge.create(Charge.java:622)
	at com.zerocracy.pmo.recharge.Stripe.charge(Stripe.java:121)
	... 59 more

  job: gh:harvest-foundation/telegram#55
  cash: $8.00
  flow: Close job; Finish order; Make payment

1700903774 1mon "Order was finished" (0.22.6)
  reason: Job was closed, order is finished
  login: olenagerasimova
  token: github;Harvest-foundation/telegram;55
  job: gh:harvest-foundation/telegram#55
  flow: Close job; Finish order
  age: 12244
```

**Comment by krzyk** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/1188#issuecomment-408622078))

@krzyk The user @krzyk[/z](https://www.0crat.com/u/krzyk) resigned from [#1188](https://github.com/zerocracy/farm/issues/1188), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
The job [#1188](https://github.com/zerocracy/farm/issues/1188) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2111150214); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by carlosmiranda** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/1188#issuecomment-418618979))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#1188](https://github.com/zerocracy/farm/issues/1188), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
The job [#1188](https://github.com/zerocracy/farm/issues/1188) assigned to @denis-konovalyenko[/z](https://www.0crat.com/u/denis-konovalyenko), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2611455797); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by denis-konovalyenko** [comment]
@0crat wait (impediments: #1711, #1712)

**Comment by 0crat** [comment]
> @0crat wait (impediments: #1711, #1712) ([here](https://github.com/zerocracy/farm/issues/1188#issuecomment-422932891))

@denis-konovalyenko The impediment for [#1188](https://github.com/zerocracy/farm/issues/1188) was registered successfully by @denis-konovalyenko[/z](https://www.0crat.com/u/denis-konovalyenko)

**Comment by g4s8** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zerocracy/farm/issues/1188#issuecomment-453107763))

@g4s8 @g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1188](https://github.com/zerocracy/farm/issues/1188), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`2.40.4`

**Comment by g4s8** [comment]
@rultor stop

**Comment by g4s8** [comment]
@rultor cancel

**Comment by g4s8** [comment]
@rultor stop

**Comment by g4s8** [comment]
@rultor release, tag=`0.40.4`

**Comment by g4s8** [comment]
fixed in https://github.com/zerocracy/farm/commit/5919a9ae340f1f473f9b0dbbdc3fd2b6da46fe6c release in `0.40.4`

**Comment by 0crat** [comment]
Job [#1188](https://github.com/zerocracy/farm/issues/1188) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 1 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#1188](https://github.com/zerocracy/farm/issues/1188) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
