### ISSUE TITLE
Failed to aqcuire blanks.xml for user

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#1194]
See [here](https://github.com/jcabi/jcabi-github/issues/1422#issuecomment-398704432).

There is the Blanks measurement, which counts how many times an opened ticket was rejected. I think the problem is the fact that the issue's author is not a user in the system, so he does not have a personalized file under ``/blanks``.

**Edit:**

I got a mail from Sentry, with a similar exception for ``/verbosity/carlosmirands.xml``.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by olenagerasimova** [comment]
I've got similar exception when said `/hello` to 0crat in telegram:
```
There is an unrecoverable failure on my side. Please, submit it here (https://github.com/zerocracy/farm/issues):

PID: 4@2a5ea468-7e77-489c-80d0-c8be03a5d7e1, thread: zerocrat_bot Telegram Executor
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 1min: 61df0a5983f1/38s/0/3/true/false by QuartzScheduler_Worker-1


0.22.7 (https://github.com/zerocracy/farm): ID: 344195865, From: olenaGerasimova, ChatId: 519312215
```

**Comment by g4s8** [comment]
@amihaiemil @olenagerasimova  looks like generic error in `SyncProject`, 0crat failed to acquire any file:
```
java.lang.IllegalStateException: Failed to acquire "roles.xml" in "PMO" in 1min: 61df0a5983f1/10min/0/4/true/false by QuartzScheduler_Worker-1
    at com.zerocracy.farm.sync.SyncProject.acq(SyncProject.java:77)
    at com.zerocracy.farm.strict.StrictProject.acq(StrictProject.java:129)
    at com.zerocracy.farm.props.PropsProject.acq(PropsProject.java:81)
    at com.zerocracy.farm.footprint.FtProject.acq(FtProject.java:67)
    at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
    at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:62)
    at com.zerocracy.pmo.Pmo.acq(Pmo.java:64)
    at com.zerocracy.pm.staff.Roles.item(Roles.java:323)
    at com.zerocracy.pm.staff.Roles.bootstrap(Roles.java:69)
    at com.zerocracy.pm.staff.Roles$bootstrap.call
    at com.zerocracy.stk.pm.in.orders.resign_on_delay.exec(resign_on_delay.groovy:36)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:822)
    at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:46)
    at groovy.lang.Script.invokeMethod(Script.java:80)
    at com.zerocracy.farm.reactive.StkRuntime.process(StkRuntime.java:65)
    at com.zerocracy.farm.StkSafe.process(StkSafe.java:81)
    at com.zerocracy.farm.reactive.StkSmart.process(StkSmart.java:66)
    at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:82)
    at com.zerocracy.farm.reactive.Brigade.lambda$apply$0(Brigade.java:64)
    at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
    at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
    at org.cactoos.iterator.Filtered.hasNext(Filtered.java:90)
    at org.cactoos.iterator.LengthOf.lambda$new$0(LengthOf.java:52)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
    at org.cactoos.scalar.NumberEnvelope.doubleValue(NumberEnvelope.java:113)
    at org.cactoos.iterable.LengthOf.lambda$new$0(LengthOf.java:51)
    at org.cactoos.scalar.NumberEnvelope.lambda$new$1(NumberEnvelope.java:73)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
    at org.cactoos.scalar.NumberEnvelope.intValue(NumberEnvelope.java:98)
    at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:67)
    at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:37)
    at org.cactoos.func.IoCheckedBiFunc.lambda$apply$0(IoCheckedBiFunc.java:60)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:61)
    at com.zerocracy.farm.reactive.DefaultFlush.process(DefaultFlush.java:98)
    at com.zerocracy.farm.reactive.DefaultFlush.lambda$exec$0(DefaultFlush.java:67)
    at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
    at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
    at org.cactoos.func.IoCheckedFunc.lambda$apply$0(IoCheckedFunc.java:59)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:59)
    at org.cactoos.func.IoCheckedProc.exec(IoCheckedProc.java:57)
    at com.zerocracy.pm.Claims.take(Claims.java:150)
    at com.zerocracy.farm.reactive.DefaultFlush.exec(DefaultFlush.java:66)
    at com.zerocracy.farm.reactive.DefaultFlush.exec(DefaultFlush.java:44)
    at com.zerocracy.farm.reactive.AsyncFlush.lambda$exec$2(AsyncFlush.java:118)
    at com.jcabi.log.VerboseCallable.call(VerboseCallable.java:173)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:221)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by g4s8** [comment]
@amihaiemil looks like a duplicate of #1168 but now it can't acquire `PMO` files.

**Comment by amihaiemil** [comment]
@g4s8 Right, closing then :D

**Comment by g4s8** [comment]
@0crat hello

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@913782de-5eeb-4cf1-9e4d-4c5e85dde386, thread: pool-17-thread-1
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 1min: d2e6b100d1f8/11min/0/2/true/false by AsyncFlush-3
```

[0.22.8](https://github.com/zerocracy/farm): Issue: zerocracy/farm#1194, Comment: 398723449

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@913782de-5eeb-4cf1-9e4d-4c5e85dde386, thread: pool-17-thread-1
com.zerocracy.radars.github.ReSafe[82] java.io.IOException: java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 1min: d2e6b100d1f8/11min/0/2/true/false by AsyncFlush-3
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 1min: d2e6b100d1f8/11min/0/2/true/false by AsyncFlush-3
```

[0.22.8](https://github.com/zerocracy/farm): Issue: zerocracy/farm#1194, Action: `created`

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1194` is not assigned, can't get performer

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@913782de-5eeb-4cf1-9e4d-4c5e85dde386, thread: AsyncFlush-6
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "blanks/amihaiemil.xml" in "PMO" in 1min: d2e6b100d1f8/17min/0/4/true/false by AsyncFlush-3
```

[0.22.8](https://github.com/zerocracy/farm): CID: [1711147044](https://www.0crat.com/C3NDPUA8L/1711147044), Type: "Close job", Author: "amihaiemil"

**Comment by g4s8** [comment]
@rultor release, tag=`0.22.9`

**Comment by g4s8** [comment]
@rultor release, tag=`0.22.10`

**Comment by g4s8** [comment]
@rultor release, tag=`0.22.11`

**Comment by g4s8** [comment]
@rultor release, tag=`0.22.12`
