### ISSUE TITLE
duplicates in verbosity.xml

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#1233]
See what happened here: https://github.com/yegor256/0pdd/issues/188#issuecomment-399843095

I believe we should check the XML file before adding a new element there. Or maybe just delete the previous right with Xembly `remove` and overwrite the new value.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@yegor256 looks like it was triggered twice because of reopen (2 `Close job` claims in one issue). I think we need to override previous verbosity value in this case. 

Full stacktrace:
```
java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:yegor256/0pdd#188] declared for identity constraint of element "verbosity".
    at com.jcabi.xml.StrictXML.<init>(StrictXML.java:124)
    at com.jcabi.xml.StrictXML.<init>(StrictXML.java:95)
    at com.jcabi.xml.StrictXML.<init>(StrictXML.java:86)
    at com.zerocracy.Xocument.modify(Xocument.java:252)
    at com.zerocracy.pmo.Verbosity.add(Verbosity.java:61)
    at com.zerocracy.pmo.Verbosity$add$0.call
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:144)
    at com.zerocracy.stk.pm.in.orders.update_verbosity.exec(update_verbosity.groovy:53)
    at sun.reflect.GeneratedMethodAccessor746.invoke
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:822)
    at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:46)
    at groovy.lang.Script.invokeMethod(Script.java:80)
    at com.zerocracy.farm.reactive.StkRuntime.process(StkRuntime.java:65)
    at com.zerocracy.farm.StkSafe.process(StkSafe.java:81)
    at com.zerocracy.farm.reactive.StkSmart.process(StkSmart.java:66)
    at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:82)
    at com.zerocracy.farm.reactive.Brigade.lambda$apply$0(Brigade.java:64)
    at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
    at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
    at org.cactoos.iterator.Filtered.hasNext(Filtered.java:90)
    at org.cactoos.iterator.LengthOf.lambda$new$0(LengthOf.java:52)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
    at org.cactoos.scalar.NumberEnvelope.doubleValue(NumberEnvelope.java:113)
    at org.cactoos.iterable.LengthOf.lambda$new$0(LengthOf.java:51)
    at org.cactoos.scalar.NumberEnvelope.lambda$new$1(NumberEnvelope.java:73)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
    at org.cactoos.scalar.NumberEnvelope.intValue(NumberEnvelope.java:98)
    at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:67)
    at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:37)
    at org.cactoos.func.IoCheckedBiFunc.lambda$apply$0(IoCheckedBiFunc.java:60)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:61)
    at com.zerocracy.farm.reactive.DefaultFlush.process(DefaultFlush.java:98)
    at com.zerocracy.farm.reactive.DefaultFlush.lambda$exec$0(DefaultFlush.java:67)
    at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
    at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
    at org.cactoos.func.IoCheckedFunc.lambda$apply$0(IoCheckedFunc.java:59)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:59)
    at org.cactoos.func.IoCheckedProc.exec(IoCheckedProc.java:57)
    at com.zerocracy.pm.Claims.take(Claims.java:150)
    at com.zerocracy.farm.reactive.DefaultFlush.exec(DefaultFlush.java:66)
    at com.zerocracy.farm.reactive.DefaultFlush.exec(DefaultFlush.java:44)
    at com.zerocracy.farm.reactive.AsyncFlush.lambda$exec$2(AsyncFlush.java:119)
    at com.jcabi.log.VerboseCallable.call(VerboseCallable.java:173)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:221)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by 0crat** [comment]
Job [#1233](https://github.com/zerocracy/farm/issues/1233) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#1519](https://github.com/zerocracy/farm/issues/1519) is still not solved.

**Comment by paulodamaso** [comment]
@yegor256 The PR #1511 was already merged and the puzzle #1519 added, please close.

**Comment by yegor256** [comment]
@paulodamaso thanks!

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@ff4e4492-afa3-49e7-b2e6-def21277e93d, thread: pool-477-thread-1
java.lang.NumberFormatException[65] java.lang.NumberFormatException: For input string: "2018-08-02T09:32:54.525Z"
```

[0.28.5](https://github.com/zerocracy/farm): Issue: zerocracy/farm#1233, Action: `closed`

**Comment by paulodamaso** [comment]
@0crat status

**Comment by g4s8** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zerocracy/farm/issues/1233#issuecomment-409990208))

@g4s8 The job [#1233](https://github.com/zerocracy/farm/issues/1233) is now out of scope

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by paulodamaso** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/1233#issuecomment-410002560))

@paulodamaso This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1233](https://github.com/zerocracy/farm/issues/1233) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 37min
  * @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%231233%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by paulodamaso** [comment]
@ypshenychka just assuring that 0crat told you about the task

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#1519](https://github.com/zerocracy/farm/issues/1519) is solved here.
