### ISSUE TITLE
BundlesTest sometimes fails

### ISSUE THREAD

**Issue by krzyk** [zerocracy/farm#1238]
Sometimes BundlesTest fails with ` BundlesTest.oneBundleWorksFine:252->lambda$oneBundleWorksFine$4:231 ? IllegalArgument`.

Examples: 
1. https://github.com/zerocracy/farm/pull/1219#issuecomment-399959882
2. https://github.com/zerocracy/farm/issues/1173#issuecomment-398716094
3. https://github.com/zerocracy/farm/pull/1115#issuecomment-396096114
4. https://github.com/zerocracy/farm/pull/1115#issuecomment-396096114
5. https://github.com/zerocracy/farm/pull/1158#issuecomment-398316919

```
Running [com/zerocracy/bundles/zerocrat_assignment_adds_to_wbs]
#fatalError(): Error reported by XML parser; SystemID: file:///; Line#: 1; Column#: 1
swallowed runtime exception: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@44bc99d rejected from java.util.concurrent.ThreadPoolExecutor@2f0eca34[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 0]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
        at com.zerocracy.farm.reactive.AsyncFlush.exec(AsyncFlush.java:113)
        at com.zerocracy.farm.reactive.AsyncFlush.exec(AsyncFlush.java:46)
        at com.zerocracy.farm.reactive.RvProject.lambda$acq$0(RvProject.java:66)
        at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
        at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
        at org.cactoos.func.IoCheckedFunc.lambda$apply$0(IoCheckedFunc.java:59)
        at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
        at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:59)
        at org.cactoos.func.IoCheckedProc.exec(IoCheckedProc.java:57)
        at com.zerocracy.farm.reactive.RvClaims.close(RvClaims.java:74)
        at com.zerocracy.pm.Claims.bootstrap(Claims.java:75)
        at com.zerocracy.farm.reactive.DefaultFlush.exec(DefaultFlush.java:62)
        at com.zerocracy.farm.reactive.DefaultFlush.exec(DefaultFlush.java:44)
        at com.zerocracy.farm.reactive.AsyncFlush.lambda$exec$2(AsyncFlush.java:119)
        at com.jcabi.log.VerboseCallable.call(VerboseCallable.java:173)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:221)
        at java.lang.Thread.run(Thread.java:748)

Tests run: 55, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 113.637 sec <<< FAILURE! - in [com/zerocracy/bundles/zerocrat_assignment_adds_to_wbs]
oneBundleWorksFine[com/zerocracy/bundles/bans_issue_reporter](com.zerocracy.BundlesTest)  Time elapsed: 2.918 sec  <<< ERROR!
java.lang.IllegalArgumentException: Failed to configure transformer by net.sf.saxon.TransformerFactoryImpl: [Error reported by XML parser; SystemID: file:///; Line#: 1; Column#: 1]
        at com.jcabi.xml.XSLDocument.transformInto(XSLDocument.java:391)
        at com.jcabi.xml.XSLDocument.transform(XSLDocument.java:338)
        at com.zerocracy.Xocument.lambda$upgraded$4(Xocument.java:292)
        at org.cactoos.scalar.Reduced.value(Reduced.java:72)
        at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
        at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
        at com.zerocracy.Xocument.upgraded(Xocument.java:310)
        at com.zerocracy.Xocument.bootstrap(Xocument.java:168)
        at com.zerocracy.pm.Claims.bootstrap(Claims.java:74)
        at com.zerocracy.BundlesTest.lambda$oneBundleWorksFine$4(BundlesTest.java:231)
        at org.cactoos.scalar.And.lambda$null$0(And.java:132)
        at org.cactoos.scalar.And.value(And.java:167)
        at com.zerocracy.BundlesTest.oneBundleWorksFine(BundlesTest.java:252)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:393)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.xml.transform.TransformerConfigurationException: net.sf.saxon.s9api.SaxonApiException: org.xml.sax.SAXParseException; systemId: file:///; lineNumber: 1; columnNumber: 1; Premature end of file.
        at net.sf.saxon.jaxp.SaxonTransformerFactory.newTemplates(SaxonTransformerFactory.java:158)
        at net.sf.saxon.jaxp.SaxonTransformerFactory.newTransformer(SaxonTransformerFactory.java:111)
        at com.jcabi.xml.XSLDocument.transformInto(XSLDocument.java:374)
        ... 31 more
Caused by: net.sf.saxon.s9api.SaxonApiException: org.xml.sax.SAXParseException; systemId: file:///; lineNumber: 1; columnNumber: 1; Premature end of file.
        at net.sf.saxon.s9api.XsltCompiler.compile(XsltCompiler.java:742)
        at net.sf.saxon.jaxp.SaxonTransformerFactory.newTemplates(SaxonTransformerFactory.java:155)
        ... 33 more
Caused by: net.sf.saxon.trans.XPathException: org.xml.sax.SAXParseException; systemId: file:///; lineNumber: 1; columnNumber: 1; Premature end of file.
        at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:447)
        at net.sf.saxon.event.Sender.send(Sender.java:164)
        at net.sf.saxon.style.StylesheetModule.loadStylesheet(StylesheetModule.java:230)
        at net.sf.saxon.style.Compilation.compileSingletonPackage(Compilation.java:106)
        at net.sf.saxon.s9api.XsltCompiler.compile(XsltCompiler.java:739)
        ... 34 more
Caused by: org.xml.sax.SAXParseException; systemId: file:///; lineNumber: 1; columnNumber: 1; Premature end of file.
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
        at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:1014)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
        at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:427)
        ... 38 more

Running com.zerocracy.pm.staff.ElectionsTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 12.405 sec - in com.zerocracy.pm.staff.ElectionsTest
Running com.zerocracy.tk.project.TkClaimTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 10.451 sec - in com.zerocracy.tk.project.TkClaimTest
Running com.zerocracy.farm.reactive.BrigadeTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.942 sec - in com.zerocracy.farm.reactive.BrigadeTest
Running com.zerocracy.farm.SmartFarmTest
swallowed exception: java.lang.IllegalStateException('http://datum.zerocracy.com/latest/rules/pm/no-lost-orders.xsl says: The order for job "gh:test/test#22" exists in orders.xml, but the job is absent in the WBS among 0 jobs.')
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.727 sec - in com.zerocracy.farm.SmartFarmTest
Running com.zerocracy.tk.project.TkXmlTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.265 sec - in com.zerocracy.tk.project.TkXmlTest
Running com.zerocracy.farm.footprint.FtFarmTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.94 sec - in com.zerocracy.farm.footprint.FtFarmTest
Running com.zerocracy.XocumentTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.243 sec - in com.zerocracy.XocumentTest
Running com.zerocracy.tools.SignatureTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 sec - in com.zerocracy.tools.SignatureTest

Results :

Tests in error:
  BundlesTest.oneBundleWorksFine:252->lambda$oneBundleWorksFine$4:231 ? IllegalArgument
```

(Full log at http://www.rultor.com/t/15075-399955589)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1238](https://github.com/zerocracy/farm/issues/1238) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@krzyk Looks like that all the times it happened `com/zerocracy/bundles/zerocrat_assignment_adds_to_wbs`was involved. For the error stacktrace I suppose that we are having some concurrency issues in some test; I am suspicious that some another test is changing or deleting claims / project / farm information used by `com/zerocracy/bundles/zerocrat_assignment_adds_to_wbs` and it's why it cant' load the desired files. I was thinking in isolating each `BundleTest` and syncrhonizing them, but it would make testing a lot slower. WDYT?

**Comment by krzyk** [comment]
@paulodamaso Hmm, but the bundle tests should already be isolated, if not they would constantly fail

**Comment by paulodamaso** [comment]
@krzyk I see. Well, I don't have any other ideas about it, so I'll let it to someone else to figure out what's happening.

**Comment by paulodamaso** [comment]
@0crat refuse

**Comment by paulodamaso** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/1238#issuecomment-410004984))

@paulodamaso The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#1238](https://github.com/zerocracy/farm/issues/1238), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by carlosmiranda** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/1238#issuecomment-423879683))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#1238](https://github.com/zerocracy/farm/issues/1238), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
The job [#1238](https://github.com/zerocracy/farm/issues/1238) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2681143559); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by krzyk** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/1238#issuecomment-425654682))

@krzyk The user @krzyk[/z](https://www.0crat.com/u/krzyk) resigned from [#1238](https://github.com/zerocracy/farm/issues/1238), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1238](https://github.com/zerocracy/farm/issues/1238), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@krzyk it should be fixed with #1949 - some bundle tests had same project ids, so it was possible that one test changes `xml` resources of another test when running parallel, I updated bundle directories names (it's the source of project id) and added a check to fail `BundleTest` if duplicates were found.

**Comment by krzyk** [comment]
@g4s8 thanks

**Comment by 0crat** [comment]
Job [#1238](https://github.com/zerocracy/farm/issues/1238) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 6 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#1238](https://github.com/zerocracy/farm/issues/1238) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
