### ISSUE TITLE
Error on "hiring"

### ISSUE THREAD

**Issue by llorllale** [zerocracy/farm#1247]
Sent out a "hiring" message and received this error:

```
java.lang.IllegalStateException: [POST https://www.0crat.com/hiring-send/CAZUREFND] failed in 649ms: 1 error(s) in XML document: -1:-1: Duplicate unique value [CAZUREFND] declared for identity constraint of element "vacancies".
	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:115)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkSslOnly.act(TkSslOnly.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.http.BkBasic.print(BkBasic.java:108)
	at org.takes.http.BkBasic.accept(BkBasic.java:84)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [CAZUREFND] declared for identity constraint of element "vacancies".
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:124)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:95)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:86)
	at com.zerocracy.Xocument.modify(Xocument.java:252)
	at com.zerocracy.pmo.Vacancies.add(Vacancies.java:85)
	at com.zerocracy.tk.project.TkHiring.act(TkHiring.java:76)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:210)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at com.zerocracy.tk.TkSoftForward.lambda$new$0(TkSoftForward.java:50)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.forward.TkForward.act(TkForward.java:68)
	at org.takes.facets.fork.FkFixed$1.route(FkFixed.java:56)
	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:109)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:89)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:108)
	at org.takes.tk.TkGzip$1.act(TkGzip.java:58)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:73)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:86)
	... 14 more
```

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@llorllale yes, this project already has submitted vacancy (2018.06.02). Old vacancies should be removed automatically after one month after submitting: https://github.com/zerocracy/farm/issues/971

I think we have to show more friendly message in such case, like "vacancy for this project already submitted", without stacktrace.

**Comment by llorllale** [comment]
@g4s8 oh, ok. How do I view vacancies previously submitted?

**Comment by g4s8** [comment]
@llorllale sorry, it's not implemented also: #970, I'll try to fix it soon.

**Comment by llorllale** [comment]
@g4s8 should I rephrase this bug?

> I think we have to show more friendly message in such case, like "vacancy for this project already submitted", without stacktrace.

**Comment by g4s8** [comment]
@llorllale yes, please update description

**Comment by llorllale** [comment]
@g4s8 done

**Comment by g4s8** [comment]
@0crat assign @uurl

**Comment by 0crat** [comment]
> @0crat assign @uurl ([here](https://github.com/zerocracy/farm/issues/1247#issuecomment-401103063))

@g4s8 The job [#1247](https://github.com/zerocracy/farm/issues/1247) assigned to @uurl[/z](https://www.0crat.com/u/uurl), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1791705661); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @uurl[/z](https://www.0crat.com/u/uurl) is on vacation; this ticket may be delayed; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by uurl** [comment]
@0crat wait

**Comment by 0crat** [comment]
> @0crat wait ([here](https://github.com/zerocracy/farm/issues/1247#issuecomment-401628750))

@uurl The impediment for [#1247](https://github.com/zerocracy/farm/issues/1247) was registered successfully by @uurl[/z](https://www.0crat.com/u/uurl)

**Comment by 0crat** [comment]
@uurl[/z](https://www.0crat.com/u/uurl) this job was assigned to you 1mon ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
> @0crat continue ([here](https://github.com/zerocracy/farm/issues/1247#issuecomment-411738319))

@g4s8 @g4s8[/z](https://www.0crat.com/u/g4s8) continued working on job [#1247](https://github.com/zerocracy/farm/issues/1247)

**Comment by uurl** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/1247#issuecomment-415465653))

@uurl This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1247](https://github.com/zerocracy/farm/issues/1247) is [in scope](http://www.zerocracy.com/policy.html#14) for 2mon
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * These users are banned and won't be assigned:
    * @uurl[/z](https://www.0crat.com/u/uurl): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%231247%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by uurl** [comment]
@krzyk ping

**Comment by krzyk** [comment]
@uurl yes?

**Comment by 0crat** [comment]
The job [#1247](https://github.com/zerocracy/farm/issues/1247) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/7067e478-1b79-419c-bc9a-af40eff33bd1); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by carlosmiranda** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/1247#issuecomment-541991161))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#1247](https://github.com/zerocracy/farm/issues/1247), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/1247#issuecomment-541991161))

@carlosmiranda Job refused in 15 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)
