### ISSUE TITLE
SlackRadarTest sometimes fail

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1262]
`SlackRadarTest` may fail with error:
```
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.248 sec <<< FAILURE! - in com.zerocracy.radars.slack.SlackRadarTest
closesSession(com.zerocracy.radars.slack.SlackRadarTest)  Time elapsed: 4.248 sec  <<< FAILURE!
Wanted but not invoked:
slackSession.disconnect();
-> at com.zerocracy.radars.slack.SlackRadarTest.closesSession(SlackRadarTest.java:57)

However, there were exactly 6 interactions with this mock:
slackSession.connect();
-> at com.zerocracy.radars.slack.SlackRadar.start(SlackRadar.java:155)

slackSession.sessionPersona();
-> at com.zerocracy.radars.slack.SlackRadar.start(SlackRadar.java:158)

slackSession.sessionPersona();
-> at com.zerocracy.radars.slack.SlackRadar.start(SlackRadar.java:159)

slackSession.getTeam();
-> at com.zerocracy.radars.slack.SlackRadar.start(SlackRadar.java:160)

slackSession.addMessagePostedListener(
    com.zerocracy.radars.slack.SlackRadar$$Lambda$398/1545203233@338a8528
);
-> at com.zerocracy.radars.slack.SlackRadar.start(SlackRadar.java:162)

slackSession.addChannelJoinedListener(
    com.zerocracy.radars.slack.SlackRadar$$Lambda$401/726868359@7395bb69
);
-> at com.zerocracy.radars.slack.SlackRadar.start(SlackRadar.java:171)


        at com.zerocracy.radars.slack.SlackRadarTest.closesSession(SlackRadarTest.java:57)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:393)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

some build logs:
https://github.com/zerocracy/farm/pull/1241#issuecomment-400658805
https://github.com/zerocracy/farm/issues/1263#issuecomment-400709275

**Comment by 0crat** [comment]
Job [#1262](https://github.com/zerocracy/farm/issues/1262) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@0crat assign @krzyk

**Comment by g4s8** [comment]
@krzyk I temporary disabled `SlackRadarTest` because it's failing too often on rultor

**Comment by 0crat** [comment]
> @0crat assign @krzyk  ([here](https://github.com/zerocracy/farm/issues/1262#issuecomment-400744038))

@g4s8 The job [#1262](https://github.com/zerocracy/farm/issues/1262) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1781647852); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by krzyk** [comment]
@g4s8 changes have been merged in #1290, please close this issue

**Comment by g4s8** [comment]
@krzyk thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1262](https://github.com/zerocracy/farm/issues/1262) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +38 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
