### ISSUE TITLE
NPE in /guts

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1315]
`/guts` returns `NullPointerException`:
```
java.lang.IllegalStateException: [GET https://www.0crat.com/guts] failed in 5s: null
	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:115)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkSslOnly.act(TkSslOnly.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.http.BkBasic.print(BkBasic.java:108)
	at org.takes.http.BkBasic.accept(BkBasic.java:84)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at com.zerocracy.farm.SmartLock.stacktrace(SmartLock.java:66)
	at com.zerocracy.farm.sync.SyncFarm.lambda$null$3(SyncFarm.java:119)
	at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.iterator.Mapped.next(Mapped.java:70)
	at org.cactoos.iterable.Joined.lambda$new$1(Joined.java:67)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.iterable.IterableEnvelope.iterator(IterableEnvelope.java:59)
	at org.xembly.Directives.append(Directives.java:250)
	at com.zerocracy.farm.sync.SyncFarm.lambda$find$4(SyncFarm.java:110)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at com.zerocracy.farm.guts.GsProject.acq(GsProject.java:114)
	at com.zerocracy.farm.strict.StrictProject.acq(StrictProject.java:129)
	at com.zerocracy.farm.guts.GsProject.acq(GsProject.java:103)
	at com.zerocracy.farm.guts.GsProject.acq(GsProject.java:103)
	at com.zerocracy.farm.footprint.FtProject.acq(FtProject.java:67)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.farm.guts.GsProject.acq(GsProject.java:103)
	at com.zerocracy.farm.guts.Guts.value(Guts.java:98)
	at com.zerocracy.farm.guts.Guts.value(Guts.java:39)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at com.zerocracy.farm.guts.TkGuts.act(TkGuts.java:70)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:154)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:210)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at com.zerocracy.tk.TkSoftForward.lambda$new$0(TkSoftForward.java:50)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.forward.TkForward.act(TkForward.java:68)
	at org.takes.facets.fork.FkFixed$1.route(FkFixed.java:56)
	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:109)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:89)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:108)
	at org.takes.tk.TkGzip$1.act(TkGzip.java:58)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:73)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:86)
	... 14 more
```

**Comment by g4s8** [comment]
Fixed in cda7dba82e3839078ff6e802473002699003a68f

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1315` is not assigned, can't get performer
