### ISSUE TITLE
One job in my agenda has no cost assigned

### ISSUE THREAD

**Issue by emilianodellacasa** [zerocracy/farm#1337]
The first job that has been assigned to me has no associated cost, maybe the reason why is that it was manually assigned or because of the rate conversion problem.

**Comment by g4s8** [comment]
@emilianodellacasa please, add a link to that job

**Comment by emilianodellacasa** [comment]
This is the issue: https://github.com/zold-io/zold/issues/98

**Comment by 0crat** [comment]
Job [#1337](https://github.com/zerocracy/farm/issues/1337) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by g4s8** [comment]
@emilianodellacasa it's a bug: assign DEV role fails first time, because of incorrect rate string, but it partially applied - you got DEV role, but rate didn't change, it was fixed after second `assign role` request, but between these two requests you was elected for `#89` job. We should not assign the role if we failed to change the rate. It's a one time issue, so please ask ARC to pay you manually for this job.

Footprint:
```
1781430118 8days "Error" (0.23.3)
  role: DEV
  channel: zold-ruby
  pid: CAZPZR9FS
  origin_id: 1781430111
  login: emilianodellacasa
  message: Claim #1781430111 in CAZPZR9FS: type="Assign role", stakeholder="assign_role", author="yegor256", token="slack;CAZPZR9FS;UAZPZGDMW"
  origin_type: Assign role
  token: slack;CAZPZR9FS;UAZPZGDMW
  stacktrace: java.lang.IllegalStateException: org.codehaus.groovy.runtime.InvokerInvocationException in com.zerocracy.stk.pm.staff.roles.assign_role
	at com.zerocracy.farm.reactive.StkRuntime.process(StkRuntime.java:78)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:91)
	at com.zerocracy.farm.reactive.StkSmart.process(StkSmart.java:66)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:82)
	at com.zerocracy.farm.reactive.Brigade.lambda$apply$0(Brigade.java:64)
	at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.iterator.Filtered.hasNext(Filtered.java:90)
	at org.cactoos.iterator.LengthOf.lambda$new$0(LengthOf.java:52)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.scalar.NumberEnvelope.doubleValue(NumberEnvelope.java:113)
	at org.cactoos.iterable.LengthOf.lambda$new$0(LengthOf.java:51)
	at org.cactoos.scalar.NumberEnvelope.lambda$new$1(NumberEnvelope.java:73)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.scalar.NumberEnvelope.intValue(NumberEnvelope.java:98)
	at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:67)
	at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:37)
	at org.cactoos.func.IoCheckedBiFunc.lambda$apply$0(IoCheckedBiFunc.java:60)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:61)
	at com.zerocracy.farm.reactive.DefaultFlush.process(DefaultFlush.java:98)
	at com.zerocracy.farm.reactive.DefaultFlush.lambda$exec$0(DefaultFlush.java:67)
	at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
	at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
	at org.cactoos.func.IoCheckedFunc.lambda$apply$0(IoCheckedFunc.java:59)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:59)
	at org.cactoos.func.IoCheckedProc.exec(IoCheckedProc.java:57)
	at com.zerocracy.pm.Claims.take(Claims.java:155)
	at com.zerocracy.farm.reactive.DefaultFlush.exec(DefaultFlush.java:66)
	at com.zerocracy.farm.reactive.DefaultFlush.exec(DefaultFlush.java:44)
	at com.zerocracy.farm.reactive.AsyncFlush.lambda$exec$2(AsyncFlush.java:119)
	at com.jcabi.log.VerboseCallable.call(VerboseCallable.java:173)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:221)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.codehaus.groovy.runtime.InvokerInvocationException: com.zerocracy.cash.CashParsingException: Can't parse cash value pair "40EUR"
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:105)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:822)
	at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:46)
	at groovy.lang.Script.invokeMethod(Script.java:80)
	at com.zerocracy.farm.reactive.StkRuntime.process(StkRuntime.java:65)
	... 41 more
Caused by: com.zerocracy.cash.CashParsingException: Can't parse cash value pair "40EUR"
	at com.zerocracy.cash.Pair.valueOf(Pair.java:161)
	at com.zerocracy.cash.Cash$S.parse(Cash.java:284)
	at com.zerocracy.cash.Cash$S.<init>(Cash.java:142)
	at sun.reflect.GeneratedConstructorAccessor672.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:238)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:250)
	at com.zerocracy.stk.pm.staff.roles.assign_role.exec(assign_role.groovy:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	... 48 more

  rate: 40EUR
  flow: Assign role


1781430111 8days "Assign role" (0.23.3)
  role: DEV
  author: yegor256
  channel: zold-ruby
  pid: CAZPZR9FS
  login: emilianodellacasa
  token: slack;CAZPZR9FS;UAZPZGDMW
  rate: 40EUR
```

**Comment by g4s8** [comment]
SHould be fixed

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1337` is not assigned, can't get performer
