### ISSUE TITLE
Error on 'Add to WBS'

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1398]
0crat may fail to add new job to WBS, e.g. this one #1387:
```
java.lang.IllegalStateException: http://datum.zerocracy.com/latest/rules/pm/no-lost-estimates.xsl says: The estimate for job "gh:zerocracy/farm#779" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#683" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#723" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#729" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#762" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#848" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#532" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#770" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#773" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#879" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#926" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#942" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#963" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#1143" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#1145" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#396" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#575" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#876" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#1041" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#1175" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#1002" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#360" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#1242" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#1123" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#1247" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#487" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/datum#315" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#1088" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#721" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#1141" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#1310" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#1016" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#1307" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#1269" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#1142" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#1166" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#1265" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#1163" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#559" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#1167" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/datum#365" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#1169" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#1170" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#1179" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#1343" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#1347" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#1116" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#1180" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#903" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#1185" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#1368" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#1350" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#1369" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/datum#367" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#1371" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#1375" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#1376" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#1037" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#1380" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.; The estimate for job "gh:zerocracy/farm#1386" exists in estimates.xml, but the job is absent in the WBS among 0 jobs.
	at com.zerocracy.farm.ruled.RdRules.check(RdRules.java:129)
	at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
	at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
	at org.cactoos.scalar.And.lambda$null$0(And.java:132)
	at org.cactoos.scalar.And.value(And.java:167)
	at org.cactoos.scalar.And.value(And.java:60)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at com.zerocracy.farm.ruled.RdRules.validate(RdRules.java:104)
	at com.zerocracy.farm.ruled.RdItem.close(RdItem.java:139)
	at com.zerocracy.pm.scope.Wbs.add(Wbs.java:94)
	at com.zerocracy.pm.scope.Wbs$add$5.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
```

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1398` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1398](https://github.com/zerocracy/farm/issues/1398) is now out of scope
