### ISSUE TITLE
Debt can be sent twice via Payapal

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1401]
We can send Paypal payment successfully, but get error in `Notify PMO` about payment, so debt will not be removed from `debts.xml`.

```
java.lang.IllegalStateException: Can't add, claims overflow in PMO, too many items: 102
	at com.zerocracy.pm.Claims.add(Claims.java:128)
	at com.zerocracy.pm.Claims.add(Claims.java:87)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:105)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:136)
	at com.zerocracy.pmo.banks.Paypal.pay(Paypal.java:163)
	at com.zerocracy.pmo.banks.Payroll.pay(Payroll.java:109)
	at com.zerocracy.pmo.banks.Payroll$pay.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:152)
	at com.zerocracy.stk.pmo.debts.pay_all_debts$_exec_closure1.doCall(pay_all_debts.groovy:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by 0crat** [comment]
The job [#1401](https://github.com/zerocracy/farm/issues/1401) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1911234336); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @g4s8[/z](https://www.0crat.com/u/g4s8) is on vacation; this ticket may be delayed; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1401` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.25.5`

**Comment by g4s8** [comment]
It was fixed in https://github.com/zerocracy/farm/commit/8c1982d4e51eaf9095bb4f36bfa17a1d627d9237

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1401](https://github.com/zerocracy/farm/issues/1401) is now out of scope
