### ISSUE TITLE
Error in Votes when elections.xml is empty

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1402]
`VsOverElected` may throw an exception if elections are empty:
```
com.jcabi.xml.NodeNotFoundException: XPath '/summary/winner/text()' not found in '<?xml version="1.0" encoding="UTF-8"?>\uA<summary>..1438..164595974"/>\uA   </total>\uA</summary>\uA': Index (0) is out of bounds (size=0)
    at com.jcabi.xml.ListWrapper.get(ListWrapper.java:162)
    at com.zerocracy.pm.staff.Elections.winner(Elections.java:278)
    at com.zerocracy.pm.staff.votes.VsOverElected.lambda$take$0(VsOverElected.java:65)
    at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
    at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
    at org.cactoos.iterator.Filtered.hasNext(Filtered.java:90)
    at org.cactoos.collection.CollectionOf.lambda$new$0(CollectionOf.java:77)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
    at org.cactoos.collection.CollectionEnvelope.iterator(CollectionEnvelope.java:75)
    at org.cactoos.collection.CollectionEnvelope.iterator(CollectionEnvelope.java:75)
    at org.cactoos.iterable.LengthOf.lambda$new$0(LengthOf.java:50)
    at org.cactoos.scalar.NumberEnvelope.lambda$new$1(NumberEnvelope.java:73)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
    at org.cactoos.scalar.NumberEnvelope.intValue(NumberEnvelope.java:98)
    at com.zerocracy.pm.staff.votes.VsOverElected.take(VsOverElected.java:68)
    at com.zerocracy.pm.staff.votes.VsSafe.take(VsSafe.java:53)
    at com.zerocracy.pm.staff.Elections.elect(Elections.java:147)
    at com.zerocracy.pm.staff.Elections$elect$1.call
    at com.zerocracy.stk.pm.staff.elections.elect_performer.exec(elect_performer.groovy:102)
    at sun.reflect.GeneratedMethodAccessor72.invoke
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:822)
    at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:46)
    at groovy.lang.Script.invokeMethod(Script.java:80)
```

Sentry errors: https://sentry.io/zerocracy/farm/issues/606539121/?query=is:unresolved

**Comment by 0crat** [comment]
The job [#1402](https://github.com/zerocracy/farm/issues/1402) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1941753369); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @g4s8[/z](https://www.0crat.com/u/g4s8) is on vacation; this ticket may be delayed; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
Reproduced and fixed in https://github.com/zerocracy/farm/commit/1b75af0673223035fed243051a66d6e259ecb464

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/1402#issuecomment-404933443))

@g4s8 This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1402](https://github.com/zerocracy/farm/issues/1402) is [in scope](http://www.zerocracy.com/policy.html#14) for 3days
  * The role is `DEV`
  * The job is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8) for [2hr](http://www.zerocracy.com/policy.html#8)
  * @g4s8[/z](https://www.0crat.com/u/g4s8) is on vacation!
  * There is a monetary reward attached
  * @g4s8[/z](https://www.0crat.com/u/g4s8) will get 50% of their hourly rate for this job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @g4s8[/z](https://www.0crat.com/u/g4s8): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%231402%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1402](https://github.com/zerocracy/farm/issues/1402) is now out of scope
