### ISSUE TITLE
Sentry.capture may throw an exception

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1426]
We should refactor exception handling with `Sentry` because `Sentry.capture()` may throw an exception itself:
```
2018-07-13T19:44:22.073092+00:00 app[web.1]: BUILD sentry-pool-1-thread-7 io.sentry.SentryClient.lockdown: The connection to Sentry is currently locked down.
2018-07-13T19:44:22.073095+00:00 app[web.1]: io.sentry.connection.LockedDownException: Dropping an Event due to lockdown: Event{level=WARNING, message='event of type UNKNOWN not handled: com.ullink.slack.simpleslackapi.events.SlackEvent$1@61f18b1c', logger='com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl'}
2018-07-13T19:44:22.073097+00:00 app[web.1]: at io.sentry.connection.AbstractConnection.send(AbstractConnection.java:68)
2018-07-13T19:44:22.073098+00:00 app[web.1]: at io.sentry.connection.AsyncConnection$EventSubmitter.run(AsyncConnection.java:171)
2018-07-13T19:44:22.073100+00:00 app[web.1]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2018-07-13T19:44:22.073102+00:00 app[web.1]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2018-07-13T19:44:22.073103+00:00 app[web.1]: at java.lang.Thread.run(Thread.java:748)
2018-07-13T19:44:22.345314+00:00 app[web.1]: BUILD pool-2-thread-1 com.zerocracy.radars.slack.SlackRadar: Slack connected as @0crat/U9LCGNW1E to January.ai
2018-07-13T19:44:22.347432+00:00 app[web.1]: BUILD Grizzly(2) com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl: event of type UNKNOWN not handled: com.ullink.slack.simpleslackapi.events.SlackEvent$1@61f18b1c
```
it breaks the logic of some classes, e.g. `Terminator`, Slack, Github, Telegram reactions.

We need to wrap it with some class which can initialize it and send events safely:
```java
try {
  Sentry.capture(error);
  // or maybe better client.sendException(error)
  // where client is `SentryClient` which created in constructor with client = Sentry.init()
} catch (Throwable ex) {
  Logger.error(ex);
}
```

Also commit https://github.com/zerocracy/farm/commit/a0766ae54345a36fbfe5f15b67963606c745c44c should be reverted.

**Comment by 0crat** [comment]
Job [#1426](https://github.com/zerocracy/farm/issues/1426) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.25.8`

**Comment by g4s8** [comment]
@rultor release, tag=`0.25.9`

**Comment by g4s8** [comment]
@rultor release, tag=`0.25.9`

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/1426#issuecomment-404951989))

@g4s8 This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1426](https://github.com/zerocracy/farm/issues/1426) is [in scope](http://www.zerocracy.com/policy.html#14) for 53min
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * These users are banned and won't be assigned:
    * @g4s8[/z](https://www.0crat.com/u/g4s8): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%231426%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by g4s8** [comment]
@0crat assign @carlosmiranda

**Comment by 0crat** [comment]
> @0crat assign @carlosmiranda ([here](https://github.com/zerocracy/farm/issues/1426#issuecomment-405021276))

@g4s8 The job [#1426](https://github.com/zerocracy/farm/issues/1426) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1951240210); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.25.10`

**Comment by carlosmiranda** [comment]
@g4s8 see PR #1434

**Comment by carlosmiranda** [comment]
@g4s8 merged #1434, may we close this now?

**Comment by g4s8** [comment]
@carlosmiranda thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1426](https://github.com/zerocracy/farm/issues/1426) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +46 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
