### ISSUE TITLE
Error using Sentry in tests

### ISSUE THREAD

**Issue by paulodamaso** [zerocracy/farm#1522]
I'm getting the following error during test runs:

```
Error creating valid DSN from: 'https://7a4c0d4df4f24c73abfdc02646279d9d@sentry.io/1231395'.
io.sentry.dsn.InvalidDsnException: Invalid DSN, the following properties aren't set '[secret key]'
	at io.sentry.dsn.Dsn.validate(Dsn.java:211)
	at io.sentry.dsn.Dsn.<init>(Dsn.java:65)
	at io.sentry.dsn.Dsn.<init>(Dsn.java:40)
	at io.sentry.SentryClientFactory.resolveDsn(SentryClientFactory.java:73)
	at io.sentry.SentryClientFactory.sentryClient(SentryClientFactory.java:42)
	at io.sentry.SentryClientFactory.sentryClient(SentryClientFactory.java:21)
	at com.zerocracy.SafeSentry.<init>(SafeSentry.java:38)
	at com.zerocracy.farm.sync.Terminator.lambda$killer$1(Terminator.java:142)
	at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
	at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
	at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.func.RunnableOf.run(RunnableOf.java:89)
	at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:190)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:221)
	at java.lang.Thread.run(Thread.java:748)
swallowed exception: io.sentry.dsn.InvalidDsnException: Invalid DSN, the following properties aren't set '[secret key]'
	at io.sentry.dsn.Dsn.validate(Dsn.java:211)
	at io.sentry.dsn.Dsn.<init>(Dsn.java:65)
	at io.sentry.dsn.Dsn.<init>(Dsn.java:40)
	at io.sentry.SentryClientFactory.resolveDsn(SentryClientFactory.java:73)
	at io.sentry.SentryClientFactory.sentryClient(SentryClientFactory.java:42)
	at io.sentry.SentryClientFactory.sentryClient(SentryClientFactory.java:21)
	at com.zerocracy.SafeSentry.<init>(SafeSentry.java:38)
	at com.zerocracy.farm.sync.Terminator.lambda$killer$1(Terminator.java:142)
	at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
	at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
	at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.func.RunnableOf.run(RunnableOf.java:89)
	at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:190)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:221)
	at java.lang.Thread.run(Thread.java:748)
```

Looks like this DSN (`'https://7a4c0d4df4f24c73abfdc02646279d9d@sentry.io/1231395'`) is hardcoded somewhere, but it is neither in the source code nor config files. This message appears in various tests. May be related to #1231 .

**Comment by 0crat** [comment]
Job [#1522](https://github.com/zerocracy/farm/issues/1522) is now in scope, role is `DEV`

**Comment by g4s8** [comment]
@paulodamaso as I remember it was fixed some time ago, but now reproducing again. We should check for `//testing` property in `SafeSentry` and try to send errors to sentry only if there are no `testing` property.

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by g4s8** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zerocracy/farm/issues/1522#issuecomment-410517719))

@g4s8 The job [#1522](https://github.com/zerocracy/farm/issues/1522) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2171264760); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.29.5`

**Comment by g4s8** [comment]
@paulodamaso it was fixed in https://github.com/zerocracy/farm/commit/a27f096ead4f7062eedab0ee342750ac2e227309, also fixed sentry reporting for this bug: #1537 (closing right now to see `NumberFormatException` in logs).

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@cb21d65d-8e2c-4fe6-95d4-1ab04782d785, thread: pool-15-thread-1
java.lang.NumberFormatException[65] java.lang.NumberFormatException: For input string: "2018-08-05T15:46:06.66Z"
```

[0.29.5](https://github.com/zerocracy/farm): Issue: zerocracy/farm#1522, Action: `closed`

**Comment by g4s8** [comment]
@0crat out

**Comment by g4s8** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zerocracy/farm/issues/1522#issuecomment-411549896))

@g4s8 Job `gh:zerocracy/farm#1522` is not assigned, can't get start time

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zerocracy/farm/issues/1522#issuecomment-410533582))

@g4s8 The job [#1522](https://github.com/zerocracy/farm/issues/1522) is now out of scope
