### ISSUE TITLE
cleanup_comments often fails

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1570]
`cleanup_comments` often fails with stacktrace:
```
2018-08-08T21:36:54.630619+00:00 app[web.1]: 404 Not Found [https://api.github.com/repos/jeff/YrFfdagy9phZOIBR6EkB/issues/comments/1]
2018-08-08T21:36:54.630620+00:00 app[web.1]: Server: GitHub.com
2018-08-08T21:36:54.630622+00:00 app[web.1]: Date: Wed, 08 Aug 2018 21:36:54 GMT
2018-08-08T21:36:54.630624+00:00 app[web.1]: Content-Type: application/json; charset=utf-8
2018-08-08T21:36:54.630625+00:00 app[web.1]: Transfer-Encoding: chunked
2018-08-08T21:36:54.630627+00:00 app[web.1]: Status: 404 Not Found
2018-08-08T21:36:54.630628+00:00 app[web.1]: X-RateLimit-Limit: 5000
2018-08-08T21:36:54.630630+00:00 app[web.1]: X-RateLimit-Remaining: 4209
2018-08-08T21:36:54.630632+00:00 app[web.1]: X-RateLimit-Reset: 1533766602
2018-08-08T21:36:54.630634+00:00 app[web.1]: X-GitHub-Media-Type: github.v3
2018-08-08T21:36:54.630636+00:00 app[web.1]: Access-Control-Expose-Headers: ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
2018-08-08T21:36:54.630638+00:00 app[web.1]: Access-Control-Allow-Origin: *
2018-08-08T21:36:54.630640+00:00 app[web.1]: Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
2018-08-08T21:36:54.630641+00:00 app[web.1]: X-Frame-Options: deny
2018-08-08T21:36:54.630643+00:00 app[web.1]: X-Content-Type-Options: nosniff
2018-08-08T21:36:54.630645+00:00 app[web.1]: X-XSS-Protection: 1; mode=block
2018-08-08T21:36:54.630646+00:00 app[web.1]: Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
2018-08-08T21:36:54.630648+00:00 app[web.1]: Content-Security-Policy: default-src 'none'
2018-08-08T21:36:54.630650+00:00 app[web.1]: X-Runtime-Rack: 0.052192
2018-08-08T21:36:54.630652+00:00 app[web.1]: X-GitHub-Request-Id: AD64:4209:1A7FBD:37B3A2:5B6B6276
2018-08-08T21:36:54.630654+00:00 app[web.1]: 
2018-08-08T21:36:54.630656+00:00 app[web.1]: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/issues/comments/#delete-a-comment"}
2018-08-08T21:36:54.630658+00:00 app[web.1]: Expected: HTTP response with status 204
2018-08-08T21:36:54.630659+00:00 app[web.1]: but: was <404 Not Found [https://api.github.com/repos/jeff/YrFfdagy9phZOIBR6EkB/issues/comments/1]
2018-08-08T21:36:54.630661+00:00 app[web.1]: Server: GitHub.com
2018-08-08T21:36:54.630663+00:00 app[web.1]: Date: Wed, 08 Aug 2018 21:36:54 GMT
2018-08-08T21:36:54.630665+00:00 app[web.1]: Content-Type: application/json; charset=utf-8
2018-08-08T21:36:54.630667+00:00 app[web.1]: Transfer-Encoding: chunked
2018-08-08T21:36:54.630668+00:00 app[web.1]: Status: 404 Not Found
2018-08-08T21:36:54.630670+00:00 app[web.1]: X-RateLimit-Limit: 5000
2018-08-08T21:36:54.630672+00:00 app[web.1]: X-RateLimit-Remaining: 4209
2018-08-08T21:36:54.630673+00:00 app[web.1]: X-RateLimit-Reset: 1533766602
2018-08-08T21:36:54.630675+00:00 app[web.1]: X-GitHub-Media-Type: github.v3
2018-08-08T21:36:54.630677+00:00 app[web.1]: Access-Control-Expose-Headers: ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
2018-08-08T21:36:54.630678+00:00 app[web.1]: Access-Control-Allow-Origin: *
2018-08-08T21:36:54.630680+00:00 app[web.1]: Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
2018-08-08T21:36:54.630682+00:00 app[web.1]: X-Frame-Options: deny
2018-08-08T21:36:54.630683+00:00 app[web.1]: X-Content-Type-Options: nosniff
2018-08-08T21:36:54.630685+00:00 app[web.1]: X-XSS-Protection: 1; mode=block
2018-08-08T21:36:54.630686+00:00 app[web.1]: Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
2018-08-08T21:36:54.630688+00:00 app[web.1]: Content-Security-Policy: default-src 'none'
2018-08-08T21:36:54.630690+00:00 app[web.1]: X-Runtime-Rack: 0.052192
2018-08-08T21:36:54.630692+00:00 app[web.1]: X-GitHub-Request-Id: AD64:4209:1A7FBD:37B3A2:5B6B6276
2018-08-08T21:36:54.630693+00:00 app[web.1]: 
2018-08-08T21:36:54.630695+00:00 app[web.1]: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/issues/comments/#delete-a-comment"}>
2018-08-08T21:36:54.630697+00:00 app[web.1]: at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
2018-08-08T21:36:54.630698+00:00 app[web.1]: at com.jcabi.http.response.RestResponse.assertStatus(RestResponse.java:111)
2018-08-08T21:36:54.630700+00:00 app[web.1]: at com.jcabi.github.RtComment.remove_aroundBody4(RtComment.java:107)
2018-08-08T21:36:54.630702+00:00 app[web.1]: at com.jcabi.github.RtComment$AjcClosure5.run(RtComment.java:1)
2018-08-08T21:36:54.630703+00:00 app[web.1]: at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
2018-08-08T21:36:54.630705+00:00 app[web.1]: at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:213)
2018-08-08T21:36:54.630707+00:00 app[web.1]: at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
2018-08-08T21:36:54.630708+00:00 app[web.1]: at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:140)
2018-08-08T21:36:54.630710+00:00 app[web.1]: at com.jcabi.github.RtComment.remove(RtComment.java:105)
2018-08-08T21:36:54.630711+00:00 app[web.1]: at com.jcabi.github.safe.SfComment.remove_aroundBody4(SfComment.java:85)
2018-08-08T21:36:54.630713+00:00 app[web.1]: at com.jcabi.github.safe.SfComment$AjcClosure5.run(SfComment.java:1)
2018-08-08T21:36:54.630714+00:00 app[web.1]: at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
2018-08-08T21:36:54.630716+00:00 app[web.1]: at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:213)
2018-08-08T21:36:54.630718+00:00 app[web.1]: at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
2018-08-08T21:36:54.630720+00:00 app[web.1]: at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:140)
2018-08-08T21:36:54.630721+00:00 app[web.1]: at com.jcabi.github.safe.SfComment.remove(SfComment.java:85)
2018-08-08T21:36:54.630723+00:00 app[web.1]: at com.jcabi.github.Comment$remove.call(Unknown Source)
2018-08-08T21:36:54.630724+00:00 app[web.1]: at com.zerocracy.stk.internal.cleanup_comments$_exec_closure1.doCall(cleanup_comments.groovy:49)
2018-08-08T21:36:54.630726+00:00 app[web.1]: at sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
2018-08-08T21:36:54.630728+00:00 app[web.1]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2018-08-08T21:36:54.630729+00:00 app[web.1]: at java.lang.reflect.Method.invoke(Method.java:498)
2018-08-08T21:36:54.630736+00:00 app[web.1]: at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
2018-08-08T21:36:54.630737+00:00 app[web.1]: at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
2018-08-08T21:36:54.630739+00:00 app[web.1]: at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
2018-08-08T21:36:54.630741+00:00 app[web.1]: at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
2018-08-08T21:36:54.630743+00:00 app[web.1]: at groovy.lang.Closure.call(Closure.java:418)
2018-08-08T21:36:54.630744+00:00 app[web.1]: at groovy.lang.Closure.call(Closure.java:434)
2018-08-08T21:36:54.630746+00:00 app[web.1]: at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2125)
2018-08-08T21:36:54.630748+00:00 app[web.1]: at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2110)
2018-08-08T21:36:54.630750+00:00 app[web.1]: at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2139)
2018-08-08T21:36:54.630751+00:00 app[web.1]: at org.codehaus.groovy.runtime.dgm$161.invoke(Unknown Source)
2018-08-08T21:36:54.630753+00:00 app[web.1]: at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
2018-08-08T21:36:54.630755+00:00 app[web.1]: at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
2018-08-08T21:36:54.630757+00:00 app[web.1]: at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
2018-08-08T21:36:54.630759+00:00 app[web.1]: at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
2018-08-08T21:36:54.630760+00:00 app[web.1]: at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
2018-08-08T21:36:54.630762+00:00 app[web.1]: at com.zerocracy.stk.internal.cleanup_comments.exec(cleanup_comments.groovy:47)

```

**Comment by 0crat** [comment]
Job [#1570](https://github.com/zerocracy/farm/issues/1570) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@0crat assign @paulodamaso

**Comment by paulodamaso** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/1570#issuecomment-416215064))

@paulodamaso This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1570](https://github.com/zerocracy/farm/issues/1570) is [in scope](http://www.zerocracy.com/policy.html#14) for 19days
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * These users are banned and won't be assigned:
    * @g4s8[/z](https://www.0crat.com/u/g4s8): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%231570%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
> @0crat assign @paulodamaso  ([here](https://github.com/zerocracy/farm/issues/1570#issuecomment-416178186))

@g4s8 The job [#1570](https://github.com/zerocracy/farm/issues/1570) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2391323882); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by paulodamaso** [comment]
@g4s8 I've tracked the problem but I'm having difficulties on emulating / creating `error` instances. It creates on `dynamobd`. but I'm getting `java.sql.SQLException: org.h2.jdbc.JdbcSQLException: Table "_61HN4OBK5LIN4SJFE9PG____" not found; SQL statement:
INSERT INTO _61HN4OBK5LIN4SJFE9PG____ (created,location,system) VALUES (?,?,?)`. Is there somehing that I must create or run before testing so it creates these tables needed on dynamo?

**Comment by g4s8** [comment]
@paulodamaso yes, you should use `dynamodb` maven profile during integration tests, it will set up local dynamodb testing instance, see https://dynamodb.jcabi.com/index.html

**Comment by paulodamaso** [comment]
@g4s8 Now something strange started to happen, `java.lang.UnsupportedOperationException: at the moment only EQ operator is supported: LT` when iterating over `Errors`; there was some version change in dynamo lib?

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#1669](https://github.com/zerocracy/farm/issues/1669) is still not solved.

**Comment by paulodamaso** [comment]
@g4s8 Merged, please close

**Comment by paulodamaso** [comment]
@g4s8 ping

**Comment by paulodamaso** [comment]
@0crat wait for closure

**Comment by 0crat** [comment]
> @0crat wait for closure ([here](https://github.com/zerocracy/farm/issues/1570#issuecomment-417540617))

@paulodamaso The impediment for [#1570](https://github.com/zerocracy/farm/issues/1570) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by g4s8** [comment]
@paulodamaso thanks

**Comment by 0crat** [comment]
The job [#1570](https://github.com/zerocracy/farm/issues/1570) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good
