### ISSUE TITLE
Sentry messes and swallows exceptions

### ISSUE THREAD

**Issue by paulodamaso** [zerocracy/farm#1603]
Sentry are messing with exception throwing in tests and sometimes is swallowing them.

For example, the code:
```

final Take take = new TkApp(new PropsFarm(new FkFarm()));
take.act(new RqFake("GET", "/?PsByFlag=PsGithub")).body()


```
Should throw the following exception:

```
java.lang.IllegalStateException: [GET http://www.example.com/?PsByFlag=PsGithub] failed in 4ms: [400] code is not provided by Github
	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:92)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkSslOnly.act(TkSslOnly.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at com.zerocracy.tk.TkAppTest.redirectOnError(TkAppTest.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)

```
 But this exception is swallowed because some sentry config problem (reported in https://github.com/zerocracy/farm/issues/1522, but seems that it's not fixed):

```
Error creating valid DSN from: 'https://7a4c0d4df4f24c73abfdc02646279d9d@sentry.io/1231395'.
io.sentry.dsn.InvalidDsnException: Invalid DSN, the following properties aren't set '[secret key]'

	at io.sentry.dsn.Dsn.validate(Dsn.java:211)
	at io.sentry.dsn.Dsn.<init>(Dsn.java:65)
	at io.sentry.dsn.Dsn.<init>(Dsn.java:40)
	at io.sentry.SentryClientFactory.resolveDsn(SentryClientFactory.java:73)
	at io.sentry.SentryClientFactory.sentryClient(SentryClientFactory.java:42)
	at io.sentry.SentryClientFactory.sentryClient(SentryClientFactory.java:21)
	at com.zerocracy.SafeSentry.<init>(SafeSentry.java:47)
	at com.zerocracy.tk.TkApp.lambda$new$6(TkApp.java:356)
	at org.takes.facets.fallback.FbChain$1.route(FbChain.java:71)
	at org.takes.facets.fallback.FbWrap.route(FbWrap.java:59)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:89)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkSslOnly.act(TkSslOnly.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)

```

Furthermore, these swallowed exceptions are messing test execution, making maven think that there were errors in the build, when there were no errors:
```

Tests run: 441, Failures: 0, Errors: 0, Skipped: 10
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:46 min
[INFO] Finished at: 2018-08-16T19:01:44Z
[INFO] Final Memory: 69M/237M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project farm: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: There was an error in the forked process
```

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#1603](https://github.com/zerocracy/farm/issues/1603) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2290509306); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1603` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@paulodamaso it should be fixed in #1607, can we close?

**Comment by 0crat** [comment]
Job was finished in 15 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#1603](https://github.com/zerocracy/farm/issues/1603) is now out of scope
