### ISSUE TITLE
Telegram "Forbidden: bot was blocked by the user"

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1660]
0crat received `403 Forbidden` error on `notify_in_telegram` script:
```
org.codehaus.groovy.runtime.InvokerInvocationException: org.telegram.telegrambots.exceptions.TelegramApiRequestException: Error sending message: [403] Forbidden: bot was blocked by the user
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:105)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:822)
    at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:46)
    at groovy.lang.Script.invokeMethod(Script.java:80)
    at com.zerocracy.farm.reactive.StkRuntime.process(StkRuntime.java:63)
    at com.zerocracy.farm.StkVerbose.process(StkVerbose.java:59)
    at com.zerocracy.farm.StkSafe.process(StkSafe.java:96)
    at com.zerocracy.farm.reactive.StkSmart.process(StkSmart.java:64)
    at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:80)
    at com.zerocracy.farm.reactive.Brigade.lambda$apply$0(Brigade.java:62)
```
it seems that some users may block 0crat chat. Let's remove telegram link for such users from `people.xml`.

**Comment by 0crat** [comment]
Job [#1660](https://github.com/zerocracy/farm/issues/1660) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
