### ISSUE TITLE
Internal Application Error when opening 0crat on /policy

### ISSUE THREAD

**Issue by filfreire** [zerocracy/farm#1677]
@yegor256 @g4s8 when opening `/policy` path in 0crat.com I expected to be lead to http://www.zerocracy.com/policy.html, instead I get an `IllegalStateException`
```
java.lang.IllegalStateException: [GET https://www.0crat.com/policy] failed in 0ms: [400] query param "i" is mandatory
	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:92)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkSslOnly.act(TkSslOnly.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.http.BkBasic.print(BkBasic.java:108)
	at org.takes.http.BkBasic.accept(BkBasic.java:84)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.takes.HttpException: [400] query param "i" is mandatory
	at org.takes.rq.RqHref$Smart.single(RqHref.java:161)
	at com.zerocracy.tk.TkPolicy.act(TkPolicy.java:38)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:154)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:210)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at com.zerocracy.tk.TkSoftForward.lambda$new$0(TkSoftForward.java:48)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.forward.TkForward.act(TkForward.java:68)
	at org.takes.facets.fork.FkFixed$1.route(FkFixed.java:56)
	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:91)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:108)
	at org.takes.tk.TkGzip$1.act(TkGzip.java:58)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:73)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:86)
	... 14 more
```

see screenshot:
<img width="1149" alt="screen shot 2018-08-31 at 09 14 01" src="https://user-images.githubusercontent.com/11976836/44898223-88b47a80-acfe-11e8-8919-335578055fbd.png">

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by filfreire** [comment]
@yegor256 @g4s8 also notice the build information doesn't seem properly formatted:

```
0.32.1, ${buildNumber}
```

Screenshot:
<img width="466" alt="screen shot 2018-08-31 at 09 18 04" src="https://user-images.githubusercontent.com/11976836/44898303-c913f880-acfe-11e8-927e-31bf446e54ef.png">

**Comment by g4s8** [comment]
@filfreire 0crat.com is actual web-app where you can see profiles, projects etc, zerocracy.com is for static content, like policy, FAQ, etc

@yegor256 please look at this issue, I agree that it's not very comfortable to use two different hosts 0crat.com and zerocracy.com
maybe we can switch to one of them? (or use 0crat.com for webhooks only)

**Comment by yegor256** [comment]
@g4s8 we will still need to have two domains, because they are hosted in different places. They can either be xx.zerocracy.com + zerocracy.com or 0crat.com + zerocracy.com. A year ago I decided to go with the second option.
