### ISSUE TITLE
No author in notify_declined_job

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1683]
Error from [Sentry](https://sentry.io/zerocracy/farm/issues/671678666/?query=is:unresolved):
```
com.jcabi.xml.NodeNotFoundException: XPath 'author/text()' not found in '<claim id="2450919995">\uA   <created>2018-09-02T0..391..b;gh:zerocracy/datum#385</token>\uA</claim>': Index (0) is out of bounds (size=0)
    at com.jcabi.xml.ListWrapper.get(ListWrapper.java:162)
    at com.zerocracy.claims.ClaimIn.author(ClaimIn.java:150)
    at com.zerocracy.claims.ClaimIn$author$8.call
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
    at com.zerocracy.stk.pm.in.orders.notify_declined_job.exec(notify_declined_job.groovy:39)
    at sun.reflect.GeneratedMethodAccessor244.invoke
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:822)
    at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:46)
    at groovy.lang.Script.invokeMethod(Script.java:80)
```

**Comment by 0crat** [comment]
Job [#1683](https://github.com/zerocracy/farm/issues/1683) is now in scope, role is `DEV`
