### ISSUE TITLE
"Resign all roles" has no token in resign_all_roles

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1726]
Repeating error in `resign_all_roles` script (https://sentry.io/zerocracy/farm/issues/666399427/?query=is:unresolved):
```
com.zerocracy.SoftException: You can't remove all architects from the project, see [§34](http://www.zerocracy.com/policy.html#34)
    at com.zerocracy.pm.staff.Roles.resign(Roles.java:209)
    at com.zerocracy.pm.staff.Roles$resign$4.call
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
    at com.zerocracy.stk.pm.staff.roles.resign_all_roles$_exec_closure1.doCall(resign_all_roles.groovy:41)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
    at groovy.lang.Closure.call(Closure.java:418)
    at groovy.lang.Closure.call(Closure.java:434)
    at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2125)
    at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2110)
    at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2151)
    at org.codehaus.groovy.runtime.dgm$163.invoke
    at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
    at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
    at com.zerocracy.stk.pm.staff.roles.resign_all_roles.exec(resign_all_roles.groovy:40)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:822)
    at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:46)
    at groovy.lang.Script.invokeMethod(Script.java:80)
    at com.zerocracy.farm.reactive.StkRuntime.process(StkRuntime.java:63)
    at com.zerocracy.farm.StkVerbose.process(StkVerbose.java:59)
    at com.zerocracy.farm.StkSafe.process(StkSafe.java:96)
    at com.zerocracy.farm.reactive.StkSmart.process(StkSmart.java:64)
    at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:80)
    at com.zerocracy.farm.reactive.Brigade.lambda$apply$0(Brigade.java:62)
    at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
    at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
    at org.cactoos.iterator.Filtered.hasNext(Filtered.java:90)
    at org.cactoos.iterator.LengthOf.lambda$new$0(LengthOf.java:52)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
    at org.cactoos.scalar.NumberEnvelope.doubleValue(NumberEnvelope.java:113)
    at org.cactoos.iterable.LengthOf.lambda$new$0(LengthOf.java:51)
    at org.cactoos.scalar.NumberEnvelope.lambda$new$1(NumberEnvelope.java:73)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
    at org.cactoos.scalar.NumberEnvelope.intValue(NumberEnvelope.java:98)
    at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:65)
    at com.zerocracy.claims.proc.BrigadeProc.exec(BrigadeProc.java:109)
    at com.zerocracy.claims.proc.BrigadeProc.exec(BrigadeProc.java:45)
    at com.zerocracy.claims.proc.CountingProc.exec(CountingProc.java:55)
    at com.zerocracy.claims.proc.CountingProc.exec(CountingProc.java:28)
    at com.zerocracy.claims.proc.FootprintProc.exec(FootprintProc.java:76)
    at com.zerocracy.claims.proc.FootprintProc.exec(FootprintProc.java:32)
    at com.zerocracy.claims.proc.SentryProc.exec(SentryProc.java:66)
    at com.zerocracy.claims.proc.SentryProc.exec(SentryProc.java:29)
    at com.zerocracy.claims.proc.ExpiryProc.exec(ExpiryProc.java:61)
    at com.zerocracy.claims.proc.ExpiryProc.exec(ExpiryProc.java:30)
    at com.zerocracy.claims.proc.MessageMonitorProc.exec(MessageMonitorProc.java:157)
    at com.zerocracy.claims.proc.MessageMonitorProc.exec(MessageMonitorProc.java:52)
    at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
    at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
    at org.cactoos.scalar.And.lambda$null$0(And.java:132)
    at org.cactoos.scalar.And.value(And.java:167)
    at com.zerocracy.claims.proc.AsyncProc.lambda$exec$1(AsyncProc.java:130)
    at com.jcabi.log.VerboseCallable.call(VerboseCallable.java:173)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:221)
    at java.lang.Thread.run(Thread.java:748)
java.lang.IllegalArgumentException: Claim #2681842669 "Resign all roles" has no token in resign_all_roles
    at com.zerocracy.farm.StkSafe.process(StkSafe.java:107)
    at com.zerocracy.farm.reactive.StkSmart.process(StkSmart.java:64)
    at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:80)
    at com.zerocracy.farm.reactive.Brigade.lambda$apply$0(Brigade.java:62)
    at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
    at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
    at org.cactoos.iterator.Filtered.hasNext(Filtered.java:90)
    at org.cactoos.iterator.LengthOf.lambda$new$0(LengthOf.java:52)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
    at org.cactoos.scalar.NumberEnvelope.doubleValue(NumberEnvelope.java:113)
    at org.cactoos.iterable.LengthOf.lambda$new$0(LengthOf.java:51)
    at org.cactoos.scalar.NumberEnvelope.lambda$new$1(NumberEnvelope.java:73)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
    at org.cactoos.scalar.NumberEnvelope.intValue(NumberEnvelope.java:98)
    at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:65)
    at com.zerocracy.claims.proc.BrigadeProc.exec(BrigadeProc.java:109)
    at com.zerocracy.claims.proc.BrigadeProc.exec(BrigadeProc.java:45)
    at com.zerocracy.claims.proc.CountingProc.exec(CountingProc.java:55)
    at com.zerocracy.claims.proc.CountingProc.exec(CountingProc.java:28)
    at com.zerocracy.claims.proc.FootprintProc.exec(FootprintProc.java:76)
    at com.zerocracy.claims.proc.FootprintProc.exec(FootprintProc.java:32)
    at com.zerocracy.claims.proc.SentryProc.exec(SentryProc.java:66)
    at com.zerocracy.claims.proc.SentryProc.exec(SentryProc.java:29)
    at com.zerocracy.claims.proc.ExpiryProc.exec(ExpiryProc.java:61)
    at com.zerocracy.claims.proc.ExpiryProc.exec(ExpiryProc.java:30)
    at com.zerocracy.claims.proc.MessageMonitorProc.exec(MessageMonitorProc.java:157)
    at com.zerocracy.claims.proc.MessageMonitorProc.exec(MessageMonitorProc.java:52)
    at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
    at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
    at org.cactoos.scalar.And.lambda$null$0(And.java:132)
    at org.cactoos.scalar.And.value(And.java:167)
    at com.zerocracy.claims.proc.AsyncProc.lambda$exec$1(AsyncProc.java:130)
    at com.jcabi.log.VerboseCallable.call(VerboseCallable.java:173)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:221)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by 0crat** [comment]
Job [#1726](https://github.com/zerocracy/farm/issues/1726) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
