### ISSUE TITLE
Getting inexplicable error while running bundle tests

### ISSUE THREAD

**Issue by victornoel** [zerocracy/farm#1738]
I'm trying to solve #1162 but when running tests, after doing some changes, I'm getting lots of this error:
```
java.lang.IllegalStateException: com.zerocracy.farm.sync.SyncFarm pool overflow, too many items: 101
	at com.zerocracy.farm.sync.SyncFarm.find(SyncFarm.java:82)
	at com.zerocracy.farm.strict.StrictFarm.find(StrictFarm.java:50)
	at com.zerocracy.farm.props.PropsFarm.lambda$0(PropsFarm.java:90)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at com.zerocracy.farm.guts.Guts.apply(Guts.java:88)
	at com.zerocracy.farm.props.PropsFarm.find(PropsFarm.java:97)
	at com.zerocracy.entry.ExtFarm.lambda$0(ExtFarm.java:52)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at com.zerocracy.farm.guts.Guts.apply(Guts.java:88)
	at com.zerocracy.entry.ExtFarm.find(ExtFarm.java:59)
	at com.zerocracy.pmo.Pmo.lambda$0(Pmo.java:51)
	at org.cactoos.scalar.SolidScalar.lambda$new$0(SolidScalar.java:55)
	at org.cactoos.func.StickyFunc.lambda$new$0(StickyFunc.java:72)
	at org.cactoos.func.StickyBiFunc.apply(StickyBiFunc.java:95)
	at org.cactoos.func.StickyFunc.apply(StickyFunc.java:79)
	at org.cactoos.func.SyncFunc.apply(SyncFunc.java:101)
	at org.cactoos.func.SolidFunc.apply(SolidFunc.java:66)
	at org.cactoos.scalar.SolidScalar.value(SolidScalar.java:61)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at com.zerocracy.pmo.Pmo.acq(Pmo.java:62)
	at com.zerocracy.farm.props.Props.item(Props.java:135)
	at com.zerocracy.farm.props.Props.values(Props.java:122)
	at com.zerocracy.farm.props.Props.has(Props.java:112)
	at com.zerocracy.entry.ExtMongo.value(ExtMongo.java:133)
	at com.zerocracy.claims.Footprint.<init>(Footprint.java:76)
	at com.zerocracy.farm.footprint.FtItem.close(FtItem.java:96)
	at com.zerocracy.claims.ClaimsItem.delete(ClaimsItem.java:223)
	at com.zerocracy.claims.ClaimsItem.take(ClaimsItem.java:172)
	at com.zerocracy.BundlesTest.run(BundlesTest.java:308)
	at com.zerocracy.BundlesTest.oneBundleWorksFine(BundlesTest.java:245)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
```

I have no idea what this means and what is creating this situation.
Could I get an explanation as well as having this improved or documented somewhere?

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by victornoel** [comment]
@g4s8 I understand what is happening, but I don't understand why it is happening. I am just running the `BundlesTest` tests.

I can't seem to reproduce it anymore now... this is maybe because I'm running tests from Eclipse and the `target` directory, containing the tests, is not cleaned in between runs.

I think `BundlesTest` should cleanup the directory before starting a test for a bundle.

**Comment by g4s8** [comment]
> I think BundlesTest should cleanup the directory before starting a test for a bundle.

@victornoel what directory? `target`?

**Comment by victornoel** [comment]
@g4s8 of course not, I was talking about each bundle directory. But I verified and they are already removed. So this idea is moot :)

In the end, right now it works, I just don't know why running `BundlesTest` gave me the error described in description of this issue.
