### ISSUE TITLE
Claim duplicate

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1770]
0crat is trying to process `Ping` claim twice:
```
java.lang.IllegalArgumentException: Claim #4b2db44f-8d77-420b-a137-06fb1ba252c1 (Ping) already exists for C3RUBL5H9
    at com.zerocracy.claims.Footprint.open(Footprint.java:111)
    at com.zerocracy.claims.proc.FootprintProc.exec(FootprintProc.java:68)
    at com.zerocracy.claims.proc.FootprintProc.exec(FootprintProc.java:32)
    at com.zerocracy.claims.proc.SentryProc.exec(SentryProc.java:66)
    at com.zerocracy.claims.proc.SentryProc.exec(SentryProc.java:29)
    at com.zerocracy.claims.proc.ExpiryProc.exec(ExpiryProc.java:61)
    at com.zerocracy.claims.proc.ExpiryProc.exec(ExpiryProc.java:30)
    at com.zerocracy.claims.proc.MessageMonitorProc.exec(MessageMonitorProc.java:157)
    at com.zerocracy.claims.proc.MessageMonitorProc.exec(MessageMonitorProc.java:52)
    at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
    at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
    at org.cactoos.scalar.And.lambda$null$0(And.java:132)
    at org.cactoos.scalar.And.value(And.java:167)
    at com.zerocracy.claims.proc.AsyncProc.lambda$exec$1(AsyncProc.java:144)
    at com.jcabi.log.VerboseCallable.call(VerboseCallable.java:173)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:221)
    at java.lang.Thread.run(Thread.java:748)
```

we tried to it here #1659 by replacing `long` ids with `UUID`s, but it didn't help.

**Comment by 0crat** [comment]
Job [#1770](https://github.com/zerocracy/farm/issues/1770) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
