### ISSUE TITLE
Internal Application Error when authorizing 0crat's access to github account

### ISSUE THREAD

**Issue by bkuzmic** [zerocracy/farm#1781]
When trying to authorize 0crat to have access to my github account, on URL: 
https://github.com/login/oauth/authorize?client_id=f16684efe7f90aae432b&redirect_uri=https%3A%2F%2Fwww.0crat.com%2F%3FPsByFlag%3DPsGithub, I get an `IllegalStateException`:

URL for form submission is: https://www.0crat.com/join-post

And here is the error printed in browser:

```
Internal application error

0.37.5, ${buildNumber}

Please, report it here. We will do our best to fix it as soon as possible. We're very sorry.

java.lang.IllegalStateException: [GET https://www.0crat.com/join-post] failed in 1s: [400] form param "telegram" is mandatory
	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:92)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkSslOnly.act(TkSslOnly.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.http.BkBasic.print(BkBasic.java:108)
	at org.takes.http.BkBasic.accept(BkBasic.java:84)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.takes.HttpException: [400] form param "telegram" is mandatory
	at org.takes.rq.form.RqFormSmart.single(RqFormSmart.java:101)
	at com.zerocracy.tk.TkJoinPost.act(TkJoinPost.java:104)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:210)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at com.zerocracy.tk.TkSoftForward.lambda$new$0(TkSoftForward.java:48)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.forward.TkForward.act(TkForward.java:68)
	at org.takes.facets.fork.FkFixed$1.route(FkFixed.java:56)
	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:109)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:89)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:108)
	at org.takes.tk.TkGzip$1.act(TkGzip.java:58)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:73)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:86)
	... 14 more
```

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@bkuzmic[/z](https://www.0crat.com/u/bkuzmic) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by bkuzmic** [comment]
I guess this issue is connected to the join form. I'm just starting to join so I'm puzzled that I could login and get an account before I was invited to join.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1781` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
