### ISSUE TITLE
Deadlock after linking the project

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1795]
It happens twice with the same steps:
 1. Create and bootstrap the project [OK]
 2. Try to link the project in Slack [OK]
 3. Add 0crat as collaborator [Deadlock]

Some details:
 - error after linking the project:
```
java.lang.IllegalStateException: org.codehaus.groovy.runtime.InvokerInvocationException in com.zerocracy.stk.pm.hooks.add_github_webhook.add_github_webhook
	at com.zerocracy.farm.reactive.StkRuntime.process(StkRuntime.java:76)
	at com.zerocracy.farm.StkTimed.process(StkTimed.java:67)
	at com.zerocracy.farm.StkVerbose.process(StkVerbose.java:59)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:99)
	at com.zerocracy.farm.reactive.StkSmart.process(StkSmart.java:64)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:80)
	at com.zerocracy.farm.reactive.Brigade.lambda$apply$0(Brigade.java:62)
	at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.iterator.Filtered.hasNext(Filtered.java:90)
	at org.cactoos.iterator.LengthOf.lambda$new$0(LengthOf.java:52)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.scalar.NumberEnvelope.doubleValue(NumberEnvelope.java:113)
	at org.cactoos.iterable.LengthOf.lambda$new$0(LengthOf.java:51)
	at org.cactoos.scalar.NumberEnvelope.lambda$new$1(NumberEnvelope.java:73)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.scalar.NumberEnvelope.intValue(NumberEnvelope.java:98)
	at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:65)
	at com.zerocracy.claims.proc.BrigadeProc.exec(BrigadeProc.java:115)
	at com.zerocracy.claims.proc.BrigadeProc.exec(BrigadeProc.java:47)
	at com.zerocracy.claims.proc.CountingProc.exec(CountingProc.java:55)
	at com.zerocracy.claims.proc.CountingProc.exec(CountingProc.java:28)
	at com.zerocracy.claims.proc.FootprintProc.exec(FootprintProc.java:76)
	at com.zerocracy.claims.proc.FootprintProc.exec(FootprintProc.java:32)
	at com.zerocracy.claims.proc.SentryProc.exec(SentryProc.java:66)
	at com.zerocracy.claims.proc.SentryProc.exec(SentryProc.java:29)
	at com.zerocracy.claims.proc.ExpiryProc.exec(ExpiryProc.java:61)
	at com.zerocracy.claims.proc.ExpiryProc.exec(ExpiryProc.java:30)
	at com.zerocracy.claims.proc.MessageMonitorProc.exec(MessageMonitorProc.java:157)
	at com.zerocracy.claims.proc.MessageMonitorProc.exec(MessageMonitorProc.java:52)
	at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
	at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
	at org.cactoos.scalar.And.lambda$null$0(And.java:132)
	at org.cactoos.scalar.And.value(And.java:167)
	at com.zerocracy.claims.proc.AsyncProc.lambda$exec$1(AsyncProc.java:144)
	at com.jcabi.log.VerboseCallable.call(VerboseCallable.java:173)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:221)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.codehaus.groovy.runtime.InvokerInvocationException: java.lang.AssertionError: HTTP response status is not equal to 201:
404 Not Found [https://api.github.com/repos/emilianodellacasa/ruby-asterisk/hooks]
Server: GitHub.com
Date: Wed, 21 Nov 2018 16:29:49 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Status: 404 Not Found
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4423
X-RateLimit-Reset: 1542819793
X-GitHub-Media-Type: github.v3
Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Content-Security-Policy: default-src 'none'
X-GitHub-Request-Id: 8728:1B6B:6DA76F:DACD49:5BF587FD

{"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/hooks/#create-a-hook"}
Expected: HTTP response with status 201
     but: was <404 Not Found [https://api.github.com/repos/emilianodellacasa/ruby-asterisk/hooks]
Server: GitHub.com
Date: Wed, 21 Nov 2018 16:29:49 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Status: 404 Not Found
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4423
X-RateLimit-Reset: 1542819793
X-GitHub-Media-Type: github.v3
Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Content-Security-Policy: default-src 'none'
X-GitHub-Request-Id: 8728:1B6B:6DA76F:DACD49:5BF587FD

{"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/hooks/#create-a-hook"}>
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:105)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:822)
	at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:46)
	at groovy.lang.Script.invokeMethod(Script.java:80)
	at com.zerocracy.farm.reactive.StkRuntime.process(StkRuntime.java:63)
	... 46 more
Caused by: java.lang.AssertionError: HTTP response status is not equal to 201:
404 Not Found [https://api.github.com/repos/emilianodellacasa/ruby-asterisk/hooks]
Server: GitHub.com
Date: Wed, 21 Nov 2018 16:29:49 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Status: 404 Not Found
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4423
X-RateLimit-Reset: 1542819793
X-GitHub-Media-Type: github.v3
Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Content-Security-Policy: default-src 'none'
X-GitHub-Request-Id: 8728:1B6B:6DA76F:DACD49:5BF587FD

{"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/hooks/#create-a-hook"}
Expected: HTTP response with status 201
     but: was <404 Not Found [https://api.github.com/repos/emilianodellacasa/ruby-asterisk/hooks]
Server: GitHub.com
Date: Wed, 21 Nov 2018 16:29:49 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Status: 404 Not Found
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4423
X-RateLimit-Reset: 1542819793
X-GitHub-Media-Type: github.v3
Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Referrer-Policy: origin-when-cross-origin, s
```

 - deadlock stacktrace (this stacktrace for ledger, but it also fails for other items):

```
java.lang.IllegalStateException: Failed to acquire "ledger.xml" in "CE8UGB6NP" in 2min: java.util.concurrent.locks.ReentrantLock@491e4024[Locked by thread BkParallel-0]
	at com.zerocracy.farm.sync.SyncProject.acq(SyncProject.java:76)
	at com.zerocracy.farm.props.PropsProject.acq(PropsProject.java:79)
	at com.zerocracy.farm.strict.StrictProject.acq(StrictProject.java:133)
	at com.zerocracy.farm.footprint.FtProject.acq(FtProject.java:65)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:52)
	at com.zerocracy.claims.proc.SqsProject.acq(SqsProject.java:69)
	at com.zerocracy.pm.cost.Ledger.item(Ledger.java:196)
	at com.zerocracy.pm.cost.Ledger.bootstrap(Ledger.java:149)
	at com.zerocracy.pm.cost.Ledger$bootstrap.call(Unknown Source)
	at com.zerocracy.stk.pm.in.orders.resign_on_delay.exec(resign_on_delay.groovy:35)
	at sun.reflect.GeneratedMethodAccessor53.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:822)
	at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:46)
	at groovy.lang.Script.invokeMethod(Script.java:80)
	at com.zerocracy.farm.reactive.StkRuntime.process(StkRuntime.java:63)
	at com.zerocracy.farm.StkTimed.process(StkTimed.java:67)
	at com.zerocracy.farm.StkVerbose.process(StkVerbose.java:59)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:99)
	at com.zerocracy.farm.reactive.StkSmart.process(StkSmart.java:64)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:80)
	at com.zerocracy.farm.reactive.Brigade.lambda$apply$0(Brigade.java:62)
	at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.iterator.Filtered.hasNext(Filtered.java:90)
	at org.cactoos.iterator.LengthOf.lambda$new$0(LengthOf.java:52)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.scalar.NumberEnvelope.doubleValue(NumberEnvelope.java:113)
	at org.cactoos.iterable.LengthOf.lambda$new$0(LengthOf.java:51)
	at org.cactoos.scalar.NumberEnvelope.lambda$new$1(NumberEnvelope.java:73)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.scalar.NumberEnvelope.intValue(NumberEnvelope.java:98)
	at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:65)
	at com.zerocracy.claims.proc.BrigadeProc.exec(BrigadeProc.java:115)
	at com.zerocracy.claims.proc.BrigadeProc.exec(BrigadeProc.java:47)
	at com.zerocracy.claims.proc.CountingProc.exec(CountingProc.java:55)
	at com.zerocracy.claims.proc.CountingProc.exec(CountingProc.java:28)
	at com.zerocracy.claims.proc.FootprintProc.exec(FootprintProc.java:76)
	at com.zerocracy.claims.proc.FootprintProc.exec(FootprintProc.java:32)
	at com.zerocracy.claims.proc.SentryProc.exec(SentryProc.java:66)
	at com.zerocracy.claims.proc.SentryProc.exec(SentryProc.java:29)
	at com.zerocracy.claims.proc.ExpiryProc.exec(ExpiryProc.java:61)
	at com.zerocracy.claims.proc.ExpiryProc.exec(ExpiryProc.java:30)
	at com.zerocracy.claims.proc.MessageMonitorProc.exec(MessageMonitorProc.java:157)
	at com.zerocracy.claims.proc.MessageMonitorProc.exec(MessageMonitorProc.java:52)
	at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
	at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
	at org.cactoos.scalar.And.lambda$null$0(And.java:132)
	at org.cactoos.scalar.And.value(And.java:167)
	at com.zerocracy.claims.proc.AsyncProc.lambda$exec$1(AsyncProc.java:144)
	at com.jcabi.log.VerboseCallable.call(VerboseCallable.java:173)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:221)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by 0crat** [comment]
Job [#1795](https://github.com/zerocracy/farm/issues/1795) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
