### ISSUE TITLE
0crat doen't validate job with underscore

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1845]
0crat thinks that job name with underscore is not valid, e.g. `gh:zverovich/timeless_is#1`.
Error https://sentry.io/zerocracy/farm/issues/837860383/?query=is%3Aunresolved

```
java.lang.IllegalArgumentException: Failed to transform by net.sf.saxon.TransformerFactoryImpl: [Job name "gh:zverovich/timeless_is#1" is not valid, Processing terminated by xsl:message at line 27 in file:///; SystemID: file:///; Line#: 27; Column#: 6]
    at com.jcabi.xml.XSLDocument.transformInto(XSLDocument.java:400)
    at com.jcabi.xml.XSLDocument.transform(XSLDocument.java:338)
    at com.jcabi.xml.XSLChain.transform(XSLChain.java:74)
    at com.zerocracy.claims.ClaimOut.postTo(ClaimOut.java:122)
    at com.zerocracy.claims.ClaimOut.postTo(ClaimOut.java:136)
    at com.zerocracy.radars.github.ReQuestion.react(ReQuestion.java:62)
    at com.zerocracy.radars.github.ReIfAddressed.react(ReIfAddressed.java:73)
    at com.zerocracy.radars.github.ReNotMine.react(ReNotMine.java:53)
    at com.zerocracy.radars.github.ReSafe.lambda$react$0(ReSafe.java:59)
    at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:84)
    at org.cactoos.func.IoCheckedFunc.lambda$apply$0(IoCheckedFunc.java:59)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:59)
    at com.zerocracy.radars.github.ReSafe.react(ReSafe.java:85)
    at com.zerocracy.radars.github.ReOnComment.send(ReOnComment.java:204)
    at com.zerocracy.radars.github.ReOnComment.react(ReOnComment.java:121)
    at com.zerocracy.radars.github.ReOnReason.react(ReOnReason.java:56)
    at com.zerocracy.radars.github.ReLogged.react(ReLogged.java:53)
    at com.zerocracy.radars.github.RbOnComment.react(RbOnComment.java:60)
    at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:63)
    at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:78)
    at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:66)
    at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:84)
    at org.cactoos.func.IoCheckedFunc.lambda$apply$0(IoCheckedFunc.java:59)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:59)
    at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:111)
    at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:50)
    at com.zerocracy.radars.github.RbDelayed.react(RbDelayed.java:55)
    at com.zerocracy.radars.github.RbAccessible.react(RbAccessible.java:86)
    at com.zerocracy.radars.github.RbSync.react(RbSync.java:48)
    at com.zerocracy.radars.github.RbAsync.lambda$react$0(RbAsync.java:49)
    at org.cactoos.func.AsyncFunc.lambda$apply$0(AsyncFunc.java:120)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1845](https://github.com/zerocracy/farm/issues/1845), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1845` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.40.2`

**Comment by g4s8** [comment]
reproduced and fixed in https://github.com/zerocracy/farm/commit/d938c655712cd08b478bc5fa3ed001b8c1201541

**Comment by 0crat** [comment]
The job [#1845](https://github.com/zerocracy/farm/issues/1845) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
