### ISSUE TITLE
0crat is failing to pay via paypal

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1857]
This is the error for paypal payments:
```
java.io.IOException: PayPal exec status is not COMPLETED: ERROR
    at com.zerocracy.pmo.banks.Paypal.valid(Paypal.java:248)
    at com.zerocracy.pmo.banks.Paypal.pay(Paypal.java:122)
    at com.zerocracy.pmo.banks.Payroll.pay(Payroll.java:116)
    at com.zerocracy.pmo.banks.Payroll$pay.call
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
    at com.zerocracy.stk.pmo.debts.pay_all_debts$_exec_closure1.doCall(pay_all_debts.groovy:72)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
    at groovy.lang.Closure.call(Closure.java:418)
    at groovy.lang.Closure.call(Closure.java:434)
    at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2125)
    at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2110)
    at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2151)
    at org.codehaus.groovy.runtime.dgm$163.invoke
    at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
    at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
    at com.zerocracy.stk.pmo.debts.pay_all_debts.exec(pay_all_debts.groovy:49)
    at sun.reflect.GeneratedMethodAccessor781.invoke
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:822)
    at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:46)
    at groovy.lang.Script.invokeMethod(Script.java:80)
    at com.zerocracy.farm.reactive.StkRuntime.process(StkRuntime.java:63)
    at com.zerocracy.farm.StkTimed.process(StkTimed.java:67)
    at com.zerocracy.farm.StkVerbose.process(StkVerbose.java:59)
    at com.zerocracy.farm.StkSafe.process(StkSafe.java:99)
    at com.zerocracy.farm.reactive.StkSmart.process(StkSmart.java:64)
    at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:80)
    at com.zerocracy.farm.reactive.Brigade.lambda$apply$0(Brigade.java:62)
    at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
    at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
    at org.cactoos.iterator.Filtered.hasNext(Filtered.java:90)
    at org.cactoos.iterator.LengthOf.lambda$new$0(LengthOf.java:52)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
    at org.cactoos.scalar.NumberEnvelope.doubleValue(NumberEnvelope.java:113)
    at org.cactoos.iterable.LengthOf.lambda$new$0(LengthOf.java:51)
    at org.cactoos.scalar.NumberEnvelope.lambda$new$1(NumberEnvelope.java:73)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
    at org.cactoos.scalar.NumberEnvelope.intValue(NumberEnvelope.java:98)
    at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:65)
    at com.zerocracy.claims.proc.BrigadeProc.exec(BrigadeProc.java:115)
    at com.zerocracy.claims.proc.BrigadeProc.exec(BrigadeProc.java:47)
    at com.zerocracy.claims.proc.CountingProc.exec(CountingProc.java:55)
    at com.zerocracy.claims.proc.CountingProc.exec(CountingProc.java:28)
    at com.zerocracy.claims.proc.FootprintProc.exec(FootprintProc.java:76)
    at com.zerocracy.claims.proc.FootprintProc.exec(FootprintProc.java:32)
    at com.zerocracy.claims.proc.SentryProc.exec(SentryProc.java:66)
    at com.zerocracy.claims.proc.SentryProc.exec(SentryProc.java:29)
    at com.zerocracy.claims.proc.ExpiryProc.exec(ExpiryProc.java:61)
    at com.zerocracy.claims.proc.ExpiryProc.exec(ExpiryProc.java:30)
    at com.zerocracy.claims.proc.MessageMonitorProc.exec(MessageMonitorProc.java:157)
    at com.zerocracy.claims.proc.MessageMonitorProc.exec(MessageMonitorProc.java:52)
    at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
    at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
    at org.cactoos.scalar.And.lambda$null$0(And.java:132)
    at org.cactoos.scalar.And.value(And.java:167)
    at com.zerocracy.claims.proc.AsyncProc.lambda$exec$1(AsyncProc.java:144)
    at com.jcabi.log.VerboseCallable.call(VerboseCallable.java:173)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:221)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1857](https://github.com/zerocracy/farm/issues/1857), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1857` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by yegor256** [comment]
@g4s8 works now

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/1857#issuecomment-455756029))

@g4s8 The user @g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#1857](https://github.com/zerocracy/farm/issues/1857), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
