### ISSUE TITLE
Internal application error 2 on board page

### ISSUE THREAD

**Issue by denis-konovalyenko** [zerocracy/farm#1945]
Navigate to the board page and observe the following error:
```
java.lang.IllegalStateException: [GET https://www.0crat.com/board] failed in 6s: failed after 4 attempts
	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)
	at org.takes.facets.fallback.TkFallback.access$100(TkFallback.java:54)
	at org.takes.facets.fallback.TkFallback$2.body(TkFallback.java:202)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsPrint.printBody(RsPrint.java:161)
	at org.takes.rs.RsPrint.print(RsPrint.java:114)
	at org.takes.http.BkBasic.print(BkBasic.java:108)
	at org.takes.http.BkBasic.accept(BkBasic.java:84)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: failed after 4 attempts
	at com.jcabi.http.wire.RetryWire.send(RetryWire.java:95)
	at com.jcabi.http.request.BaseRequest.fetchResponse(BaseRequest.java:355)
	at com.jcabi.http.request.BaseRequest.fetch(BaseRequest.java:270)
	at com.jcabi.github.RtJson.fetch_aroundBody0(RtJson.java:75)
	at com.jcabi.github.RtJson$AjcClosure1.run(RtJson.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:213)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:140)
	at com.jcabi.github.RtJson.fetch(RtJson.java:75)
	at com.jcabi.github.RtRepo.languages_aroundBody34(RtRepo.java:200)
	at com.jcabi.github.RtRepo$AjcClosure35.run(RtRepo.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:213)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:140)
	at com.jcabi.github.RtRepo.languages(RtRepo.java:195)
	at com.zerocracy.tk.TkBoard.languages(TkBoard.java:199)
	at com.zerocracy.tk.TkBoard.source(TkBoard.java:152)
	at com.zerocracy.tk.TkBoard.lambda$null$0(TkBoard.java:100)
	at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
	at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
	at org.cactoos.scalar.And.lambda$null$0(And.java:132)
	at org.cactoos.scalar.And.value(And.java:167)
	at com.zerocracy.tk.TkBoard.lambda$act$1(TkBoard.java:106)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at com.zerocracy.tk.RsPage.lambda$make$0(RsPage.java:123)
	at org.takes.rs.xe.XeChain$2.toXembly(XeChain.java:79)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeChain$2.toXembly(XeChain.java:80)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeAppend$1.toXembly(XeAppend.java:75)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeChain$2.toXembly(XeChain.java:80)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.RsXembly.render(RsXembly.java:147)
	at org.takes.rs.xe.RsXembly.access$000(RsXembly.java:65)
	at org.takes.rs.xe.RsXembly$1.body(RsXembly.java:129)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithoutHeader$1.body(RsWithoutHeader.java:75)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsXslt$1.body(RsXslt.java:113)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.facets.fork.RsFork$1.body(RsFork.java:74)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at com.zerocracy.tk.TkSoftForward$RsSoft$1.body(TkSoftForward.java:93)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.facets.forward.TkForward$Safe.load(TkForward.java:116)
	at org.takes.facets.forward.TkForward$Safe.body(TkForward.java:102)
	at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsGzip.make(RsGzip.java:91)
	at org.takes.rs.RsGzip.body(RsGzip.java:76)
	at org.takes.facets.fork.RsFork$1.body(RsFork.java:74)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithHeaders$1.body(RsWithHeaders.java:78)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.facets.fallback.TkFallback$2.body(TkFallback.java:187)
	... 12 more
```

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue
