### ISSUE TITLE
Failed to delete recharge on fund_by_zold

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1946]
`fund_by_zold` stk falis to delete reacharge, error: https://sentry.io/organizations/zerocracy/issues/934436020/?project=1227515&query=is%3Aunresolved+&statsPeriod=14d&utc=true

```
java.lang.IllegalArgumentException: Recharge CF7JL4282 doesn't exist, can't delete
    at com.zerocracy.pmo.recharge.Recharge.delete(Recharge.java:128)
    at com.zerocracy.pmo.recharge.Recharge$delete.call
    at com.zerocracy.stk.pm.cost.funding.fund_by_zold.exec(fund_by_zold.groovy:74)
    at sun.reflect.GeneratedMethodAccessor162.invoke
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:822)
    at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:46)
    at groovy.lang.Script.invokeMethod(Script.java:80)
```

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1946](https://github.com/zerocracy/farm/issues/1946), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@g4s8 fixed in https://github.com/zerocracy/farm/commit/4c7717ba70f09028c7d6bb296d7babd9f7a53b36

**Comment by 0crat** [comment]
Job [#1946](https://github.com/zerocracy/farm/issues/1946) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#1946](https://github.com/zerocracy/farm/issues/1946) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
