### ISSUE TITLE
You have to pull the wallet first

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1947]
0crat failed to create new invoice to receive ZLD:
https://sentry.io/organizations/zerocracy/issues/934360086/?project=193755
```
IOException: Failed to get invoice; code=500 error=You have to pull the wallet 860261987eb8d2d3 first
    at com.zerocracy.zold.ZldError.raise(ZldError.java:65)
    at com.zerocracy.zold.Zold.invoice(Zold.java:168)
    at com.zerocracy.tk.project.TkFundZold.act(TkFundZold.java:58)
    at com.zerocracy.tk.TkSoftForward.lambda$new$0(TkSoftForward.java:48)
...
(35 additional frame(s) were not displayed)

IllegalStateException: [GET https://www.0crat.com/p/CF7JL4282/zold] failed in 3s: Failed to get invoice; code=500 error=You have to pull the wallet 860261987eb8d2d3 first
    at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)
    at org.takes.facets.fallback.TkFallback.route(TkFallback.java:115)
    at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
    at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
...
(11 additional frame(s) were not displayed)
```
we should pull 0crat wallet before each operation

**Comment by 0crat** [comment]
Job [#1947](https://github.com/zerocracy/farm/issues/1947) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.45.23`

**Comment by g4s8** [comment]
@g4s8 fixed

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1947` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1947](https://github.com/zerocracy/farm/issues/1947) is now out of scope
