### ISSUE TITLE
Fund by zold failed

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1986]
`fund_by_zold` script failed with error (https://sentry.io/organizations/zerocracy/issues/973589879/?project=1227515&query=is%3Aunresolved&statsPeriod=14d&utc=true):
```
groovy.lang.MissingPropertyException: No such property: pid for class: com.zerocracy.stk.pm.cost.funding.fund_by_zold
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:66)
    at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:51)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:310)
    at com.zerocracy.stk.pm.cost.funding.fund_by_zold.exec(fund_by_zold.groovy:89)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:822)
    at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:46)
    at groovy.lang.Script.invokeMethod(Script.java:80)
    at com.zerocracy.farm.reactive.StkRuntime.process(StkRuntime.java:63)
    at com.zerocracy.farm.StkTimed.process(StkTimed.java:67)
    at com.zerocracy.farm.StkVerbose.process(StkVerbose.java:59)
    at com.zerocracy.farm.StkSafe.process(StkSafe.java:99)
    at com.zerocracy.farm.reactive.StkSmart.process(StkSmart.java:64)
    at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:80)
    at com.zerocracy.farm.reactive.Brigade.lambda$apply$0(Brigade.java:62)
    at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
    at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
    at org.cactoos.iterator.Filtered.hasNext(Filtered.java:90)
    at org.cactoos.iterator.LengthOf.lambda$new$0(LengthOf.java:52)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
    at org.cactoos.scalar.NumberEnvelope.doubleValue(NumberEnvelope.java:113)
    at org.cactoos.iterable.LengthOf.lambda$new$0(LengthOf.java:51)
    at org.cactoos.scalar.NumberEnvelope.lambda$new$1(NumberEnvelope.java:73)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
    at org.cactoos.scalar.NumberEnvelope.intValue(NumberEnvelope.java:98)
    at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:65)
    at com.zerocracy.claims.proc.BrigadeProc.exec(BrigadeProc.java:115)
    at com.zerocracy.claims.proc.BrigadeProc.exec(BrigadeProc.java:47)
    at com.zerocracy.claims.proc.CountingProc.exec(CountingProc.java:55)
    at com.zerocracy.claims.proc.CountingProc.exec(CountingProc.java:28)
    at com.zerocracy.claims.proc.FootprintProc.exec(FootprintProc.java:76)
    at com.zerocracy.claims.proc.FootprintProc.exec(FootprintProc.java:32)
    at com.zerocracy.claims.proc.SentryProc.exec(SentryProc.java:66)
    at com.zerocracy.claims.proc.SentryProc.exec(SentryProc.java:29)
    at com.zerocracy.claims.proc.ExpiryProc.exec(ExpiryProc.java:47)
    at com.zerocracy.claims.proc.ExpiryProc.exec(ExpiryProc.java:27)
    at com.zerocracy.claims.proc.MessageMonitorProc.exec(MessageMonitorProc.java:157)
    at com.zerocracy.claims.proc.MessageMonitorProc.exec(MessageMonitorProc.java:52)
    at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
    at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
    at org.cactoos.scalar.And.lambda$null$0(And.java:132)
    at org.cactoos.scalar.And.value(And.java:167)
    at org.cactoos.scalar.And.value(And.java:60)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at com.zerocracy.claims.proc.AsyncSink.exec(AsyncSink.java:121)
    at com.zerocracy.claims.proc.AsyncSink.lambda$execAsync$0(AsyncSink.java:80)
    at com.jcabi.log.VerboseCallable.call(VerboseCallable.java:173)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by 0crat** [comment]
Job [#1986](https://github.com/zerocracy/farm/issues/1986) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@g4s8 fixed in https://github.com/zerocracy/farm/commit/b52b1ff78efd17a2434541a79f3813acaa55a2a1

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1986` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1986](https://github.com/zerocracy/farm/issues/1986) is now out of scope
