### ISSUE TITLE
notify_telegram failed for some text

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#2000]
0crat failed to send some message to Telegram (it seems for jobs in repositories with underscore, not sure).

stacktrace:
```
java.lang.IllegalStateException: org.codehaus.groovy.runtime.InvokerInvocationException in com.zerocracy.stk.pm.comm.notify_telegram
	at com.zerocracy.farm.reactive.StkRuntime.process(StkRuntime.java:76)
	at com.zerocracy.farm.StkTimed.process(StkTimed.java:67)
	at com.zerocracy.farm.StkVerbose.process(StkVerbose.java:59)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:99)
	at com.zerocracy.farm.reactive.StkSmart.process(StkSmart.java:64)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:80)
	at com.zerocracy.farm.reactive.Brigade.lambda$apply$0(Brigade.java:62)
	at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.iterator.Filtered.hasNext(Filtered.java:90)
	at org.cactoos.iterator.LengthOf.lambda$new$0(LengthOf.java:52)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.scalar.NumberEnvelope.doubleValue(NumberEnvelope.java:113)
	at org.cactoos.iterable.LengthOf.lambda$new$0(LengthOf.java:51)
	at org.cactoos.scalar.NumberEnvelope.lambda$new$1(NumberEnvelope.java:73)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.scalar.NumberEnvelope.intValue(NumberEnvelope.java:98)
	at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:65)
	at com.zerocracy.claims.proc.BrigadeProc.exec(BrigadeProc.java:115)
	at com.zerocracy.claims.proc.BrigadeProc.exec(BrigadeProc.java:47)
	at com.zerocracy.claims.proc.CountingProc.exec(CountingProc.java:55)
	at com.zerocracy.claims.proc.CountingProc.exec(CountingProc.java:28)
	at com.zerocracy.claims.proc.FootprintProc.exec(FootprintProc.java:76)
	at com.zerocracy.claims.proc.FootprintProc.exec(FootprintProc.java:32)
	at com.zerocracy.claims.proc.SentryProc.exec(SentryProc.java:66)
	at com.zerocracy.claims.proc.SentryProc.exec(SentryProc.java:29)
	at com.zerocracy.claims.proc.ExpiryProc.exec(ExpiryProc.java:47)
	at com.zerocracy.claims.proc.ExpiryProc.exec(ExpiryProc.java:27)
	at com.zerocracy.claims.proc.MessageMonitorProc.exec(MessageMonitorProc.java:157)
	at com.zerocracy.claims.proc.MessageMonitorProc.exec(MessageMonitorProc.java:52)
	at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
	at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
	at org.cactoos.scalar.And.lambda$null$0(And.java:132)
	at org.cactoos.scalar.And.value(And.java:167)
	at org.cactoos.scalar.And.value(And.java:60)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at com.zerocracy.claims.proc.AsyncSink.exec(AsyncSink.java:121)
	at com.zerocracy.claims.proc.AsyncSink.lambda$execAsync$0(AsyncSink.java:80)
	at com.jcabi.log.VerboseCallable.call(VerboseCallable.java:173)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.codehaus.groovy.runtime.InvokerInvocationException: org.telegram.telegrambots.exceptions.TelegramApiRequestException: Error sending message: [400] Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 93
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:105)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:822)
	at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:46)
	at groovy.lang.Script.invokeMethod(Script.java:80)
	at com.zerocracy.farm.reactive.StkRuntime.process(StkRuntime.java:63)
	... 46 more
Caused by: org.telegram.telegrambots.exceptions.TelegramApiRequestException: Error sending message: [400] Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 93
	at org.telegram.telegrambots.api.methods.send.SendMessage.deserializeResponse(SendMessage.java:170)
	at org.telegram.telegrambots.api.methods.send.SendMessage.deserializeResponse(SendMessage.java:24)
	at org.telegram.telegrambots.bots.DefaultAbsSender.sendApiMethod(DefaultAbsSender.java:690)
	at com.zerocracy.radars.telegram.TmZerocrat.post(TmZerocrat.java:77)
	at com.zerocracy.radars.telegram.TmZerocrat$post.call(Unknown Source)
	at com.zerocracy.stk.pm.comm.notify_telegram$1.exec(notify_telegram.groovy:48)
	at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
	at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
	at org.cactoos.func.RetryFunc.apply(RetryFunc.java:118)
	at org.cactoos.Func$apply.call(Unknown Source)
	at com.zerocracy.stk.pm.comm.notify_telegram.exec(notify_telegram.groovy:41)
	at sun.reflect.GeneratedMethodAccessor152.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	... 53 more
```
message:
```
We just paid you $50.00 (`03adb9ed-6467-4e9c-b0a9-09cf19eb75d9`) for gh:january-ai/restaurant_crawling#14: Order was finished
```

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2000](https://github.com/zerocracy/farm/issues/2000), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
