### ISSUE TITLE
0crat failed to make direct payment

### ISSUE THREAD

**Issue by paulodamaso** [zerocracy/farm#2014]
Trying to wirk around #2013 I've triedy to make a direct payment:

`@0crat pay 120min @paulodamaso`

> @paulodamaso There is an unrecoverable failure on my side. Please, submit it here:
> 
> PID: 4@45146756-cba2-4503-abff-3e6112a9905c, thread: pool-4-thread-2
> com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1: - 1: Duplicate unique value [Direct payment from @paulodamaso at gh:stryvers/life-lens-app#281] declared for identity constraint of element "items".
> 0.46.6: CID: 95494dd1-8f38-4625-beb2-c05944e4821c, Type: "Pay cash"

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
```
java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [Direct payment from @paulodamaso at gh:stryvers/life-lens-app#281] declared for identity constraint of element "items".
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:124)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:95)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:86)
	at com.zerocracy.Xocument.modify(Xocument.java:265)
	at com.zerocracy.pmo.Debts.add(Debts.java:190)
	at com.zerocracy.pmo.Debts.add(Debts.java:173)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrap.invoke(PojoMetaMethodSite.java:213)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:152)
	at com.zerocracy.stk.pm.cost.pay_cash.exec(pay_cash.groovy:106)
	at sun.reflect.GeneratedMethodAccessor87.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:822)
	at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:46)
	at groovy.lang.Script.invokeMethod(Script.java:80)
	at com.zerocracy.farm.reactive.StkRuntime.process(StkRuntime.java:63)
	at com.zerocracy.farm.StkTimed.process(StkTimed.java:67)
	at com.zerocracy.farm.StkVerbose.process(StkVerbose.java:59)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:99)
	at com.zerocracy.farm.reactive.StkSmart.process(StkSmart.java:64)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:80)
	at com.zerocracy.farm.reactive.Brigade.lambda$apply$0(Brigade.java:62)
	at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.iterator.Filtered.hasNext(Filtered.java:90)
	at org.cactoos.iterator.LengthOf.lambda$new$0(LengthOf.java:52)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.scalar.NumberEnvelope.doubleValue(NumberEnvelope.java:113)
	at org.cactoos.iterable.LengthOf.lambda$new$0(LengthOf.java:51)
	at org.cactoos.scalar.NumberEnvelope.lambda$new$1(NumberEnvelope.java:73)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.scalar.NumberEnvelope.intValue(NumberEnvelope.java:98)
	at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:65)
	at com.zerocracy.claims.proc.BrigadeProc.exec(BrigadeProc.java:115)
	at com.zerocracy.claims.proc.BrigadeProc.exec(BrigadeProc.java:47)
	at com.zerocracy.claims.proc.CountingProc.exec(CountingProc.java:55)
	at com.zerocracy.claims.proc.CountingProc.exec(CountingProc.java:28)
	at com.zerocracy.claims.proc.FootprintProc.exec(FootprintProc.java:76)
	at com.zerocracy.claims.proc.FootprintProc.exec(FootprintProc.java:32)
	at com.zerocracy.claims.proc.SentryProc.exec(SentryProc.java:66)
	at com.zerocracy.claims.proc.SentryProc.exec(SentryProc.java:29)
	at com.zerocracy.claims.proc.ExpiryProc.exec(ExpiryProc.java:47)
	at com.zerocracy.claims.proc.ExpiryProc.exec(ExpiryProc.java:27)
	at com.zerocracy.claims.proc.MessageMonitorProc.exec(MessageMonitorProc.java:157)
	at com.zerocracy.claims.proc.MessageMonitorProc.exec(MessageMonitorProc.java:52)
	at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
	at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
	at org.cactoos.scalar.And.lambda$null$0(And.java:132)
	at org.cactoos.scalar.And.value(And.java:167)
	at org.cactoos.scalar.And.value(And.java:60)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at com.zerocracy.claims.proc.AsyncSink.exec(AsyncSink.java:121)
	at com.zerocracy.claims.proc.AsyncSink.lambda$execAsync$0(AsyncSink.java:80)
	at com.jcabi.log.VerboseCallable.call(VerboseCallable.java:173)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
https://www.0crat.com/footprint/GFV03LPPY/48216a54-9893-42e5-916e-67c764617108

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2014](https://github.com/zerocracy/farm/issues/2014), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by g4s8** [comment]
@paulodamaso it seems you've sent two identical direct payments (same amount, from same issue):
> Direct payment from @paulodamaso at gh:stryvers/life-lens-app#281

is it true?

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Job [#2014](https://github.com/zerocracy/farm/issues/2014) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#2014](https://github.com/zerocracy/farm/issues/2014) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
