### ISSUE TITLE
/funded callback doesn't work

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#2019]
It was implemented in #1975, however, it doesn't work. I'm not sure exactly what happens, but I suspect that we should start by creating a unit test for it. At the moment the WTS platform doesn't get any HTTP GET requests from the Farm on Stripe funding events.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@yegor256 sentry error https://sentry.io/organizations/zerocracy/issues/972588501/?project=193755&query=is%3Aunresolved:
```
sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
    at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
    at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
    at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392)
    at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)
    at sun.security.validator.Validator.validate(Validator.java:262)
    at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
    at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
    at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
    at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621)
    at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)
    at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
    at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
    at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
    at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
    at com.jcabi.http.request.JdkRequest$1.send(JdkRequest.java:121)
    at com.jcabi.http.request.BaseRequest.fetchResponse(BaseRequest.java:355)
    at com.jcabi.http.request.BaseRequest.fetch(BaseRequest.java:270)
    at com.jcabi.http.Request$fetch$1.call
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
    at com.zerocracy.stk.pm.cost.funding.notify_wts_on_funded.exec(notify_wts_on_funded.groovy:49)
    at sun.reflect.GeneratedMethodAccessor429.invoke
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:822)
    at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:46)
    at groovy.lang.Script.invokeMethod(Script.java:80)
    at com.zerocracy.farm.reactive.StkRuntime.process(StkRuntime.java:63)
    at com.zerocracy.farm.StkTimed.process(StkTimed.java:67)
    at com.zerocracy.farm.StkVerbose.process(StkVerbose.java:59)
    at com.zerocracy.farm.StkSafe.process(StkSafe.java:99)
    at com.zerocracy.farm.reactive.StkSmart.process(StkSmart.java:64)
    at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:80)
    at com.zerocracy.farm.reactive.Brigade.lambda$apply$0(Brigade.java:62)
    at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
    at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
    at org.cactoos.iterator.Filtered.hasNext(Filtered.java:90)
    at org.cactoos.iterator.LengthOf.lambda$new$0(LengthOf.java:52)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
    at org.cactoos.scalar.NumberEnvelope.doubleValue(NumberEnvelope.java:113)
    at org.cactoos.iterable.LengthOf.lambda$new$0(LengthOf.java:51)
    at org.cactoos.scalar.NumberEnvelope.lambda$new$1(NumberEnvelope.java:73)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
    at org.cactoos.scalar.NumberEnvelope.intValue(NumberEnvelope.java:98)
    at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:65)
    at com.zerocracy.claims.proc.BrigadeProc.exec(BrigadeProc.java:115)
    at com.zerocracy.claims.proc.BrigadeProc.exec(BrigadeProc.java:47)
    at com.zerocracy.claims.proc.CountingProc.exec(CountingProc.java:55)
    at com.zerocracy.claims.proc.CountingProc.exec(CountingProc.java:28)
    at com.zerocracy.claims.proc.FootprintProc.exec(FootprintProc.java:76)
    at com.zerocracy.claims.proc.FootprintProc.exec(FootprintProc.java:32)
    at com.zerocracy.claims.proc.SentryProc.exec(SentryProc.java:66)
    at com.zerocracy.claims.proc.SentryProc.exec(SentryProc.java:29)
    at com.zerocracy.claims.proc.ExpiryProc.exec(ExpiryProc.java:47)
    at com.zerocracy.claims.proc.ExpiryProc.exec(ExpiryProc.java:27)
    at com.zerocracy.claims.proc.MessageMonitorProc.exec(MessageMonitorProc.java:157)
    at com.zerocracy.claims.proc.MessageMonitorProc.exec(MessageMonitorProc.java:52)
    at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
    at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
    at org.cactoos.scalar.And.lambda$null$0(And.java:132)
    at org.cactoos.scalar.And.value(And.java:167)
    at org.cactoos.scalar.And.value(And.java:60)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at com.zerocracy.claims.proc.AsyncSink.exec(AsyncSink.java:121)
    at com.zerocracy.claims.proc.AsyncSink.lambda$execAsync$0(AsyncSink.java:80)
    at com.jcabi.log.VerboseCallable.call(VerboseCallable.java:173)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2019](https://github.com/zerocracy/farm/issues/2019), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by g4s8** [comment]
@rultor release, tag=`0.46.7`

**Comment by yegor256** [comment]
@g4s8 still doesn't work, WTS is not getting calls

**Comment by g4s8** [comment]
@rultor release, tag=`0.46.10`

**Comment by g4s8** [comment]
@rultor release, tag=`0.46.10`

**Comment by g4s8** [comment]
@yegor256 it should be fixed now, also please check https://github.com/zold-io/wts.zold.io/issues/226

**Comment by yegor256** [comment]
@g4s8 works now, thanks!

**Comment by 0crat** [comment]
Job [#2019](https://github.com/zerocracy/farm/issues/2019) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#2019](https://github.com/zerocracy/farm/issues/2019) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
