### ISSUE TITLE
unrecoverable failure Type: "Job milestoned"

### ISSUE THREAD

**Issue by amorenew** [zerocracy/farm#2051]
I have added an issue with a milestone but 0crat gives me the following error in this issue https://github.com/ammaratef45/zold-flutter-client/issues/108

```
PID: 4@62637b42-8780-4988-af20-1984572b8182, thread: pool-5-thread-2
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:V 1.1' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
0.47.3: CID: d7668c3e-5332-4b48-9b98-37c17b60ff42, Type: "Job milestoned"

```

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@amorenew[/z](https://www.0crat.com/u/amorenew) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#2051](https://github.com/zerocracy/farm/issues/2051) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2051](https://github.com/zerocracy/farm/issues/2051), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@0crat assign @loro2

**Comment by 0crat** [comment]
> @0crat assign @loro2 ([here](https://github.com/zerocracy/farm/issues/2051#issuecomment-543815053))

@g4s8 The job [#2051](https://github.com/zerocracy/farm/issues/2051) assigned to @loro2[/z](https://www.0crat.com/u/loro2), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/7687f762-364e-4ba2-92a9-f84c52117ba7); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
> @0crat assign @loro2 ([here](https://github.com/zerocracy/farm/issues/2051#issuecomment-543815053))

@g4s8 There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@5ab6a569-9cde-4946-ad9e-e081a294c41d, thread: PQ-C3NDPUA8L
com.zerocracy.claims.ClaimIn[214] java.lang.IllegalArgumentException: Parameter "age" not found in "Order was canceled" among: [comment, job, issue, repo, cause, _parent_sig, flow, login]
```

[0.50.30](https://github.com/zerocracy/farm): CID: [70af2c94-32bd-40d0-9324-570f7d1f11b6](https://www.0crat.com/footprint/C3NDPUA8L/70af2c94-32bd-40d0-9324-570f7d1f11b6), Type: "Order was canceled"

**Comment by 0crat** [comment]
@0crat[/z](https://www.0crat.com/u/0crat) I see that you unassigned this issue; the order is still assigned to @loro2[/z](https://www.0crat.com/u/loro2) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by loro2** [comment]
@g4s8 Is it possible to get a stacktrace for this error message?

**Comment by loro2** [comment]
> 
> 
> @0crat[/z](https://www.0crat.com/u/0crat) I see that you unassigned this issue; the order is still assigned to @loro2[/z](https://www.0crat.com/u/loro2) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)

@g4s8 also, what is this about?

**Comment by loro2** [comment]
@0crat status

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/zerocracy/farm/issues/2051#issuecomment-544451316); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/2051#issuecomment-544487140))

@g4s8 This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#2051](https://github.com/zerocracy/farm/issues/2051) is [in scope](http://www.zerocracy.com/policy.html#14) for 5mon
  * The role is `DEV`
  * The job is assigned to @loro2[/z](https://www.0crat.com/u/loro2) for [3days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @amorenew[/z](https://www.0crat.com/u/amorenew): This user reported the ticket
    * @g4s8[/z](https://www.0crat.com/u/g4s8): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%232051%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/2051#issuecomment-544451954))

@loro2 This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#2051](https://github.com/zerocracy/farm/issues/2051) is [in scope](http://www.zerocracy.com/policy.html#14) for 5mon
  * The role is `DEV`
  * The job is assigned to @loro2[/z](https://www.0crat.com/u/loro2) for [3days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @amorenew[/z](https://www.0crat.com/u/amorenew): This user reported the ticket
    * @g4s8[/z](https://www.0crat.com/u/g4s8): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%232051%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by g4s8** [comment]
@loro2 sure, [the stacktrace](https://www.0crat.com/footprint/CGC59KB9B/732fda6e-2acc-45aa-b805-77e0678785d5):
```
java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:V 1.1' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:124)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:95)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:86)
	at com.zerocracy.Xocument.modify(Xocument.java:265)
	at com.zerocracy.pm.time.Precedences.add(Precedences.java:95)
	at com.zerocracy.pm.time.Precedences$add$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at com.zerocracy.stk.pm.staff.milestones.update_precedences.exec(update_precedences.groovy:31)
	at sun.reflect.GeneratedMethodAccessor1252.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:822)
	at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:46)
	at groovy.lang.Script.invokeMethod(Script.java:80)
	at com.zerocracy.farm.reactive.StkRuntime.process(StkRuntime.java:63)
	at com.zerocracy.farm.StkTimed.process(StkTimed.java:67)
	at com.zerocracy.farm.StkVerbose.process(StkVerbose.java:59)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:99)
	at com.zerocracy.farm.reactive.StkSmart.process(StkSmart.java:64)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:80)
	at com.zerocracy.farm.reactive.Brigade.lambda$apply$0(Brigade.java:62)
	at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.iterator.Filtered.hasNext(Filtered.java:90)
	at org.cactoos.iterator.LengthOf.lambda$new$0(LengthOf.java:52)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.scalar.NumberEnvelope.doubleValue(NumberEnvelope.java:113)
	at org.cactoos.iterable.LengthOf.lambda$new$0(LengthOf.java:51)
	at org.cactoos.scalar.NumberEnvelope.lambda$new$1(NumberEnvelope.java:73)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.scalar.NumberEnvelope.intValue(NumberEnvelope.java:98)
	at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:65)
	at com.zerocracy.claims.proc.BrigadeProc.exec(BrigadeProc.java:115)
	at com.zerocracy.claims.proc.BrigadeProc.exec(BrigadeProc.java:47)
	at com.zerocracy.claims.proc.CountingProc.exec(CountingProc.java:55)
	at com.zerocracy.claims.proc.CountingProc.exec(CountingProc.java:28)
	at com.zerocracy.claims.proc.FootprintProc.exec(FootprintProc.java:76)
	at com.zerocracy.claims.proc.FootprintProc.exec(FootprintProc.java:32)
	at com.zerocracy.claims.proc.SentryProc.exec(SentryProc.java:66)
	at com.zerocracy.claims.proc.SentryProc.exec(SentryProc.java:29)
	at com.zerocracy.claims.proc.ExpiryProc.exec(ExpiryProc.java:47)
	at com.zerocracy.claims.proc.ExpiryProc.exec(ExpiryProc.java:27)
	at com.zerocracy.claims.proc.MessageMonitorProc.exec(MessageMonitorProc.java:157)
	at com.zerocracy.claims.proc.MessageMonitorProc.exec(MessageMonitorProc.java:52)
	at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
	at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
	at org.cactoos.scalar.And.lambda$null$0(And.java:132)
	at org.cactoos.scalar.And.value(And.java:167)
	at org.cactoos.scalar.And.value(And.java:60)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at com.zerocracy.claims.proc.AsyncSink.exec(AsyncSink.java:121)
	at com.zerocracy.claims.proc.AsyncSink.lambda$execAsync$0(AsyncSink.java:80)
	at com.jcabi.log.VerboseCallable.call(VerboseCallable.java:173)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by loro2** [comment]
Created PR #2189 for this issue

**Comment by loro2** [comment]
@0crat wait #2200

**Comment by 0crat** [comment]
> @0crat wait #2200 ([here](https://github.com/zerocracy/farm/issues/2051#issuecomment-552794143))

@loro2 The impediment for [#2051](https://github.com/zerocracy/farm/issues/2051) was registered successfully by @loro2[/z](https://www.0crat.com/u/loro2)

**Comment by 0pdd** [comment]
@amorenew the puzzle [#2204](https://github.com/zerocracy/farm/issues/2204) is still not solved.

**Comment by loro2** [comment]
@g4s8 I wrote the unit test for this case, how can I get payment for that PR?

**Comment by g4s8** [comment]
@loro2 to get the payment you need to close this ticket by asking its author @amorenew

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @loro2[/z](https://www.0crat.com/u/loro2), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#2051](https://github.com/zerocracy/farm/issues/2051) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @loro2[/z](https://www.0crat.com/u/loro2)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0pdd** [comment]
@amorenew the puzzle [#unknown]() is still not solved.
