### ISSUE TITLE
Zold payment failure reported by 0crat

### ISSUE THREAD

**Issue by samihibrahim** [zerocracy/farm#2098]
As role DEV, after completion of job #354 (https://github.com/stryvers/life-lens-app/issues/354) in zerocracy project GFV03LPPY, the payment failed with the log provided at the end of this issue. This message was received from 0crat bot over telegram. After about 20mins, I received another notification that the debt was received (& it was paid successfully indeed).

```
We are very sorry, but we failed to pay you $10.67 for gh:stryvers/life-lens-app#354: "Failed to pay: Failed to pay via WTS: job=af0c098e-411a-471b-b2dd-7932c3534031 error=WTS::UserError: There are only edge nodes, run 'zold remote update' or use --tolerate-edges
 /app/objects/ops.rb:75:in rescue in pull'
 /app/objects/ops.rb:61:in pull'
 /app/front/frontpay.rb:79:in `block (2 levels) in <top (required)>'
 /app/front/frontjobs.rb:43:in block in job'
 /app/objects/update_job.rb:47:in call'
 /app/objects/versionedjob.rb:40:in `call'
 /app/objects/trackedjob.rb:33:in call'
 /app/objects/safe_job.rb:36:in call'
 /app/objects/asyncjob.rb:44:in `block (2 levels) in call'
 /app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:130:in `block in open'
 /app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:176:in `opensynchronized'
 /app/vendor/bundle/ruby/2.6.0/gems/futex-0.8.6/lib/futex.rb:103:in open'
 /app/objects/async_job.rb:43:in block in call'
 /app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/rubythreadpoolexecutor.rb:348:in `runtask'
 /app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/rubythreadpoolexecutor.rb:337:in `block (3 levels) in createworker'
 /app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/rubythreadpoolexecutor.rb:320:in `loop'
 /app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/rubythreadpoolexecutor.rb:320:in block (2 levels) in create_worker'
 /app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in catch'
 /app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/rubythreadpoolexecutor.rb:319:in `block in createworker'"; this amount was added to the list of payments we owe you; we will try to send them all together very soon; we will keep you informed, see §20 (http://www.zerocracy.com/policy.html#20)the tuition fee $0.93 was deducted and sent to @denis-konovalyenko/z (https://www.0crat.com/u/denis-konovalyenko) (your mentor), according to §45 (http://www.zerocracy.com/policy.html#45)
```

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@samihibrahim[/z](https://www.0crat.com/u/samihibrahim) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@samihibrahim this payment should be added to the debts, check profile page: https://www.0crat.com/u/me to see all debts. 0crat will retry to make failed payment every 1 hour.

**Comment by samihibrahim** [comment]
@g4s8 It was indeed paid successfully after 20mins or so after the error. I have no issue with the payment, I am only reporting this for the sake of the exception received.

**Comment by g4s8** [comment]
@samihibrahim reported it here: https://github.com/zold-io/wts.zold.io/issues/271

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2098` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
