### ISSUE TITLE
Cannot pause project

### ISSUE THREAD

**Issue by paulodamaso** [zerocracy/farm#2128]
0crat is not accepting `pause` command in slack, for pausing the project. I've tried to put the project GFV03LPPY into pause, but 0crat just ignored the command.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@paulodamaso it looks like a connection problem with Slack API, can you please try again this command as a hotfix (I've restarted 0crat to reconnect it to Slack servers)? 

```
FARM Thread-40 com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl: unexpected exception on monitoring thread
java.io.IOException: java.lang.IllegalStateException: Connection is not open.
 at org.glassfish.tyrus.core.TyrusRemoteEndpoint$Basic.processFuture(TyrusRemoteEndpoint.java:173)
 at org.glassfish.tyrus.core.TyrusRemoteEndpoint$Basic.sendText(TyrusRemoteEndpoint.java:103)
 at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl$2.run(SlackWebSocketSessionImpl.java:443)
Caused by: java.lang.IllegalStateException: Connection is not open.
 at org.glassfish.tyrus.container.grizzly.client.GrizzlyWriter.write(GrizzlyWriter.java:75)
 at org.glassfish.tyrus.core.ProtocolHandler.write(ProtocolHandler.java:484)
 at org.glassfish.tyrus.core.ProtocolHandler.send(ProtocolHandler.java:270)
 at org.glassfish.tyrus.core.ProtocolHandler.send(ProtocolHandler.java:266)
 at org.glassfish.tyrus.core.ProtocolHandler.send(ProtocolHandler.java:315)
 at org.glassfish.tyrus.core.TyrusWebSocket.sendText(TyrusWebSocket.java:307)
: at org.glassfish.tyrus.core.TyrusRemoteEndpoint$Basic.sendText(TyrusRemoteEndpoint.java:101)
 ... 1 more
FARM Thread-62 com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl: Connection lost...
FARM Grizzly(1) com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl: event of type UNKNOWN not handled: com.ullink.slack.simpleslackapi.events.SlackEvent$1@2cd6f914
FARM Thread-74 com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl: Connection lost...
FARM Grizzly(2) com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl: event of type UNKNOWN not handled: com.ullink.slack.simpleslackapi.events.SlackEvent$1@2cd6f914
FARM Thread-58 com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl: unexpected exception on monitoring thread
```

**Comment by 0crat** [comment]
Job [#2128](https://github.com/zerocracy/farm/issues/2128) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by paulodamaso** [comment]
@g4s8 It worked. 0crat should detect communication problems with slack or any other provider and notify someone, WDYT?

**Comment by g4s8** [comment]
@rultor release, tag=`0.49.2`
