### ISSUE TITLE
Multiple Telegram bot instances are running

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#2134]
There're multiple Telegram bot instances are running (according to logs), most probably different farm instances are used to access `ExtTelegram`:
```
2019-09-06T10:29:47.858840+00:00 app[web.1]: SEVERE: BOTSESSION
2019-09-06T10:29:47.858843+00:00 app[web.1]: org.telegram.telegrambots.exceptions.TelegramApiRequestException: Error getting updates: [409] Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2019-09-06T10:29:47.858846+00:00 app[web.1]: at org.telegram.telegrambots.api.methods.updates.GetUpdates.deserializeResponse(GetUpdates.java:119)
2019-09-06T10:29:47.858848+00:00 app[web.1]: at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$ReaderThread.getUpdatesFromServer(DefaultBotSession.java:262)
2019-09-06T10:29:47.858850+00:00 app[web.1]: at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$ReaderThread.run(DefaultBotSession.java:191)
2019-09-06T10:29:47.858853+00:00 app[web.1]: 
```

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2134](https://github.com/zerocracy/farm/issues/2134), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2134` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.49.8`

**Comment by g4s8** [comment]
@g4s8 it was fixed in https://github.com/zerocracy/farm/commit/885f2adde0c76b96c521c6e1dc88d451c17ffd21

**Comment by 0crat** [comment]
Job [#2134](https://github.com/zerocracy/farm/issues/2134) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#2134](https://github.com/zerocracy/farm/issues/2134) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
