### ISSUE TITLE
Mongo cleanup timeoutexception

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#2172]
Too many exceptions on `Footprint.cleanup()` in Sentry:
```
b5adf61b-1617-47c3-99dc-561a554718b8 : <?xml version="1.0" encoding="UTF-8"?> <claim id="1f40ea2d-4b38-4925-9bcf-ccc1a0055358"> <created>2019-10-15T00:00:36.505Z</created> <params> <param name="priority">LOW</param> <param name="cause">ceb6231c-b3bd-4302-a5f8-2303d49a9904</param> <param name="_parent_sig">u7TLIWNIdHytoT9dssGdhNls+iQOUp3bdfPDA9QgL4M=</param> <param name="flow">Ping nightly</param> <param name="origin_id">ceb6231c-b3bd-4302-a5f8-2303d49a9904</param> <param name="origin_type">Ping nightly</param> <param name="message">Claim #ceb6231c-b3bd-4302-a5f8-2303d49a9904 in PMO: type="Ping nightly", stakeholder="cleanup_footprint"</param> <param name="stacktrace">com.mongodb.MongoSocketReadTimeoutException: Timeout while receiving message at com.mongodb.internal.connection.InternalStreamConnection.translateReadException(InternalStreamConnection.java:537) at com.mongodb.internal.connection.InternalStreamConnection.receiveMessage(InternalStreamConnection.java:428) at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:289) at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:255) at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:99) at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:444) at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:72) at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:200) at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:269) at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:131) at com.mongodb.operation.MixedBulkWriteOperation.executeCommand(MixedBulkWriteOperation.java:418) at com.mongodb.operation.MixedBulkWriteOperation.executeBulkWriteBatch(MixedBulkWriteOperation.java:256) at com.mongodb.operation.MixedBulkWriteOperation.access$700(MixedBulkWriteOperation.java:67) at com.mongodb.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:200) at com.mongodb.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:191) at com.mongodb.operation.OperationHelper.withReleasableConnection(OperationHelper.java:419) at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:191) at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:67) at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:193) at com.mongodb.client.internal.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:960) at com.mongodb.client.internal.MongoCollectionImpl.executeDelete(MongoCollectionImpl.java:940) at com.mongodb.client.internal.MongoCollectionImpl.deleteMany(MongoCollectionImpl.java:551) at com.mongodb.client.internal.MongoCollectionImpl.deleteMany(MongoCollectionImpl.java:546) at com.zerocracy.claims.Footprint.cleanup(Footprint.java:178) at com.zerocracy.claims.Footprint$cleanup$0.call(Unknown Source) at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128) at com.zerocracy.stk.internal.cleanup_footprint$_exec_closure1.doCall(cleanup_footprint.groovy:35) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98) at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264) at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034) at groovy.lang.Closure.call(Closure.java:418) at groovy.lang.Closure.call(Closure.java:434) at org.codehaus.groovy.runtime.IOGroovyMethods.withCloseable(IOGroovyMethods.java:1630) at org.codehaus.groovy.runtime.NioGroovyMethods.withCloseable(NioGroovyMethods.java:1759) at sun.reflect.GeneratedMethodAccessor213.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.codehaus.groovy.runtime.metaclass.ReflectionMetaMethod.invoke(ReflectionMetaMethod.java:54) at org.codehaus.groovy.runtime.metaclass.NewInstanceMetaMethod.invoke(NewInstanceMetaMethod.java:56) at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274) at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56) at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128) at com.zerocracy.stk.internal.cleanup_footprint.exec(cleanup_footprint.groovy:34) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98) at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225) at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034) at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:822) at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:46) at groovy.lang.Script.invokeMethod(Script.java:80) at com.zerocracy.farm.reactive.StkRuntime.process(StkRuntime.java:63) at com.zerocracy.farm.StkTimed.process(StkTimed.java:67) at com.zerocracy.farm.StkVerbose.process(StkVerbose.java:59) at com.zerocracy.farm.StkSafe.process(StkSafe.java:99) at com.zerocracy.farm.reactive.StkSmart.process(StkSmart.java:64) at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:80) at com.zerocracy.farm.reactive.Brigade.lambda$apply$0(Brigade.java:62) at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58) at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70) at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58) at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59) at org.cactoos.iterator.Filtered.hasNext(Filtered.java:90) at org.cactoos.iterator.LengthOf.lambda$new$0(LengthOf.java:52) at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70) at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58) at org.cactoos.scalar.NumberEnvelope.doubleValue(NumberEnvelope.java:113) at org.cactoos.iterable.LengthOf.lambda$new$0(LengthOf.java:51) at org.cactoos.scalar.NumberEnvelope.lambda$new$1(NumberEnvelope.java:73) at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70) at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58) at org.cactoos.scalar.NumberEnvelope.intValue(NumberEnvelope.java:98) at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:65) at com.zerocracy.claims.proc.BrigadeProc.exec(BrigadeProc.java:115) at com.zerocracy.claims.proc.BrigadeProc.exec(BrigadeProc.java:47) at com.zerocracy.claims.proc.CountingProc.exec(CountingProc.java:55) at com.zerocracy.claims.proc.CountingProc.exec(CountingProc.java:28) at com.zerocracy.claims.proc.FootprintProc.exec(FootprintProc.java:76) at com.zerocracy.claims.proc.FootprintProc.exec(FootprintProc.java:32) at com.zerocracy.claims.proc.SentryProc.exec(SentryProc.java:66) at com.zerocracy.claims.proc.SentryProc.exec(SentryProc.java:29) at com.zerocracy.claims.proc.ExpiryProc.exec(ExpiryProc.java:47) at com.zerocracy.claims.proc.ExpiryProc.exec(ExpiryProc.java:27) at com.zerocracy.claims.proc.MessageMonitorProc.exec(MessageMonitorProc.java:157) at com.zerocracy.claims.proc.MessageMonitorProc.exec(MessageMonitorProc.java:52) at com.zerocracy.claims.proc.ProjectQueue.run(ProjectQueue.java:239) at java.lang.Thread.run(Thread.java:748) Caused by: java.net.SocketTimeoutException: Read timed out at java.net.SocketInputStream.socketRead0(Native Method) at java.net.SocketInputStream.socketRead(
```

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2172](https://github.com/zerocracy/farm/issues/2172), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2172` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
