### ISSUE TITLE
failed to second the application form second time

### ISSUE THREAD

**Issue by eparovyshnaya** [zerocracy/farm#2221]
Dear zerocracy.

I've submitted an application at [join us](https://www.0crat.com/join) 0crat page some time ago and have got no response. According to the instruction given on that very page and in the [policy, p1](http://www.zerocracy.com/policy.html#1), I've repeated the trick (today), and there was the response (the process tries to put my info block into some xml doc while it had been added there on my first application):
 
> Internal application error
> 0.50.40, ${buildNumber}
> 
> Please, report it here. We will do our best to fix it as soon as possible. We're very sorry.
> java.lang.IllegalStateException: [POST https://www.0crat.com/join-post] failed in 4s: 1 error(s) in XML document: -1:-1: Duplicate unique value [eparovyshnaya] declared for identity constraint of element "resumes".
> 	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)
> 	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:115)
> 	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
> 	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
> 	at org.takes.tk.TkWrap.act(TkWrap.java:61)
> 	at org.takes.tk.TkSslOnly.act(TkSslOnly.java:71)
> 	at org.takes.tk.TkWrap.act(TkWrap.java:61)
> 	at org.takes.http.BkBasic.print(BkBasic.java:108)
> 	at org.takes.http.BkBasic.accept(BkBasic.java:84)
> 	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
> 	at org.takes.http.BkWrap.accept(BkWrap.java:52)
> 	at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
> 	at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [eparovyshnaya] declared for identity constraint of element "resumes".
> 	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:124)
> 	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:95)
> 	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:86)
> 	at com.zerocracy.Xocument.modify(Xocument.java:266)
> 	at com.zerocracy.pmo.Resumes.add(Resumes.java:88)
> 	at com.zerocracy.tk.TkJoinPost.act(TkJoinPost.java:113)
> 	at org.takes.facets.fork.FkRegex.route(FkRegex.java:210)

Nevertheless, [0crat](https://www.0crat.com/) now acknoledges me and the [join page](https://www.0crat.com/join) exposes the identification information  I've provided in the application form.

Not sure if the notifications described in the first paragraph of Policy have been triggered.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@eparovyshnaya[/z](https://www.0crat.com/u/eparovyshnaya) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!
