### ISSUE TITLE
can't download ledger XML

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#2301]
I'm getting this:

```
Caused by: java.io.FileNotFoundException: /tmp/0crat8332752662811522102/S3Item5820991407436816280.tmp (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.cactoos.io.InputOf.lambda$new$2(InputOf.java:81)
	at org.cactoos.io.InputOf.stream(InputOf.java:315)
	at org.cactoos.io.TeeInput.stream(TeeInput.java:870)
	at org.cactoos.io.InputAsBytes.asBytes(InputAsBytes.java:79)
	at org.cactoos.io.BytesOf.asBytes(BytesOf.java:336)
	at org.cactoos.text.TextOf.lambda$new$0(TextOf.java:296)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.text.TextOf.asString(TextOf.java:365)
	at com.zerocracy.tk.project.TkXml.act(TkXml.java:59)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:210)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at com.zerocracy.tk.TkSoftForward.lambda$new$0(TkSoftForward.java:48)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.forward.TkForward.act(TkForward.java:68)
	at org.takes.facets.fork.FkFixed$1.route(FkFixed.java:56)
	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:109)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:89)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:108)
```

**Comment by yegor256** [comment]
@g4s8 can you please help?

**Comment by g4s8** [comment]
@0crat assign ruca905

**Comment by 0crat** [comment]
> @0crat assign ruca905 ([here](https://github.com/zerocracy/farm/issues/2301#issuecomment-690922336))

@g4s8 The job [#2301](https://github.com/zerocracy/farm/issues/2301) assigned to @ruca905[/z](https://www.0crat.com/u/ruca905), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/34a7f31c-c8b3-4957-900f-67622ccd4efd); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by ruca905** [comment]
@yegor256 how can i reproduce this error?

**Comment by yegor256** [comment]
@ruca905 I just go to project page, click "Ledger" and then click "Download XML" at the bottom of the page

**Comment by ruca905** [comment]
@yegor256 Is this the page that the link leads to in the repository description?(https://www.0crat.com/) I can't find the "Ledger" button.

**Comment by yegor256** [comment]
@ruca905 you need a project page, something like https://www.0crat.com/a/CT2E6TK9B

**Comment by ruca905** [comment]
@yegor256 Sorry, but I still can't understand what this is about. As I understand the https://www.0crat.com/p/CT2E6TK9B is the page of the project in zero cracy. Then what is this link - https://www.0crat.com/a/CT2E6TK9B. I have not been able to find any documentation on this. I also still don't understand which xml fails to download. There is no download button or Ledger https://www.0crat.com/a/CT2E6TK9B and https://www.0crat.com/p/CT2E6TK9B.

**Comment by yegor256** [comment]
@ruca905 can't you understand the problem by looking at the stacktrace?

**Comment by ruca905** [comment]
@yegor256 I see a file reading error called from the class methods of a new project for me. Of course, I can study these methods and try to fix this bug. But from the experience of reading your blog, I understand that this is a bad idea.
