### ISSUE TITLE
java.io.IOException: Stream closed

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#412]
This happens in the build, time to time (not very often). I believe, it's some concurrency issue, let's investigate and fix.

```
java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/staff/awards/add_award_points.groovy
	at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:125)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:89)
	at com.zerocracy.farm.reactive.StkSmart.process(StkSmart.java:66)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:82)
	at com.zerocracy.farm.reactive.Brigade.lambda$apply$13(Brigade.java:64)
	at com.zerocracy.farm.reactive.Brigade$$Lambda$398/676672206.apply(Unknown Source)
	at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
	at org.cactoos.func.UncheckedFunc$$Lambda$11/1356728614.apply(Unknown Source)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:66)
	at org.cactoos.func.UncheckedBiFunc.apply(UncheckedBiFunc.java:60)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.iterator.Filtered.hasNext(Filtered.java:90)
	at org.cactoos.iterator.LengthOf.lambda$new$0(LengthOf.java:52)
	at org.cactoos.iterator.LengthOf$$Lambda$342/972079084.value(Unknown Source)
	at org.cactoos.scalar.UncheckedScalar.lambda$value$0(UncheckedScalar.java:58)
	at org.cactoos.scalar.UncheckedScalar$$Lambda$10/450003680.apply(Unknown Source)
	at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
	at org.cactoos.func.UncheckedFunc$$Lambda$11/1356728614.apply(Unknown Source)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:66)
	at org.cactoos.func.UncheckedBiFunc.apply(UncheckedBiFunc.java:60)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:59)
	at org.cactoos.scalar.NumberEnvelope.doubleValue(NumberEnvelope.java:111)
	at org.cactoos.iterable.LengthOf.lambda$new$0(LengthOf.java:51)
	at org.cactoos.iterable.LengthOf$$Lambda$341/2145898154.value(Unknown Source)
	at org.cactoos.scalar.NumberEnvelope.lambda$new$1(NumberEnvelope.java:71)
	at org.cactoos.scalar.NumberEnvelope$$Lambda$125/2141497801.value(Unknown Source)
	at org.cactoos.scalar.UncheckedScalar.lambda$value$0(UncheckedScalar.java:58)
	at org.cactoos.scalar.UncheckedScalar$$Lambda$10/450003680.apply(Unknown Source)
	at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
	at org.cactoos.func.UncheckedFunc$$Lambda$11/1356728614.apply(Unknown Source)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:66)
	at org.cactoos.func.UncheckedBiFunc.apply(UncheckedBiFunc.java:60)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:59)
	at org.cactoos.scalar.NumberEnvelope.intValue(NumberEnvelope.java:96)
	at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:67)
	at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:37)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:66)
	at com.zerocracy.farm.reactive.DefaultFlush.process(DefaultFlush.java:97)
	at com.zerocracy.farm.reactive.DefaultFlush.exec(DefaultFlush.java:70)
	at com.zerocracy.farm.reactive.DefaultFlush.exec(DefaultFlush.java:44)
	at com.zerocracy.farm.reactive.AsyncFlush.lambda$exec$26(AsyncFlush.java:118)
	at com.zerocracy.farm.reactive.AsyncFlush$$Lambda$395/680215029.call(Unknown Source)
	at com.jcabi.log.VerboseCallable.call(VerboseCallable.java:173)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:221)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:115)
	... 49 more
Caused by: java.io.UncheckedIOException: java.io.IOException: Stream closed.
	at org.cactoos.func.UncheckedBiFunc.apply(UncheckedBiFunc.java:62)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:59)
	at org.cactoos.io.UncheckedInput.stream(UncheckedInput.java:56)
	at org.cactoos.io.LSInputOf.getByteStream(LSInputOf.java:104)
	at com.sun.org.apache.xerces.internal.util.DOMEntityResolverWrapper.resolveEntity(DOMEntityResolverWrapper.java:127)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.resolveEntity(XMLEntityManager.java:1079)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.resolveDocument(XMLSchemaLoader.java:660)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.findSchemaGrammar(XMLSchemaValidator.java:2437)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1773)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:746)
	at com.sun.org.apache.xerces.internal.jaxp.validation.DOMValidatorHelper.beginNode(DOMValidatorHelper.java:277)
	at com.sun.org.apache.xerces.internal.jaxp.validation.DOMValidatorHelper.validate(DOMValidatorHelper.java:244)
	at com.sun.org.apache.xerces.internal.jaxp.validation.DOMValidatorHelper.validate(DOMValidatorHelper.java:190)
	at com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorImpl.validate(ValidatorImpl.java:109)
	at javax.xml.validation.Validator.validate(Validator.java:124)
	at com.jcabi.xml.StrictXML.validate(StrictXML.java:229)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:95)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:86)
	at com.zerocracy.Xocument.modify(Xocument.java:246)
	at com.zerocracy.pmo.Awards.add(Awards.java:87)
	at com.zerocracy.pmo.Awards$add$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:124)
	at com.zerocracy.stk.pm.staff.awards.add_award_points.exec(add_award_points.groovy:35)
	... 54 more
Caused by: java.io.IOException: Stream closed.
	at java.net.AbstractPlainSocketImpl.available(AbstractPlainSocketImpl.java:465)
	at java.net.SocketInputStream.available(SocketInputStream.java:258)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:353)
	at sun.net.www.MeteredStream.read(MeteredStream.java:134)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3335)
	at org.cactoos.io.TeeInputStream.read(TeeInputStream.java:79)
	at org.cactoos.io.TeeInputStream.read(TeeInputStream.java:73)
	at org.cactoos.io.LengthOf.lambda$new$0(LengthOf.java:72)
	at org.cactoos.io.LengthOf$$Lambda$119/1486458099.value(Unknown Source)
	at org.cactoos.scalar.NumberEnvelope.value(NumberEnvelope.java:116)
	at org.cactoos.io.StickyInput.lambda$new$0(StickyInput.java:64)
	at org.cactoos.io.StickyInput$$Lambda$319/654778994.value(Unknown Source)
	at org.cactoos.scalar.StickyScalar.lambda$new$0(StickyScalar.java:66)
	at org.cactoos.scalar.StickyScalar$$Lambda$13/1392906938.apply(Unknown Source)
	at org.cactoos.func.StickyFunc.lambda$new$0(StickyFunc.java:72)
	at org.cactoos.func.StickyFunc$$Lambda$8/508198356.apply(Unknown Source)
	at org.cactoos.func.StickyBiFunc.apply(StickyBiFunc.java:95)
	at org.cactoos.func.StickyFunc.apply(StickyFunc.java:79)
	at org.cactoos.scalar.StickyScalar.value(StickyScalar.java:72)
	at org.cactoos.scalar.IoCheckedScalar$$Lambda$31/165205057.apply(Unknown Source)
	at org.cactoos.func.IoCheckedFunc.lambda$apply$0(IoCheckedFunc.java:60)
	at org.cactoos.func.IoCheckedFunc$$Lambda$32/1480768445.apply(Unknown Source)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:66)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:61)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:65)
	at org.cactoos.io.StickyInput.stream(StickyInput.java:73)
	at org.cactoos.io.SyncInput.stream(SyncInput.java:72)
	at org.cactoos.io.UncheckedInput$$Lambda$336/637299155.value(Unknown Source)
	at org.cactoos.scalar.UncheckedScalar.lambda$value$0(UncheckedScalar.java:58)
	at org.cactoos.scalar.UncheckedScalar$$Lambda$10/450003680.apply(Unknown Source)
	at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
	at org.cactoos.func.UncheckedFunc$$Lambda$11/1356728614.apply(Unknown Source)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:66)
	at org.cactoos.func.UncheckedBiFunc.apply(UncheckedBiFunc.java:60)
	... 79 more
	Suppressed: java.io.IOException: Stream closed.
		at java.net.AbstractPlainSocketImpl.available(AbstractPlainSocketImpl.java:465)
		at java.net.SocketInputStream.available(SocketInputStream.java:258)
		at java.io.BufferedInputStream.available(BufferedInputStream.java:410)
		at sun.net.www.MeteredStream.available(MeteredStream.java:170)
		at sun.net.www.http.KeepAliveStream.close(KeepAliveStream.java:85)
		at java.io.FilterInputStream.close(FilterInputStream.java:181)
		at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.close(HttpURLConnection.java:3408)
		at org.cactoos.io.TeeInputStream.close(TeeInputStream.java:98)
		at org.cactoos.io.LengthOf.lambda$new$0(LengthOf.java:81)
		... 105 more
```

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by carlosmiranda** [comment]
@0crat status

**Comment by 0crat** [comment]
The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#412](https://github.com/zerocracy/farm/issues/412), please stop working

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/412#issuecomment-363302779))

@carlosmiranda This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#412](https://github.com/zerocracy/farm/issues/412) is [in scope](http://datum.zerocracy.com/pages/policy.html#14) for 21days
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://datum.zerocracy.com/pages/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @yegor256[/z](https://www.0crat.com/u/yegor256): This user reported the ticket

**Comment by 0crat** [comment]
The job [#412](https://github.com/zerocracy/farm/issues/412) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/462209646). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/412#issuecomment-368342455))

@g4s8 The user @g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#412](https://github.com/zerocracy/farm/issues/412), please stop working

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+4615](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#412](https://github.com/zerocracy/farm/issues/412) assigned to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/610876327). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by t-izbassar** [comment]
@0crat refuse

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 points just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by 0crat** [comment]
The job [#412](https://github.com/zerocracy/farm/issues/412) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/720756487). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by amihaiemil** [comment]
@0crat waiting for https://github.com/zerocracy/farm/issues/819, master is broken

**Comment by 0crat** [comment]
> @0crat waiting for https://github.com/zerocracy/farm/issues/819, master is broken ([here](https://github.com/zerocracy/farm/issues/412#issuecomment-373762129))

@amihaiemil The impediment for [#412](https://github.com/zerocracy/farm/issues/412) was registered successfully by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by amihaiemil** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/412#issuecomment-375904995))

@amihaiemil The user @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) resigned from [#412](https://github.com/zerocracy/farm/issues/412), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#412](https://github.com/zerocracy/farm/issues/412) assigned to @neonailol[/z](https://www.0crat.com/u/neonailol), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1161363924); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@neonailol[/z](https://www.0crat.com/u/neonailol) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/412#issuecomment-394974375))

@g4s8 The user @neonailol[/z](https://www.0crat.com/u/neonailol) resigned from [#412](https://github.com/zerocracy/farm/issues/412), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#412](https://github.com/zerocracy/farm/issues/412) assigned to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1591424152); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by proshin-roman** [comment]
@g4s8 I've spent more than 30 minutes and couldn't find any potential problem. As well, the posted stacktrace is too old and doesn't match the current master anymore (I used a version from Jan 16 for investigating). It looks like the problem doesn't occur again - let's close the ticket so that other devs don't waste time on that (just count how many times it was already refused).

**Comment by g4s8** [comment]
@proshin-roman I'd suggest to create unit tests in such cases to prove that bug is not reproducing, this is how you can be paid for these tickets.

What about closing, please try to ask issue author to close it first, only if he's not responding then ask me.

**Comment by 0crat** [comment]
@proshin-roman[/z](https://www.0crat.com/u/proshin-roman) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by proshin-roman** [comment]
@yegor256 ping

**Comment by proshin-roman** [comment]
@0crat waiting for a reaction from issue's author

**Comment by yegor256** [comment]
@proshin-roman thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#412](https://github.com/zerocracy/farm/issues/412) is now out of scope

**Comment by ypshenychka** [comment]
@carlosmiranda According to our [QA Rules](http://www.zerocracy.com/policy.html#42)
>All impediments registered in the ticket have explanations of the reasons and links to related tickets, if necessary

Please add more details to the registered [impediment](https://github.com/zerocracy/farm/issues/412#issuecomment-359309285).

**Comment by carlosmiranda** [comment]
@ypshenychka done

**Comment by ypshenychka** [comment]
@carlosmiranda Thanks!

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
