### ISSUE TITLE
Tests sometimes hangs

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#416]
See #379 PR Rultor messages. It hangs about 2 hours on some tests (different tests), then fails with message:
>'pid' file is absent, something was broken

but I can run these tests on local machine in same branch.

**Comment by g4s8** [comment]
@yegor256 I've got the reason: it's infinity loop started by `BundleTest` if some groovy script has invalid imports:

```
AsyncFlush-1 com.jcabi.log.VerboseCallable: swallowed runtime exception: java.lang.IllegalStateException: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
com/zerocracy/stk/pm/qa/qa_review.groovy: 21: unable to resolve class com.zerocracy.jstk.Project
 @ line 21, column 1.
   import com.zerocracy.jstk.Project
   ^

1 error
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:130)
	at com.zerocracy.farm.reactive.StkSmart.process(StkSmart.java:66)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:82)
	at com.zerocracy.farm.reactive.Brigade.lambda$apply$0(Brigade.java:64)
	at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:66)
	at org.cactoos.func.UncheckedBiFunc.apply(UncheckedBiFunc.java:60)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.iterator.Filtered.hasNext(Filtered.java:90)
	at org.cactoos.iterator.LengthOf.lambda$new$0(LengthOf.java:52)
	at org.cactoos.scalar.UncheckedScalar.lambda$value$0(UncheckedScalar.java:58)
	at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:66)
	at org.cactoos.func.UncheckedBiFunc.apply(UncheckedBiFunc.java:60)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:59)
	at org.cactoos.scalar.NumberEnvelope.doubleValue(NumberEnvelope.java:111)
	at org.cactoos.iterable.LengthOf.lambda$new$0(LengthOf.java:51)
	at org.cactoos.scalar.NumberEnvelope.lambda$new$1(NumberEnvelope.java:71)
	at org.cactoos.scalar.UncheckedScalar.lambda$value$0(UncheckedScalar.java:58)
	at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:66)
	at org.cactoos.func.UncheckedBiFunc.apply(UncheckedBiFunc.java:60)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:59)
	at org.cactoos.scalar.NumberEnvelope.intValue(NumberEnvelope.java:96)
	at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:67)
	at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:37)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:66)
	at com.zerocracy.farm.reactive.DefaultFlush.process(DefaultFlush.java:97)
	at com.zerocracy.farm.reactive.DefaultFlush.exec(DefaultFlush.java:70)
	at com.zerocracy.farm.reactive.DefaultFlush.exec(DefaultFlush.java:44)
	at com.zerocracy.farm.reactive.AsyncFlush.lambda$exec$2(AsyncFlush.java:118)
	at com.jcabi.log.VerboseCallable.call(VerboseCallable.java:173)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:221)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
com/zerocracy/stk/pm/qa/qa_review.groovy: 21: unable to resolve class com.zerocracy.jstk.Project
 @ line 21, column 1.
   import com.zerocracy.jstk.Project
   ^
```

**Comment by yegor256** [comment]
@g4s8 this may be true, thanks. We have to fix the test, it should not hang forever, but should report a problem and fail.

**Comment by 0crat** [comment]
The job [#416](https://github.com/zerocracy/farm/issues/416) assigned to @caarlos0[/z](https://www.0crat.com/u/caarlos0), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/522233815). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@caarlos0[/z](https://www.0crat.com/u/caarlos0) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@caarlos0[/z](https://www.0crat.com/u/caarlos0) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @caarlos0[/z](https://www.0crat.com/u/caarlos0) resigned from [#416](https://github.com/zerocracy/farm/issues/416), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 points just awarded to @caarlos0[/z](https://www.0crat.com/u/caarlos0)

**Comment by amihaiemil** [comment]
@g4s8 Are you sure this is the case? I tried now to mess some imports and the tests in cause are failing fast, nothing hangs. And the rest of the test just keep executing fine.

**Comment by amihaiemil** [comment]
@0crat waiting for answer

**Comment by 0crat** [comment]
> @0crat waiting for answer ([here](https://github.com/zerocracy/farm/issues/416#issuecomment-371923792))

@amihaiemil The impediment for [#416](https://github.com/zerocracy/farm/issues/416) was registered successfully by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by g4s8** [comment]
@amihaiemil you are right, it seems to be fixed, can't reproduce it too.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#416](https://github.com/zerocracy/farm/issues/416) is now out of scope

**Comment by ypshenychka** [comment]
@g4s8 According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Messages in a job [always](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#4-avoid-noiseaddress-your-comments) start with a name of a user they are addressed to.

Please correct your messages ([this](https://github.com/zerocracy/farm/issues/416#issuecomment-358221783) and [this](https://github.com/zerocracy/farm/issues/416#issuecomment-358360172)) by indicating an addressee in the beginning.

**Comment by g4s8** [comment]
@ypshenychka moved these comments to issue details and deleted them.

**Comment by ypshenychka** [comment]
@g4s8 Thanks a lot!

**Comment by ypshenychka** [comment]
@0crat quality bad as no work was done in acope of the issue

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by amihaiemil** [comment]
@ypshenychka @yegor256 Is it a rule that if no PRs were made, the DEV is not paid? Indeed, I did not spend 30min here but still, I had to study the Issue, make the branch, play with the code, see if I couldn't make it hang otherwise -- I spent 10-15min on this.

Could we have a new quality command for these situations? For instance, the DEV could at least be paid the reputation, or be paid half the task's budget? What do you think?

**Comment by ypshenychka** [comment]
@amihaiemil Currently we have such statement in rules:
>The quality of a job is “bad” if any of the following happens (these violations we can’t forgive):
> - The job is closed without a solution provided.
