### ISSUE TITLE
Internal error while verifying with yoti

### ISSUE THREAD

**Issue by t-izbassar** [zerocracy/farm#452]
I've got error when I was trying to verify the details via QR code scanning. In yoti app it is said that details was send. Here is the stacktrace from the 0crat page:

> java.lang.IllegalStateException: [GET http://www.0crat.com/yoti?token=***] failed in 2s: There are 2 parameter(s) but only 1 format argument(s) were provided.
	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:115)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at com.zerocracy.tk.TkSslOnly.act(TkSslOnly.java:59)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.http.BkBasic.print(BkBasic.java:108)
	at org.takes.http.BkBasic.accept(BkBasic.java:84)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: There are 2 parameter(s) but only 1 format argument(s) were provided.
	at com.jcabi.log.PreFormatter.process(PreFormatter.java:154)
	at com.jcabi.log.PreFormatter.<init>(PreFormatter.java:84)
	at com.jcabi.log.Logger.format(Logger.java:127)
	at com.zerocracy.Par.say(Par.java:75)
	at com.zerocracy.tk.profile.TkYoti.act(TkYoti.java:96)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:210)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at org.takes.facets.forward.TkForward.act(TkForward.java:68)
	at org.takes.facets.fork.FkFixed$1.route(FkFixed.java:56)
	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:109)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:89)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:108)
	at org.takes.tk.TkGzip$1.act(TkGzip.java:58)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:73)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:86)
	... 14 more

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by t-izbassar** [comment]
I think the way to reproduce it is to try get new QR code after previous one was expired. That at least what was happening for me. Also, my credentials was verified regardless.

**Comment by 0crat** [comment]
The job [#452](https://github.com/zerocracy/farm/issues/452) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+7950](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@t-izbassar I fixed it, thanks for reporting

**Comment by t-izbassar** [comment]
@yegor256 thanks. I see)

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+7975](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#452](https://github.com/zerocracy/farm/issues/452) is now out of scope

**Comment by 0crat** [comment]
Job [#452](https://github.com/zerocracy/farm/issues/452) was not in scope
