### ISSUE TITLE
500 error on pm/cost/equity

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#468]
Stylesheet transformation error on equity page: https://www.0crat.com/a/C3NDPUA8L?a=pm/cost/equity

```
Internal application error

java.lang.IllegalStateException: [GET http://www.0crat.com/a/C3NDPUA8L?a=pm%2Fcost%2Fequity] failed in 106ms: failed to configure transformer by net.sf.saxon.TransformerFactoryImpl
	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)
	at org.takes.facets.fallback.TkFallback.access$100(TkFallback.java:54)
	at org.takes.facets.fallback.TkFallback$2.body(TkFallback.java:202)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsPrint.printBody(RsPrint.java:161)
	at org.takes.rs.RsPrint.print(RsPrint.java:114)
	at org.takes.http.BkBasic.print(BkBasic.java:108)
	at org.takes.http.BkBasic.accept(BkBasic.java:84)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: failed to configure transformer by net.sf.saxon.TransformerFactoryImpl
	at com.jcabi.xml.XSLDocument.transformInto(XSLDocument.java:401)
	at com.jcabi.xml.XSLDocument.transform(XSLDocument.java:356)
	at com.zerocracy.tk.XeXsl.toXembly(XeXsl.java:113)
	at org.takes.rs.xe.XeChain$2.toXembly(XeChain.java:80)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeChain$2.toXembly(XeChain.java:80)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeChain$2.toXembly(XeChain.java:80)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeAppend$1.toXembly(XeAppend.java:75)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeChain$2.toXembly(XeChain.java:80)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.RsXembly.render(RsXembly.java:147)
	at org.takes.rs.xe.RsXembly.access$000(RsXembly.java:65)
	at org.takes.rs.xe.RsXembly$1.body(RsXembly.java:129)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithoutHeader$1.body(RsWithoutHeader.java:75)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsPrettyXml.make(RsPrettyXml.java:113)
	at org.takes.rs.RsPrettyXml.head(RsPrettyXml.java:94)
	at org.takes.facets.fork.RsFork$1.head(RsFork.java:70)
	at org.takes.rs.RsWrap.head(RsWrap.java:60)
	at org.takes.rs.RsWrap.head(RsWrap.java:60)
	at org.takes.facets.forward.TkForward$Safe.load(TkForward.java:115)
	at org.takes.facets.forward.TkForward$Safe.body(TkForward.java:102)
	at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsGzip.make(RsGzip.java:91)
	at org.takes.rs.RsGzip.body(RsGzip.java:76)
	at org.takes.facets.fork.RsFork$1.body(RsFork.java:74)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithHeaders$1.body(RsWithHeaders.java:78)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.facets.fallback.TkFallback$2.body(TkFallback.java:187)
	... 12 more
Caused by: javax.xml.transform.TransformerConfigurationException: Failed to compile stylesheet. 1 error detected.
	at net.sf.saxon.PreparedStylesheet.prepare(PreparedStylesheet.java:176)
	at net.sf.saxon.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:139)
	at net.sf.saxon.TransformerFactoryImpl.newTransformer(TransformerFactoryImpl.java:91)
	at com.jcabi.xml.XSLDocument.transformInto(XSLDocument.java:390)
	... 54 more
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#468](https://github.com/zerocracy/farm/issues/468) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by yegor256** [comment]
@g4s8 this is what I see in logs:

```
com.jcabi.xml.XSLDocument$1: #fatalError(): SequenceType syntax error at char 0 in {number}:
2018-01-25T20:06:44.661941+00:00 app[web.1]:     There is no imported schema for the null namespace; SystemID: http://datum.zerocracy.com/latest/xsl/pm/cost/equity.xsl; Line#: 110; Column#: 81
```

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+3520](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+8285](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/468#issuecomment-360695901))

@yegor256 This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#468](https://github.com/zerocracy/farm/issues/468) is [in scope](http://datum.zerocracy.com/pages/policy.html#14) for 4min
  * The role is `DEV`
  * The job is assigned to @yegor256[/z](https://www.0crat.com/u/yegor256) for 3min
  * The [budget](http://datum.zerocracy.com/pages/policy.html#4) is 30 minutes
  * These users are banned and won't be assigned:
    @g4s8[/z](https://www.0crat.com/u/g4s8): This user reported the ticket
  * There is no monetary reward attached, it's a [free](http://datum.zerocracy.com/pages/policy.html#2) job
  * The job doesn't have any [impediments](http://datum.zerocracy.com/pages/policy.html#9)

**Comment by yegor256** [comment]
@g4s8 I will continue once https://github.com/zerocracy/datum/issues/255 is fixed

**Comment by yegor256** [comment]
@0crat hold

**Comment by 0crat** [comment]
> @0crat hold ([here](https://github.com/zerocracy/farm/issues/468#issuecomment-360759189))

@yegor256 The impediment for [#468](https://github.com/zerocracy/farm/issues/468) was registered successfully by @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/468#issuecomment-360762104))

@yegor256 This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#468](https://github.com/zerocracy/farm/issues/468) is [in scope](http://datum.zerocracy.com/pages/policy.html#14) for 5hr
  * The role is `DEV`
  * The job is assigned to @yegor256[/z](https://www.0crat.com/u/yegor256) for [5hr](http://datum.zerocracy.com/pages/policy.html#8)
  * The [budget](http://datum.zerocracy.com/pages/policy.html#4) is 30 minutes
  * These users are banned and won't be assigned:
    * @g4s8[/z](https://www.0crat.com/u/g4s8): This user reported the ticket
  * There is no monetary reward attached, it's a [free](http://datum.zerocracy.com/pages/policy.html#2) job
  * The job has an [impediment](http://datum.zerocracy.com/pages/policy.html#9)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
@0crat hold

**Comment by 0crat** [comment]
> @0crat hold ([here](https://github.com/zerocracy/farm/issues/468#issuecomment-361930090))

@yegor256 Job [#468](https://github.com/zerocracy/farm/issues/468) is already on hold

**Comment by g4s8** [comment]
@yegor256 it's working now, thanks

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#468](https://github.com/zerocracy/farm/issues/468) is now out of scope
