### ISSUE TITLE
500 error for PMO

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#483]
Got `Internal application error` error for this page: https://www.0crat.com/p/PMO
```
java.lang.IllegalStateException: [GET http://www.0crat.com/p/PMO] failed in 53ms: File "roles.xml" is not accessible in "PMO"
	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)
	at org.takes.facets.fallback.TkFallback.access$100(TkFallback.java:54)
	at org.takes.facets.fallback.TkFallback$2.body(TkFallback.java:202)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsPrint.printBody(RsPrint.java:161)
	at org.takes.rs.RsPrint.print(RsPrint.java:114)
	at org.takes.http.BkBasic.print(BkBasic.java:108)
	at org.takes.http.BkBasic.accept(BkBasic.java:84)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: File "roles.xml" is not accessible in "PMO"
	at com.zerocracy.farm.strict.StrictProject.acq(StrictProject.java:107)
	at com.zerocracy.farm.props.PropsProject.acq(PropsProject.java:78)
	at com.zerocracy.farm.footprint.FtProject.acq(FtProject.java:67)
	at com.zerocracy.farm.uplinked.UplinkedProject.lambda$acq$4(UplinkedProject.java:99)
	at org.cactoos.scalar.Ternary.value(Ternary.java:123)
	at org.cactoos.func.IoCheckedFunc.lambda$apply$0(IoCheckedFunc.java:60)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:66)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:61)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:65)
	at com.zerocracy.farm.uplinked.UplinkedProject.acq(UplinkedProject.java:101)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:62)
	at com.zerocracy.pm.staff.Roles.item(Roles.java:353)
	at com.zerocracy.pm.staff.Roles.bootstrap(Roles.java:73)
	at com.zerocracy.tk.project.RqProject.lambda$new$0(RqProject.java:75)
	at org.cactoos.scalar.SolidScalar.lambda$new$0(SolidScalar.java:55)
	at org.cactoos.func.StickyFunc.lambda$new$0(StickyFunc.java:72)
	at org.cactoos.func.StickyBiFunc.apply(StickyBiFunc.java:95)
	at org.cactoos.func.StickyFunc.apply(StickyFunc.java:79)
	at org.cactoos.func.SyncFunc.apply(SyncFunc.java:101)
	at org.cactoos.func.SolidFunc.apply(SolidFunc.java:66)
	at org.cactoos.scalar.SolidScalar.value(SolidScalar.java:61)
	at org.cactoos.func.IoCheckedFunc.lambda$apply$0(IoCheckedFunc.java:60)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:66)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:61)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:65)
	at com.zerocracy.tk.project.RqProject.pid(RqProject.java:91)
	at com.zerocracy.tk.project.TkProject.lambda$act$6(TkProject.java:76)
	at org.cactoos.func.IoCheckedFunc.lambda$apply$0(IoCheckedFunc.java:60)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:66)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:61)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:65)
	at com.zerocracy.tk.RsPage.lambda$make$0(RsPage.java:121)
	at org.takes.rs.xe.XeChain$2.toXembly(XeChain.java:79)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeChain$2.toXembly(XeChain.java:80)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeAppend$1.toXembly(XeAppend.java:75)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeChain$2.toXembly(XeChain.java:80)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.RsXembly.render(RsXembly.java:147)
	at org.takes.rs.xe.RsXembly.access$000(RsXembly.java:65)
	at org.takes.rs.xe.RsXembly$1.body(RsXembly.java:129)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithoutHeader$1.body(RsWithoutHeader.java:75)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsPrettyXml.make(RsPrettyXml.java:113)
	at org.takes.rs.RsPrettyXml.head(RsPrettyXml.java:94)
	at org.takes.facets.fork.RsFork$1.head(RsFork.java:70)
	at org.takes.rs.RsWrap.head(RsWrap.java:60)
	at org.takes.rs.RsWrap.head(RsWrap.java:60)
	at org.takes.facets.forward.TkForward$Safe.load(TkForward.java:115)
	at org.takes.facets.forward.TkForward$Safe.body(TkForward.java:102)
	at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsGzip.make(RsGzip.java:91)
	at org.takes.rs.RsGzip.body(RsGzip.java:76)
	at org.takes.facets.fork.RsFork$1.body(RsFork.java:74)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithHeaders$1.body(RsWithHeaders.java:78)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.facets.fallback.TkFallback$2.body(TkFallback.java:187)
	... 12 more
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#483](https://github.com/zerocracy/farm/issues/483) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+3640](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+8665](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@g4s8 it was reproduced and fixed: f93f4cc32c0b3742b410a29bd7ecbacc4acae833 and 528b532d49054ff56a3363c1c57056b473e5ee2e

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@yegor256 thanks

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9170](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#483](https://github.com/zerocracy/farm/issues/483) is now out of scope
