### ISSUE TITLE
0crat telegram bot crashes after an attempt to apply to a project

### ISSUE THREAD

**Issue by driver733** [zerocracy/farm#491]
apply C7JGJ00DP $16

```
I can't do it for technical reasons, I'm very sorry.  If you don't know what to do,  submit this error as a ticket  here: 

 1.0-SNAPSHOT 37c3b5d1 2018-01-29T17:43:01
IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pmo/profile/apply_to_project.groovy
java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pmo/profile/apply_to_project.groovy
 at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:125)
 at com.zerocracy.farm.StkSafe.process(StkSafe.java:89)
 at com.zerocracy.farm.reactive.StkSmart.process(StkSmart.java:66)
 at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:83)
 at com.zerocracy.farm.reactive.Brigade.lambda$apply$0(Brigade.java:65)
 at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
 at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:66)
 at org.cactoos.func.UncheckedBiFunc.apply(UncheckedBiFunc.java:60)
 at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
 at org.cactoos.iterator.Filtered.hasNext(Filtered.java:90)
 at org.cactoos.iterator.LengthOf.lambda$new$0(LengthOf.java:52)
 at org.cactoos.scalar.UncheckedScalar.lambda$value$0(UncheckedScalar.java:58)
 at org.cactoos.func.UncheckedFunc.lambda$apply$0(Unchec... 
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@driver733 can you please try again? It seems to be a temporary issue.

**Comment by driver733** [comment]
@yegor256 I have just tried it again and 0crat threw off the exact same error.

**Comment by driver733** [comment]
```
apply C7JGJ00DP $16

I can't do it for technical reasons, I'm very sorry.  If you don't know what to do,  submit this error as a ticket  here: 

 1.0-SNAPSHOT 3ec53982 2018-01-29T20:57:44
IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pmo/profile/apply_to_project.groovy
java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pmo/profile/apply_to_project.groovy
 at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:125)
 at com.zerocracy.farm.StkSafe.process(StkSafe.java:89)
 at com.zerocracy.farm.reactive.StkSmart.process(StkSmart.java:66)
 at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:83)
 at com.zerocracy.farm.reactive.Brigade.lambda$apply$0(Brigade.java:65)
 at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
 at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:66)
 at org.cactoos.func.UncheckedBiFunc.apply(UncheckedBiFunc.java:60)
 at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
 at org.cactoos.iterator.Filtered.hasNext(Filtered.java:90)
 at org.cactoos.iterator.LengthOf.lambda$new$0(LengthOf.java:52)
 at org.cactoos.scalar.UncheckedScalar.lambda$value$0(UncheckedScalar.java:58)
 at org.cactoos.func.UncheckedFunc.lambda$apply$0(Unchec... 
```

**Comment by yegor256** [comment]
@driver733 fixed, should work fine now

**Comment by driver733** [comment]
@yegor256, thank you!

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#491` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#491](https://github.com/zerocracy/farm/issues/491) was not in scope
