### ISSUE TITLE
Can't see job status

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#509]
Status command throws an error: https://github.com/zerocracy/farm/issues/492#issuecomment-362591737
```
IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/check_job_status.groovy
java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/check_job_status.groovy
	at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:125)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:89)
	at com.zerocracy.farm.reactive.StkSmart.process(StkSmart.java:66)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:82)
	at com.zerocracy.farm.reactive.Brigade.lambda$apply$0(Brigade.java:64)
	at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.iterator.Filtered.hasNext(Filtered.java:90)
	at org.cactoos.iterator.LengthOf.lambda$new$0(LengthOf.java:52)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/farm/issues/509#issuecomment-362613172))

@yegor256 This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#509](https://github.com/zerocracy/farm/issues/509) is not in scope

**Comment by yegor256** [comment]
@g4s8 fixed, thanks

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#509` is not assigned, can't get start time

**Comment by g4s8** [comment]
@yegor256 why did you not add this and #507 jobs to WBS before fixed them?

**Comment by 0crat** [comment]
Job [#509](https://github.com/zerocracy/farm/issues/509) was not in scope

**Comment by yegor256** [comment]
@g4s8 it was rather small, so I decided to treat it as a minor bug. It's always up to a project architect, which ticket to register officially and which one to "ignore".
