### ISSUE TITLE
0crat failed to deliver a payment

### ISSUE THREAD

**Issue by neonailol** [zerocracy/farm#538]
https://github.com/yegor256/takes/issues/779#issuecomment-364417159

```log
 1.0-SNAPSHOT 28f476b8 2018-02-09T12:00:38
IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/cost/make_payment.groovy
java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/cost/make_payment.groovy
	at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:125)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:89)
	at com.zerocracy.farm.reactive.StkSmart.process(StkSmart.java:66)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:82)
	at com.zerocracy.farm.reactive.Brigade.lambda$apply$0(Brigade.java:64)
	at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.iterator.Filtered.hasNext(Filtered.java:90)
	at org.cactoos.iterator.LengthOf.lambda$new$0(LengthOf.java:52)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)... 
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@neonailol shouldn't happen again, I hope. It was a defect with PayPal connection.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#538` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#538](https://github.com/zerocracy/farm/issues/538) was not in scope
