### ISSUE TITLE
notify_user sometimes fail

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#549]
Tests sometimes fails with this stacktrace:
```
AsyncFlush-4 com.jcabi.log.VerboseCallable: swallowed runtime exception: java.lang.IllegalStateException: java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/comm/notify_user.groovy
        at com.zerocracy.farm.StkSafe.process(StkSafe.java:123)
        at com.zerocracy.farm.reactive.StkSmart.process(StkSmart.java:66)
        at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:82)
        at com.zerocracy.farm.reactive.Brigade.lambda$apply$0(Brigade.java:64)
        at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
        at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
        at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
        at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
        at org.cactoos.iterator.Filtered.hasNext(Filtered.java:90)
        at org.cactoos.iterator.LengthOf.lambda$new$0(LengthOf.java:52)
        at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
        at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
        at org.cactoos.scalar.NumberEnvelope.doubleValue(NumberEnvelope.java:113)
        at org.cactoos.iterable.LengthOf.lambda$new$0(LengthOf.java:51)
        at org.cactoos.scalar.NumberEnvelope.lambda$new$1(NumberEnvelope.java:73)
        at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
        at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
        at org.cactoos.scalar.NumberEnvelope.intValue(NumberEnvelope.java:98)
        at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:67)
        at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:37)
        at org.cactoos.func.IoCheckedBiFunc.lambda$apply$0(IoCheckedBiFunc.java:60)
        at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
        at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:61)
        at com.zerocracy.farm.reactive.DefaultFlush.process(DefaultFlush.java:97)
        at com.zerocracy.farm.reactive.DefaultFlush.exec(DefaultFlush.java:70)
        at com.zerocracy.farm.reactive.DefaultFlush.exec(DefaultFlush.java:44)
        at com.zerocracy.farm.reactive.AsyncFlush.lambda$exec$2(AsyncFlush.java:118)
        at com.jcabi.log.VerboseCallable.call(VerboseCallable.java:173)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:221)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/comm/notify_user.groovy
        at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:125)
        at com.zerocracy.farm.StkSafe.process(StkSafe.java:82)
        ... 32 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:115)
        ... 33 more
Caused by: java.lang.IllegalArgumentException: Project PMO doesn't exist, can't get links
        at com.zerocracy.pmo.Catalog.links(Catalog.java:448)
        at com.zerocracy.pmo.Catalog$links$3.call(Unknown Source)
        at com.zerocracy.stk.pm.comm.notify_user.exec(notify_user.groovy:41)
        ... 37 more
```
e.g. this build: http://www.rultor.com/t/13858-364974689

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 too late, fixed already in a518b373

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#549` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#549](https://github.com/zerocracy/farm/issues/549) was not in scope
