### ISSUE TITLE
Broken points distribution for manual assignment

### ISSUE THREAD

**Issue by biboran** [zerocracy/farm#662]
As an `ARC` I assigned a task manually and points punishment was applied to the assigned `DEV` and his mentor who is not participating in this project. The excepted behavior would be that I got the punishment for manual assignment (this used to be the case for all previous issues I assigned manually).

![screen shot 2018-02-27 at 3 05 20 pm](https://user-images.githubusercontent.com/8717108/36728373-93243898-1bd1-11e8-9394-ab1e110c1889.png)
![screen shot 2018-02-27 at 3 04 12 pm](https://user-images.githubusercontent.com/8717108/36728372-9132536c-1bd1-11e8-9abf-1b1f6fa7563d.png)

**Comment by driver733** [comment]
Also, 0crat took off only 5 points me (see first post), but did not take off 15 (see second post, my point reputation did not change after the second post).
![screen shot 2018-02-27 at 10 49 38 am](https://user-images.githubusercontent.com/10466206/36738607-f36e1956-1bab-11e8-9124-4e284381828f.png)

**Comment by biboran** [comment]
@driver733 I don't think it works that way. 0crat usually does notification in batches but the points are precomputed for the batch execution and you get the same output for the whole batch.

**Comment by driver733** [comment]
Here is the stack trace

```
java.lang.IllegalStateException: [GET http://www.0crat.com/p/PMO] failed in 129ms: File "rates.xml" is not accessible in "PMO"
	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)
	at org.takes.facets.fallback.TkFallback.access$100(TkFallback.java:54)
	at org.takes.facets.fallback.TkFallback$2.body(TkFallback.java:202)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsPrint.printBody(RsPrint.java:161)
	at org.takes.rs.RsPrint.print(RsPrint.java:114)
	at org.takes.http.BkBasic.print(BkBasic.java:108)
	at org.takes.http.BkBasic.accept(BkBasic.java:84)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: File "rates.xml" is not accessible in "PMO"
	at com.zerocracy.farm.strict.StrictProject.acq(StrictProject.java:110)
	at com.zerocracy.farm.props.PropsProject.acq(PropsProject.java:78)
	at com.zerocracy.farm.footprint.FtProject.acq(FtProject.java:67)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.farm.ruled.RdItem.lambda$close$3(RdItem.java:132)
	at com.zerocracy.farm.ruled.RdAuto.auto(RdAuto.java:125)
	at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
	at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
	at org.cactoos.scalar.And.lambda$null$0(And.java:132)
	at org.cactoos.scalar.And.value(And.java:167)
	at org.cactoos.scalar.And.value(And.java:60)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at com.zerocracy.farm.ruled.RdAuto.propagate(RdAuto.java:108)
	at com.zerocracy.farm.ruled.RdItem.close(RdItem.java:136)
	at com.zerocracy.pm.staff.Roles.bootstrap(Roles.java:75)
	at com.zerocracy.tk.project.RqProject.lambda$new$0(RqProject.java:83)
	at org.cactoos.scalar.SolidScalar.lambda$new$0(SolidScalar.java:55)
	at org.cactoos.func.StickyFunc.lambda$new$0(StickyFunc.java:72)
	at org.cactoos.func.StickyBiFunc.apply(StickyBiFunc.java:95)
	at org.cactoos.func.StickyFunc.apply(StickyFunc.java:79)
	at org.cactoos.func.SyncFunc.apply(SyncFunc.java:101)
	at org.cactoos.func.SolidFunc.apply(SolidFunc.java:66)
	at org.cactoos.scalar.SolidScalar.value(SolidScalar.java:61)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at com.zerocracy.tk.project.RqProject.pid(RqProject.java:112)
	at com.zerocracy.tk.project.TkProject.lambda$act$6(TkProject.java:75)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at com.zerocracy.tk.RsPage.lambda$make$0(RsPage.java:121)
	at org.takes.rs.xe.XeChain$2.toXembly(XeChain.java:79)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeChain$2.toXembly(XeChain.java:80)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeAppend$1.toXembly(XeAppend.java:75)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeChain$2.toXembly(XeChain.java:80)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.RsXembly.render(RsXembly.java:147)
	at org.takes.rs.xe.RsXembly.access$000(RsXembly.java:65)
	at org.takes.rs.xe.RsXembly$1.body(RsXembly.java:129)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithoutHeader$1.body(RsWithoutHeader.java:75)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsPrettyXml.make(RsPrettyXml.java:113)
	at org.takes.rs.RsPrettyXml.head(RsPrettyXml.java:94)
	at org.takes.facets.fork.RsFork$1.head(RsFork.java:70)
	at org.takes.rs.RsWrap.head(RsWrap.java:60)
	at org.takes.rs.RsWrap.head(RsWrap.java:60)
	at org.takes.facets.forward.TkForward$Safe.load(TkForward.java:115)
	at org.takes.facets.forward.TkForward$Safe.body(TkForward.java:102)
	at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsGzip.make(RsGzip.java:91)
	at org.takes.rs.RsGzip.body(RsGzip.java:76)
	at org.takes.facets.fork.RsFork$1.body(RsFork.java:74)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithHeaders$1.body(RsWithHeaders.java:78)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.facets.fallback.TkFallback$2.body(TkFallback.java:187)
	... 12 more
```

**Comment by yegor256** [comment]
@biboran what is broken? You don't want negative points to be applied to your mentor? I didn't get the problem.

**Comment by driver733** [comment]
@yegor256 
@biboran, the `ARC`, assigned me to the ticket and should have been punished for that. But instead, I the `DEV` got punished.

**Comment by yegor256** [comment]
@driver733 I see, thanks, let me check

**Comment by 0crat** [comment]
The job [#662](https://github.com/zerocracy/farm/issues/662) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/591746726). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @biboran[/z](https://www.0crat.com/u/biboran), total is [+175](https://www.0crat.com/u/biboran)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10999](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@biboran it's fixed in e5c0665a9f481a2da667ad607316e0e1307bea57 won't happen again.

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#662](https://github.com/zerocracy/farm/issues/662) is now out of scope
