### ISSUE TITLE
Identify link is broken

### ISSUE THREAD

**Issue by llorllale** [zerocracy/farm#663]
Trying to access https://www.0crat.com/identify and get this error:

```
Internal application error

1.0-SNAPSHOT, 5996b5c4

Please, report it here. We will do our best to fix it as soon as possible. We're very sorry.

java.lang.IllegalStateException: [GET http://www.0crat.com/identify] failed in 1ms: No group 1
	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)
	at org.takes.facets.fallback.TkFallback.access$100(TkFallback.java:54)
	at org.takes.facets.fallback.TkFallback$2.body(TkFallback.java:202)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsPrint.printBody(RsPrint.java:161)
	at org.takes.rs.RsPrint.print(RsPrint.java:114)
	at org.takes.http.BkBasic.print(BkBasic.java:108)
	at org.takes.http.BkBasic.accept(BkBasic.java:84)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IndexOutOfBoundsException: No group 1
	at java.util.regex.Matcher.group(Matcher.java:538)
	at com.zerocracy.tk.profile.RqLogin.value(RqLogin.java:63)
	at com.zerocracy.tk.profile.RqSecureLogin.value(RqSecureLogin.java:63)
	at com.zerocracy.tk.profile.TkIdentify.lambda$act$0(TkIdentify.java:63)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at com.zerocracy.tk.RsPage.lambda$make$0(RsPage.java:121)
	at org.takes.rs.xe.XeChain$2.toXembly(XeChain.java:79)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeChain$2.toXembly(XeChain.java:80)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeAppend$1.toXembly(XeAppend.java:75)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeChain$2.toXembly(XeChain.java:80)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.RsXembly.render(RsXembly.java:147)
	at org.takes.rs.xe.RsXembly.access$000(RsXembly.java:65)
	at org.takes.rs.xe.RsXembly$1.body(RsXembly.java:129)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithoutHeader$1.body(RsWithoutHeader.java:75)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsPrettyXml.make(RsPrettyXml.java:113)
	at org.takes.rs.RsPrettyXml.head(RsPrettyXml.java:94)
	at org.takes.facets.fork.RsFork$1.head(RsFork.java:70)
	at org.takes.rs.RsWrap.head(RsWrap.java:60)
	at org.takes.rs.RsWrap.head(RsWrap.java:60)
	at org.takes.facets.forward.TkForward$Safe.load(TkForward.java:115)
	at org.takes.facets.forward.TkForward$Safe.body(TkForward.java:102)
	at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsGzip.make(RsGzip.java:91)
	at org.takes.rs.RsGzip.body(RsGzip.java:76)
	at org.takes.facets.fork.RsFork$1.body(RsFork.java:74)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.rs.RsWithHeaders$1.body(RsWithHeaders.java:78)
	at org.takes.rs.RsWrap.body(RsWrap.java:65)
	at org.takes.facets.fallback.TkFallback$2.body(TkFallback.java:187)
	... 12 more
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#663](https://github.com/zerocracy/farm/issues/663) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/581710403). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale), total is [+880](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10969](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@llorllale I believe it's fixed in dde5484e, please check

**Comment by llorllale** [comment]
@yegor256 thanks

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+10994](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#663](https://github.com/zerocracy/farm/issues/663) is now out of scope
