### ISSUE TITLE
"Internal application error" on board page

### ISSUE THREAD

**Issue by proshin-roman** [zerocracy/farm#686]
I get this error each time when open https://www.0crat.com/board:
```
java.lang.IllegalStateException: [GET http://www.0crat.com/board] failed in 4ms: javax.crypto.BadPaddingException: Given final block not properly padded
	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:115)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at com.zerocracy.tk.TkSslOnly.act(TkSslOnly.java:59)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.http.BkBasic.print(BkBasic.java:108)
	at org.takes.http.BkBasic.accept(BkBasic.java:84)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: javax.crypto.BadPaddingException: Given final block not properly padded
	at org.takes.facets.auth.codecs.CcAes.decrypt(CcAes.java:163)
	at org.takes.facets.auth.codecs.CcAes.decode(CcAes.java:102)
	at org.takes.facets.auth.codecs.CcHex.decode(CcHex.java:117)
	at org.takes.facets.auth.codecs.CcSafe.decode(CcSafe.java:64)
	at com.zerocracy.tk.CcSecure.decode(CcSecure.java:77)
	at org.takes.facets.auth.PsCookie.enter(PsCookie.java:105)
	at org.takes.facets.auth.PsChain.enter(PsChain.java:70)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:86)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:108)
	at org.takes.tk.TkGzip$1.act(TkGzip.java:58)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:73)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:86)
	... 14 more
Caused by: javax.crypto.BadPaddingException: Given final block not properly padded
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:991)
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:847)
	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
	at javax.crypto.Cipher.doFinal(Cipher.java:2165)
	at org.takes.facets.auth.codecs.CcAes.decrypt(CcAes.java:161)
	... 32 more
```

Version shown on the page was `1.0-SNAPSHOT, 3b2de08b`

Time was 15:09 UTC+3 of 01 March 2018. Browser (if it makes any difference) was Yandex Browser 18.1.1.839

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@proshin-roman @amihaiemil should work now (recent version of Takes was broken). The final fix will be deployed now.

**Comment by 0crat** [comment]
The job [#686](https://github.com/zerocracy/farm/issues/686) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/601416263). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@proshin-roman it's fixed

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#686](https://github.com/zerocracy/farm/issues/686) is now out of scope
