### ISSUE TITLE
Login fails with "[400] No access token" error

### ISSUE THREAD

**Issue by driver733** [zerocracy/farm#690]
While logging in I have faced the error` [400] No access token`

```
java.lang.IllegalStateException: [GET https://www.0crat.com/?PsByFlag=PsGithub&code=c251b26161b3bcc26d6c] failed in 73ms: [400] No access token
	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:92)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at com.zerocracy.tk.TkSslOnly.act(TkSslOnly.java:59)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.http.BkBasic.print(BkBasic.java:108)
	at org.takes.http.BkBasic.accept(BkBasic.java:84)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.takes.HttpException: [400] No access token
	at org.takes.facets.auth.social.PsGithub.token(PsGithub.java:186)
	at org.takes.facets.auth.social.PsGithub.enter(PsGithub.java:132)
	at org.takes.facets.auth.PsByFlag.enter(PsByFlag.java:107)
	at org.takes.facets.auth.PsChain.enter(PsChain.java:70)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:86)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:108)
	at org.takes.tk.TkGzip$1.act(TkGzip.java:58)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:73)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:86)
	... 14 more
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#690](https://github.com/zerocracy/farm/issues/690) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/602029763). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @driver733[/z](https://www.0crat.com/u/driver733)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@driver733 it's fixed

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#690](https://github.com/zerocracy/farm/issues/690) is now out of scope
