### ISSUE TITLE
IllegalStateException: [POST https://www.0crat.com/ghook] failed in 8s: com.amazonaws.SdkClientException: Unable to exec...

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#741]
here: https://github.com/zerocracy/farm/issues/229#issuecomment-371047170

https://sentry.io/zerocracy/farm/issues/464802247/

```
ClosedChannelException: None
    at sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:110)
    at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:147)
    at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
    at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109)
    at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
...
(45 additional frame(s) were not displayed)

SdkClientException: Unable to execute HTTP request: null
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1113)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1063)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
...
(14 additional frame(s) were not displayed)

IOException: com.amazonaws.SdkClientException: Unable to execute HTTP request: null
    at com.zerocracy.radars.github.RbSafe.lambda$react$1(RbSafe.java:91)
    at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:95)
    at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
    at com.zerocracy.radars.github.RbDelayed.react(RbDelayed.java:57)
    at com.zerocracy.radars.github.RbAccessible.react(RbAccessible.java:88)
...
(46 additional frame(s) were not displayed)

IllegalStateException: [POST https://www.0crat.com/ghook] failed in 8s: com.amazonaws.SdkClientException: Unable to execute HTTP request: null
    at com.zerocracy.tk.TkSslOnly.act(TkSslOnly.java:59)
...
(11 additional frame(s) were not displayed)

[POST https://www.0crat.com/ghook] failed in 8s: com.amazonaws.SdkClientException: Unable to execute HTTP request: null
```

**Comment by yegor256** [comment]
Full stack trace:

```
java.nio.channels.ClosedChannelException: null
    at sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:110)
    at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:147)
    at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
    at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109)
    at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
    at org.apache.commons.io.input.ProxyInputStream.read(ProxyInputStream.java:100)
    at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:82)
    at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:82)
    at com.amazonaws.util.LengthCheckInputStream.read(LengthCheckInputStream.java:107)
    at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:82)
    at com.amazonaws.services.s3.internal.MD5DigestCalculatingInputStream.read(MD5DigestCalculatingInputStream.java:128)
    at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
    at com.amazonaws.internal.SdkBufferedInputStream.read(SdkBufferedInputStream.java:76)
    at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:82)
    at com.amazonaws.event.ProgressInputStream.read(ProgressInputStream.java:180)
    at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:82)
    at org.apache.http.entity.InputStreamEntity.writeTo(InputStreamEntity.java:140)
    at com.amazonaws.http.RepeatableInputStreamRequestEntity.writeTo(RepeatableInputStreamRequestEntity.java:160)
    at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:156)
    at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:162)
    at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:238)
    at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doSendRequest(SdkHttpRequestExecutor.java:63)
    at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
    at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1235)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1055)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
    at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4247)
    at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4194)
    at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1738)
    at com.amazonaws.services.s3.transfer.internal.UploadCallable.uploadInOneChunk(UploadCallable.java:133)
    at com.amazonaws.services.s3.transfer.internal.UploadCallable.call(UploadCallable.java:125)
    at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:143)
    at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:48)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
com.amazonaws.SdkClientException: Unable to execute HTTP request: null
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1113)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1063)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
    at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4247)
    at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4194)
    at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1738)
    at com.amazonaws.services.s3.transfer.internal.UploadCallable.uploadInOneChunk(UploadCallable.java:133)
    at com.amazonaws.services.s3.transfer.internal.UploadCallable.call(UploadCallable.java:125)
    at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:143)
    at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:48)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
java.io.IOException: com.amazonaws.SdkClientException: Unable to execute HTTP request: null
    at com.zerocracy.radars.github.RbSafe.lambda$react$1(RbSafe.java:91)
    at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
    at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
    at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:90)
    at org.cactoos.func.IoCheckedFunc.lambda$apply$0(IoCheckedFunc.java:59)
    at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
    at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:59)
    at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:95)
    at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
    at com.zerocracy.radars.github.RbDelayed.react(RbDelayed.java:57)
    at com.zerocracy.radars.github.RbAccessible.react(RbAccessible.java:88)
    at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:172)
    at org.takes.facets.fork.FkMethods.route(FkMethods.java:103)
    at org.takes.facets.fork.FkChain.route(FkChain.java:75)
    at org.takes.facets.fork.TkFork.act(TkFork.java:100)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:154)
    at org.takes.facets.fork.FkRegex.route(FkRegex.java:210)
    at org.takes.facets.fork.FkChain.route(FkChain.java:75)
    at org.takes.facets.fork.TkFork.act(TkFork.java:100)
    at org.takes.facets.forward.TkForward.act(TkForward.java:68)
    at org.takes.facets.fork.FkFixed$1.route(FkFixed.java:56)
    at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
    at org.takes.facets.fork.FkChain.route(FkChain.java:75)
    at org.takes.facets.fork.TkFork.act(TkFork.java:100)
    at org.takes.facets.auth.TkAuth.act(TkAuth.java:91)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.facets.flash.TkFlash.act(TkFlash.java:108)
    at org.takes.tk.TkGzip$1.act(TkGzip.java:58)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkVersioned$1.act(TkVersioned.java:73)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.facets.fallback.TkFallback.route(TkFallback.java:86)
    at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
    at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at com.zerocracy.tk.TkSslOnly.act(TkSslOnly.java:59)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.http.BkBasic.print(BkBasic.java:108)
    at org.takes.http.BkBasic.accept(BkBasic.java:84)
    at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
    at org.takes.http.BkWrap.accept(BkWrap.java:52)
    at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
    at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
java.lang.IllegalStateException: [POST https://www.0crat.com/ghook] failed in 8s: com.amazonaws.SdkClientException: Unable to execute HTTP request: null
    at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)
    at org.takes.facets.fallback.TkFallback.route(TkFallback.java:115)
    at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
    at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at com.zerocracy.tk.TkSslOnly.act(TkSslOnly.java:59)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.http.BkBasic.print(BkBasic.java:108)
    at org.takes.http.BkBasic.accept(BkBasic.java:84)
    at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
    at org.takes.http.BkWrap.accept(BkWrap.java:52)
    at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
    at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by yegor256** [comment]
@0crat assign @carlosmiranda

**Comment by yegor256** [comment]
@carlosmiranda we tried here: https://github.com/zerocracy/farm/issues/511

**Comment by 0crat** [comment]
> @0crat assign @carlosmiranda  ([here](https://github.com/zerocracy/farm/issues/741#issuecomment-371047916))

@yegor256 The job [#741](https://github.com/zerocracy/farm/issues/741) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/660739063). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by carlosmiranda** [comment]
@yegor256 isn't this supposed to be handled in #556?

**Comment by yegor256** [comment]
@0crat refuse

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.amazonaws.http.AmazonHttpClient$RequestExecutor[1113] com.amazonaws.SdkClientException: Unable to execute HTTP request: null
sun.nio.ch.FileChannelImpl[110] java.nio.channels.ClosedChannelException: null
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.radars.github.ReSafe[76] java.io.IOException: com.amazonaws.SdkClientException: Unable to execute HTTP request: null
com.amazonaws.http.AmazonHttpClient$RequestExecutor[1113] com.amazonaws.SdkClientException: Unable to execute HTTP request: null
sun.nio.ch.FileChannelImpl[110] java.nio.channels.ClosedChannelException: null
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by yegor256** [comment]
@carlosmiranda you are right, it's a duplicate

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#741](https://github.com/zerocracy/farm/issues/741) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
