### ISSUE TITLE
/ghook IllegalStateException

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#791]
Received from Sentry:

**Exception**:
```
TerminationException: Processing terminated by xsl:message at line 27 in file:///
    at net.sf.saxon.expr.instruct.Message.processLeavingTail(Message.java:223)
    at net.sf.saxon.expr.instruct.Choose.processLeavingTail(Choose.java:880)
    at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:687)
    at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:151)
    at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:337)
...
(77 additional frame(s) were not displayed)

IllegalArgumentException: Failed to transform by net.sf.saxon.TransformerFactoryImpl: [Job name "gh:yegor256/elegantobjects.github.io#35" is not valid, Processing terminated by xsl:message at line 27 in file:///; SystemID: file:///; Line#: 27; Column#: 6]
    at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:108)
    at com.zerocracy.radars.github.RbOnPullRequest.react(RbOnPullRequest.java:50)
    at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
    at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
    at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:67)
...
(51 additional frame(s) were not displayed)

IOException: java.lang.IllegalArgumentException: Failed to transform by net.sf.saxon.TransformerFactoryImpl: [Job name "gh:yegor256/elegantobjects.github.io#35" is not valid, Processing terminated by xsl:message at line 27 in file:///; SystemID: file:///; Line#: 27; Column#: 6]
    at com.zerocracy.radars.github.RbSafe.lambda$react$1(RbSafe.java:91)
    at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:95)
    at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
    at com.zerocracy.radars.github.RbDelayed.react(RbDelayed.java:57)
    at com.zerocracy.radars.github.RbAccessible.react(RbAccessible.java:88)
...
(46 additional frame(s) were not displayed)

IllegalStateException: [POST https://www.0crat.com/ghook] failed in 5s: java.lang.IllegalArgumentException: Failed to transform by net.sf.saxon.TransformerFactoryImpl: [Job name "gh:yegor256/elegantobjects.github.io#35" is not valid, Processing terminated by xsl:message at line 27 in file:///; SystemID: file:///; Line#: 27; Column#: 6]
    at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)
    at org.takes.facets.fallback.TkFallback.route(TkFallback.java:115)
    at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
    at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
...
(11 additional frame(s) were not displayed)
```
**Message**:
```
[POST https://www.0crat.com/ghook] failed in 5s: java.lang.IllegalArgumentException: Failed to transform by net.sf.saxon.TransformerFactoryImpl: [Job name "gh:yegor256/elegantobjects.github.io#35" is not valid, Processing terminated by xsl:message at line 27 in file:///; SystemID: file:///; Line#: 27; Column#: 6]
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil fixed already, thanks
