### ISSUE TITLE
GPG signature for PDF documents

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#819]
Let's add GPG signature for all PDF documents we produce.

**Comment by amihaiemil** [comment]
@yegor256 goddamn, please stop commiting on master, it's broken now :(

**Comment by amihaiemil** [comment]
@yegor256 
```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.159 sec <<< FAILURE! - in com.zerocracy.tools.SignatureTest
rendersSignature(com.zerocracy.tools.SignatureTest)  Time elapsed: 0.159 sec  <<< ERROR!
java.lang.IllegalStateException: 
Failed to receive PGP key: gpg: WARNUNG: Unsicheres Besitzverh"altnis des Home-Verzeichnis `/Users/amihaiemil/.gnupg'
gpg: failed to create temporary file '/Users/amihaiemil/.gnupg/.#lk0x00007fe20f406210.Mihais-MacBook-Pro.local.2734': Permission denied
gpg: can't allocate lock for '/Users/amihaiemil/.gnupg/pubring.kbx': Permission denied
gpg: Schl"usselblockhilfsmittel`/Users/amihaiemil/.gnupg/pubring.kbx': Permission denied
gpg: Kein aktiver Dirmngr - `/usr/local/Cellar/gnupg/2.2.4/bin/dirmngr' wird gestartet
gpg: failed to create temporary file '/Users/amihaiemil/.gnupg/.#lk0x00007fe20f406260.Mihais-MacBook-Pro.local.2734': Permission denied
gpg: connecting dirmngr at '/Users/amihaiemil/.gnupg/S.dirmngr' failed: Permission denied
gpg: receptie server de chei esuata: No dirmngr

	at com.zerocracy.tools.Signature.asString(Signature.java:74)
	at com.zerocracy.tools.SignatureTest.rendersSignature(SignatureTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:393)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


Results :

Tests in error: 
  SignatureTest.rendersSignature:36 » IllegalState Failed to receive PGP key: gp...
```

**Comment by amihaiemil** [comment]
@yegor256 the build worked only when ran with ``sudo``, which is still not ok; you don't run builds containing who knows what maven plugins, with admin rights...

**Comment by yegor256** [comment]
@amihaiemil try now please, I made it touch the temp dir only: be45af7f

**Comment by amihaiemil** [comment]
@yegor256 yes, now it seems to work

**Comment by yegor256** [comment]
@amihaiemil sorry for touching master, but this problem would not be caught by Rultor/Travis anyway, since it's relevant to your local environment only.
