### ISSUE TITLE
IllegalStateException: [POST https://www.0crat.com/ghook] failed in 26ms: URLDecoder: Illegal hex characters in escape (...

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#831]
https://sentry.io/zerocracy/farm/issues/494855832/

```
IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - For input string: " r"
    at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:151)
...
(40 additional frame(s) were not displayed)

IllegalStateException: [POST https://www.0crat.com/ghook] failed in 26ms: URLDecoder: Illegal hex characters in escape (%) pattern - For input string: " r"
    at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)
    at org.takes.facets.fallback.TkFallback.route(TkFallback.java:115)
    at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
    at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
...
(11 additional frame(s) were not displayed)

[POST https://www.0crat.com/ghook] failed in 26ms: URLDecoder: Illegal hex characters in escape (%) pattern - For input string: " r"
```

Full:

```
java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - For input string: " r"
    at java.net.URLDecoder.decode(URLDecoder.java:194)
    at org.takes.rq.form.RqFormBase.decode(RqFormBase.java:115)
    at org.takes.rq.form.RqFormBase.freshMap(RqFormBase.java:160)
    at org.takes.rq.form.RqFormBase.map(RqFormBase.java:131)
    at org.takes.rq.form.RqFormBase.param(RqFormBase.java:81)
    at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:151)
    at org.takes.facets.fork.FkMethods.route(FkMethods.java:103)
    at org.takes.facets.fork.FkChain.route(FkChain.java:75)
    at org.takes.facets.fork.TkFork.act(TkFork.java:100)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:154)
    at org.takes.facets.fork.FkRegex.route(FkRegex.java:210)
    at org.takes.facets.fork.FkChain.route(FkChain.java:75)
    at org.takes.facets.fork.TkFork.act(TkFork.java:100)
    at org.takes.facets.forward.TkForward.act(TkForward.java:68)
    at org.takes.facets.fork.FkFixed$1.route(FkFixed.java:56)
    at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
    at org.takes.facets.fork.FkChain.route(FkChain.java:75)
    at org.takes.facets.fork.TkFork.act(TkFork.java:100)
    at org.takes.facets.auth.TkAuth.act(TkAuth.java:91)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.facets.flash.TkFlash.act(TkFlash.java:108)
    at org.takes.tk.TkGzip$1.act(TkGzip.java:58)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkVersioned$1.act(TkVersioned.java:73)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.facets.fallback.TkFallback.route(TkFallback.java:86)
    at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
    at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkSslOnly.act(TkSslOnly.java:71)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.http.BkBasic.print(BkBasic.java:108)
    at org.takes.http.BkBasic.accept(BkBasic.java:84)
    at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
    at org.takes.http.BkWrap.accept(BkWrap.java:52)
    at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
    at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
java.lang.IllegalStateException: [POST https://www.0crat.com/ghook] failed in 26ms: URLDecoder: Illegal hex characters in escape (%) pattern - For input string: " r"
    at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)
    at org.takes.facets.fallback.TkFallback.route(TkFallback.java:115)
    at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
    at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkSslOnly.act(TkSslOnly.java:71)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.http.BkBasic.print(BkBasic.java:108)
    at org.takes.http.BkBasic.accept(BkBasic.java:84)
    at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
    at org.takes.http.BkWrap.accept(BkWrap.java:52)
    at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
    at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by 0crat** [comment]
Job [#831](https://github.com/zerocracy/farm/issues/831) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#831](https://github.com/zerocracy/farm/issues/831) assigned to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1390817127); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@t-izbassar[/z](https://www.0crat.com/u/t-izbassar) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by t-izbassar** [comment]
@yegor256 can you boost this job? It seems like this task will require accurate digging in our redirection urls. And from stacktrace we only have an information, that it failed to parse POST request on `https://www.0crat.com/ghook` with incorrect URL.

Even if we reproduce the bug by sending this POST request to `TkGithub` (which is responsible for dealing with `ghook`), we won't find where we creating such invalid request (it might be the github bug?) - that's require dip digging.

**Comment by t-izbassar** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/831#issuecomment-393464360))

@t-izbassar The user @t-izbassar[/z](https://www.0crat.com/u/t-izbassar) resigned from [#831](https://github.com/zerocracy/farm/issues/831), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by yegor256** [comment]
@g4s8 this should be pretty simple. Just check if the HTTP query param is present. If it's not, return `RsText("param is mandatory")`. Otherwise, do what we do now.

**Comment by 0crat** [comment]
The job [#831](https://github.com/zerocracy/farm/issues/831) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1551157535); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by g4s8** [comment]
@yegor256 this exception was reproduced and fixed in #1097 PR, can we close?

**Comment by yegor256** [comment]
@g4s8 thanks

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#831](https://github.com/zerocracy/farm/issues/831) is now out of scope
