### ISSUE TITLE
422 Unprocessable Entity for equity pdf download

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#852]
I tried to download equity pdf but got an error:
```
java.lang.IllegalStateException: [GET https://www.0crat.com/equity/C3NDPUA8L] failed in 2s: HTTP response status is not equal to 200:
422 Unprocessable Entity [https://hostq81gtq.cloudconvert.com/download/avibOB0e1p3yz4QKHA8W?inline]
Cache-Control: no-cache, no-store, must-revalidate
ETag: W/"44-DM9oKUrbqU6X/bfOf8G1tHs4zwA"
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS, GET, PUT, POST, DELETE
Connection: keep-alive
Expires: 0
Pragma: no-cache
Content-Length: 68
Date: Tue, 20 Mar 2018 12:31:38 GMT
Access-Control-Allow-Headers: Content-Type, Origin, User-Agent, Retry-After
Content-Type: application/json; charset=utf-8

{"error":"Transcript written on /data//article.log.\r\n","code":422}
Expected: HTTP response with status 200
     but: was <422 Unprocessable Entity [https://hostq81gtq.cloudconvert.com/download/avibOB0e1p3yz4QKHA8W?inline]
Cache-Control: no-cache, no-store, must-revalidate
ETag: W/"44-DM9oKUrbqU6X/bfOf8G1tHs4zwA"
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS, GET, PUT, POST, DELETE
Connection: keep-alive
Expires: 0
Pragma: no-cache
Content-Length: 68
Date: Tue, 20 Mar 2018 12:31:38 GMT
Access-Control-Allow-Headers: Content-Type, Origin, User-Agent, Retry-After
Content-Type: application/json; charset=utf-8

{"error":"Transcript written on /data//article.log.\r\n","code":422}>
	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:115)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkSslOnly.act(TkSslOnly.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.http.BkBasic.print(BkBasic.java:108)
	at org.takes.http.BkBasic.accept(BkBasic.java:84)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AssertionError: HTTP response status is not equal to 200:
422 Unprocessable Entity [https://hostq81gtq.cloudconvert.com/download/avibOB0e1p3yz4QKHA8W?inline]
Cache-Control: no-cache, no-store, must-revalidate
ETag: W/"44-DM9oKUrbqU6X/bfOf8G1tHs4zwA"
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS, GET, PUT, POST, DELETE
Connection: keep-alive
Expires: 0
Pragma: no-cache
Content-Length: 68
Date: Tue, 20 Mar 2018 12:31:38 GMT
Access-Control-Allow-Headers: Content-Type, Origin, User-Agent, Retry-After
Content-Type: application/json; charset=utf-8
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#852](https://github.com/zerocracy/farm/issues/852) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by victornoel** [comment]
@g4s8 could we get this fixed? I tried to access my equity proof on a project and I got the following error (it's a bit different than the one in the description, but according to #2073 and #2077 it is the same problem):
```
java.lang.IllegalStateException: [GET https://www.0crat.com/equity/CJT4R32Q3] failed in 2s: HTTP response status is not equal to 200:
500 Internal Server Error [https://marcelina.infra.cloudconvert.com/download/a20a8dbb-5d4b-41e0-b692-90a793fcc5bf?inline]
Cache-Control: no-cache, no-store, must-revalidate
ETag: W/"2a-c5Yd735mWsST6SbM+ozpXm6eIAU"
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS, GET, PUT, POST, DELETE
Connection: keep-alive
Expires: 0
Pragma: no-cache
Content-Length: 42
Date: Sun, 14 Jul 2019 14:20:26 GMT
Access-Control-Allow-Headers: Content-Type, Origin, User-Agent, Retry-After
Content-Type: application/json; charset=utf-8

{"error":"Converter not found","code":500}
Expected: HTTP response with status 200
     but: was <500 Internal Server Error [https://marcelina.infra.cloudconvert.com/download/a20a8dbb-5d4b-41e0-b692-90a793fcc5bf?inline]
Cache-Control: no-cache, no-store, must-revalidate
ETag: W/"2a-c5Yd735mWsST6SbM+ozpXm6eIAU"
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS, GET, PUT, POST, DELETE
Connection: keep-alive
Expires: 0
Pragma: no-cache
Content-Length: 42
Date: Sun, 14 Jul 2019 14:20:26 GMT
Access-Control-Allow-Headers: Content-Type, Origin, User-Agent, Retry-After
Content-Type: application/json; charset=utf-8

{"error":"Converter not found","code":500}>
	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:115)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkSslOnly.act(TkSslOnly.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.http.BkBasic.print(BkBasic.java:108)
	at org.takes.http.BkBasic.accept(BkBasic.java:84)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AssertionError: HTTP response status is not equal to 200:
500 Internal Server Error [https://marcelina.infra.cloudconvert.com/download/a20a8dbb-5d4b-41e0-b692-90a793fcc5bf?inline]
Cache-Control: no-cache, no-store, must-revalidate
ETag: W/"2a-c5Yd735mWsST6SbM+ozpXm6eIAU"
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS, GET, PUT, POST, DELETE
Connection: keep-alive
Expires: 0
Pragma: no-cache
Content-Length: 42
Date: Sun, 14 Jul 2019 14:20:26 GMT
Access-Control-Allow-Headers: Content-Type, Origin, User-Agent, Retry-After
Content-Type: application/json; charset=utf-8

{"error":"Converter not found","code":500}
Expected: HTTP response with status 200
     but: was <500 Internal Server Error [https://marcelina.infra.cloudconvert.com/download/a20a8dbb-5d4b-41e0-b692-90a793fcc5bf?inline]
Cache-Control: no-cache, no-store, must-revalidate
ETag: W/"2a-c5Yd735mWsST6SbM+ozpXm6eIAU"
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS, GET, PUT, POST, DELETE
Connection: keep-alive
Expires: 0
Pragma: no-cache
Content-Length: 42
Date: Sun, 14 Jul 2019 14:20:26 GMT
Access-Control-Allow-Headers: Content-Type, Origin, User-Agent, Retry-After
Content-Type: application/json; charset=utf-8

{"error":"Converter not found","code":500}>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at com.jcabi.http.response.RestResponse.assertStatus(RestResponse.java:111)
	at com.zerocracy.tools.Latex.pdf(Latex.java:103)
	at com.zerocracy.pm.cost.Equity.pdf(Equity.java:102)
	at com.zerocracy.tk.project.TkEquity.act(TkEquity.java:73)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:210)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at com.zerocracy.tk.TkSoftForward.lambda$new$0(TkSoftForward.java:48)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.forward.TkForward.act(TkForward.java:68)
	at org.takes.facets.fork.FkFixed$1.route(FkFixed.java:56)
	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:109)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:89)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:108)
	at org.takes.tk.TkGzip$1.act(TkGzip.java:58)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:73)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:86)
	... 14 more
```
