### ISSUE TITLE
Internal Application Error when sending join request form

### ISSUE THREAD

**Issue by Vatavuk** [zerocracy/farm#859]
I've got error response while sending new request form to join zerocracy.

```
at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:115)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkSslOnly.act(TkSslOnly.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.http.BkBasic.print(BkBasic.java:108)
	at org.takes.http.BkBasic.accept(BkBasic.java:84)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Duplicate claims are not allowed, can't add this: <?xml version="1.0" encoding="UTF-8"?>
<claim id="811263451">
   <created>2018-03-22T12:59:11.593Z</created>
   <type>Notify all</type>
   <params>
      <param name="message">someText
</param>
      <param name="min">1024</param>
   </params>
</claim>

	at com.zerocracy.pm.Claims.add(Claims.java:107)
	at com.zerocracy.pm.Claims.add(Claims.java:79)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:91)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:122)
	at com.zerocracy.tk.TkJoin.act(TkJoin.java:88)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:210)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at org.takes.facets.forward.TkForward.act(TkForward.java:68)
	at org.takes.facets.fork.FkFixed$1.route(FkFixed.java:56)
	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:109)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:89)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:108)
	at org.takes.tk.TkGzip$1.act(TkGzip.java:58)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:73)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:86)
	... 14 more
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@Vatavuk you seem to be trying to send the form multiple time. Was it the case?

**Comment by Vatavuk** [comment]
@yegor256 The error popped out when I submitted the form for the first time. Above is the stack trace from the second attempt. 
Now I submitted it through IE and it works.

**Comment by yegor256** [comment]
@Vatavuk I don't think it's reproducible. The text `someText` was submitted in the form. I believe, it was a temporary problem on the user side. Anyway, it's not fixable.
