### ISSUE TITLE
Rultor build is failing due to Jacoco coverage check.

### ISSUE THREAD

**Issue by carlosmiranda** [zerocracy/farm#922]
Recent Rultor builds have been failing; see for example:

https://github.com/zerocracy/farm/issues/909#issuecomment-380346765
https://github.com/zerocracy/farm/pull/913#issuecomment-380439641

```java
Results :

Tests run: 324, Failures: 0, Errors: 0, Skipped: 5

[ERROR] Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.0:check (jacoco-check) on project farm: Coverage checks have not been met. See log for details. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.0:check (jacoco-check) on project farm: Coverage checks have not been met. See log for details.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Coverage checks have not been met. See log for details.
	at org.jacoco.maven.CheckMojo.executeCheck(CheckMojo.java:187)
	at org.jacoco.maven.CheckMojo.executeMojo(CheckMojo.java:161)
	at org.jacoco.maven.AbstractJacocoMojo.execute(AbstractJacocoMojo.java:63)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
container fd5f3c43af3dab4437ad6a721719685b9706f419c8ae46599a299687bdc247de is dead
Wed Apr 11 08:53:14 CEST 2018
```

Might have had something to do with the change in https://github.com/zerocracy/farm/commit/e91aab5495eb23073217933325229a131303f343. Let's investigate and fix.

**Comment by g4s8** [comment]
@carlosmiranda was this job fixed, can we close?

**Comment by carlosmiranda** [comment]
@g4s8 yes, thanks. Seems that I missed this one

**Comment by 0crat** [comment]
Job [#922](https://github.com/zerocracy/farm/issues/922) is not in the agenda of @yegor256[/z](https://www.0crat.com/u/yegor256), can't retrieve data and time of add

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#922](https://github.com/zerocracy/farm/issues/922) is now out of scope
