### ISSUE TITLE
ExtTelegram reconnects

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#936]
```
2018-04-15T06:06:21.041608+00:00 app[web.1]: Apr 15, 2018 6:06:21 AM org.telegram.telegrambots.logging.BotLogger severe
2018-04-15T06:06:21.041624+00:00 app[web.1]: SEVERE: BOTSESSION
2018-04-15T06:06:21.041626+00:00 app[web.1]: org.telegram.telegrambots.exceptions.TelegramApiRequestException: Error getting updates: [409] Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2018-04-15T06:06:21.041628+00:00 app[web.1]: 	at org.telegram.telegrambots.api.methods.updates.GetUpdates.deserializeResponse(GetUpdates.java:119)
2018-04-15T06:06:21.041630+00:00 app[web.1]: 	at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$ReaderThread.getUpdatesFromServer(DefaultBotSession.java:262)
2018-04-15T06:06:21.041631+00:00 app[web.1]: 	at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$ReaderThread.run(DefaultBotSession.java:191)
2018-04-15T06:06:21.041633+00:00 app[web.1]:undefined
```

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
