### ISSUE TITLE
TelegramApiRequestException: Error sending message: [400] Bad Request: can't parse entities: Can't find end of the entity

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#942]
```
java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/comm/notify_telegram.groovy
	at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:125)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:81)
	at com.zerocracy.farm.reactive.StkSmart.process(StkSmart.java:66)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:82)
	at com.zerocracy.farm.reactive.Brigade.lambda$apply$0(Brigade.java:64)
	at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.iterator.Filtered.hasNext(Filtered.java:90)
	at org.cactoos.iterator.LengthOf.lambda$new$0(LengthOf.java:52)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.scalar.NumberEnvelope.doubleValue(NumberEnvelope.java:113)
	at org.cactoos.iterable.LengthOf.lambda$new$0(LengthOf.java:51)
	at org.cactoos.scalar.NumberEnvelope.lambda$new$1(NumberEnvelope.java:73)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.scalar.NumberEnvelope.intValue(NumberEnvelope.java:98)
	at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:67)
	at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:37)
	at org.cactoos.func.IoCheckedBiFunc.lambda$apply$0(IoCheckedBiFunc.java:60)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:61)
	at com.zerocracy.farm.reactive.DefaultFlush.process(DefaultFlush.java:98)
	at com.zerocracy.farm.reactive.DefaultFlush.lambda$exec$0(DefaultFlush.java:67)
	at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
	at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
	at org.cactoos.func.IoCheckedFunc.lambda$apply$0(IoCheckedFunc.java:59)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:59)
	at org.cactoos.func.IoCheckedProc.exec(IoCheckedProc.java:57)
	at com.zerocracy.pm.Claims.take(Claims.java:143)
	at com.zerocracy.farm.reactive.DefaultFlush.exec(DefaultFlush.java:66)
	at com.zerocracy.farm.reactive.DefaultFlush.exec(DefaultFlush.java:44)
	at com.zerocracy.farm.reactive.AsyncFlush.lambda$exec$2(AsyncFlush.java:118)
	at com.jcabi.log.VerboseCallable.call(VerboseCallable.java:173)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:221)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:115)
	... 41 more
Caused by: org.telegram.telegrambots.exceptions.TelegramApiRequestException: Error sending message: [400] Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 65
	at org.telegram.telegrambots.api.methods.send.SendMessage.deserializeResponse(SendMessage.java:170)
	at org.telegram.telegrambots.api.methods.send.SendMessage.deserializeResponse(SendMessage.java:24)
	at org.telegram.telegrambots.bots.DefaultAbsSender.sendApiMethod(DefaultAbsSender.java:690)
	at com.zerocracy.radars.telegram.TmZerocrat.post(TmZerocrat.java:80)
	at com.zerocracy.radars.telegram.TmZerocrat$post.call(Unknown Source)
	at com.zerocracy.stk.pm.comm.notify_telegram$1.exec(notify_telegram.groovy:48)
	at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
	at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
	at org.cactoos.func.RetryFunc.apply(RetryFunc.java:118)
	at org.cactoos.Func$apply.call(Unknown Source)
	at com.zerocracy.stk.pm.comm.notify_telegram.exec(notify_telegram.groovy:41)
	... 46 more
```

It seems that we have to preprocess/filter the text somehow, before sending it to Telegram API.

This was the message:

```
Stripe customer `cus_ChVVYPLyZcJxxx` charged $16.00 for "RFP": ch_1CI6ULHUMSJnVjMYrflt4xxx
```

It seems that it chokes on the underscore.

**Comment by 0crat** [comment]
Job [#942](https://github.com/zerocracy/farm/issues/942) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#942](https://github.com/zerocracy/farm/issues/942) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1562025418); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by g4s8** [comment]
@yegor256 it seems this bug was fixed already, can't find same error in Sentry now

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/942#issuecomment-472960188))

@g4s8 The user @g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#942](https://github.com/zerocracy/farm/issues/942), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#942` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#942](https://github.com/zerocracy/farm/issues/942) is now out of scope
